package com.dhikr.app.core.backup

import com.dhikr.app.core.database.entity.RoutineEntity
import com.dhikr.app.core.database.entity.RoutineStepEntity
import com.dhikr.app.core.database.entity.SessionEntity
import com.dhikr.app.core.database.entity.TasbihEntity
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Bump when the on-disk shape changes incompatibly. A file whose [BackupFile.version]
 *  exceeds this is rejected on import. */
const val BACKUP_FORMAT = "dhikr.backup"
const val BACKUP_VERSION = 1

@Serializable
data class BackupFile(
    val format: String = BACKUP_FORMAT,
    val version: Int = BACKUP_VERSION,
    val createdAt: Long = 0L,
    val appVersionName: String = "",
    val customTasbih: List<BackupTasbih> = emptyList(),
    val builtInFavorites: List<String> = emptyList(),
    val customRoutines: List<BackupRoutine> = emptyList(),
    val sessions: List<BackupSession> = emptyList(),
    val preferences: BackupPreferences = BackupPreferences(),
)

@Serializable
data class BackupTasbih(
    val id: String,
    val name: String,
    val arabic: String,
    // Renamed from `transliteration`; default keeps older backup files readable.
    val pronunciation: String = "",
    val translation: String,
    val note: String = "",
    val source: String? = null,
    val lapTarget: Int,
    val lapCount: Int,
    val dailyGoal: Int? = null,
    val isFavorite: Boolean = false,
    val createdAt: Long,
    val updatedAt: Long,
) {
    /** Restored rows are always custom, regardless of what device they came from. */
    fun toEntity() = TasbihEntity(
        id = id,
        name = name,
        arabic = arabic,
        pronunciation = pronunciation,
        translation = translation,
        note = note,
        source = source,
        lapTarget = lapTarget,
        lapCount = lapCount,
        dailyGoal = dailyGoal,
        isFavorite = isFavorite,
        isBuiltIn = false,
        createdAt = createdAt,
        updatedAt = updatedAt,
    )

    companion object {
        fun from(e: TasbihEntity) = BackupTasbih(
            id = e.id,
            name = e.name,
            arabic = e.arabic,
            pronunciation = e.pronunciation,
            translation = e.translation,
            note = e.note,
            source = e.source,
            lapTarget = e.lapTarget,
            lapCount = e.lapCount,
            dailyGoal = e.dailyGoal,
            isFavorite = e.isFavorite,
            createdAt = e.createdAt,
            updatedAt = e.updatedAt,
        )
    }
}

@Serializable
data class BackupRoutine(
    val id: String,
    val name: String,
    val createdAt: Long,
    val updatedAt: Long,
    val steps: List<BackupRoutineStep> = emptyList(),
) {
    fun toEntity() = RoutineEntity(
        id = id,
        name = name,
        isPreset = false,
        createdAt = createdAt,
        updatedAt = updatedAt,
    )
}

@Serializable
data class BackupRoutineStep(
    val tasbihId: String,
    val stepOrder: Int,
    val targetCount: Int,
) {
    /** stepId is autogenerated by Room on insert. */
    fun toEntity(routineId: String) = RoutineStepEntity(
        routineId = routineId,
        tasbihId = tasbihId,
        stepOrder = stepOrder,
        targetCount = targetCount,
    )

    companion object {
        fun from(e: RoutineStepEntity) = BackupRoutineStep(
            tasbihId = e.tasbihId,
            stepOrder = e.stepOrder,
            targetCount = e.targetCount,
        )
    }
}

@Serializable
data class BackupSession(
    val tasbihId: String,
    val routineId: String? = null,
    val count: Int,
    val startedAt: Long,
    val endedAt: Long,
) {
    /** id is autogenerated by Room on insert. */
    fun toEntity() = SessionEntity(
        tasbihId = tasbihId,
        routineId = routineId,
        count = count,
        startedAt = startedAt,
        endedAt = endedAt,
    )

    companion object {
        fun from(e: SessionEntity) = BackupSession(
            tasbihId = e.tasbihId,
            routineId = e.routineId,
            count = e.count,
            startedAt = e.startedAt,
            endedAt = e.endedAt,
        )
    }
}

/** Enum values stored as their `name` strings, matching AppPreferencesRepository.
 *  Absent/unknown fields fall back to the same defaults the preference flows use. */
@Serializable
data class BackupPreferences(
    @SerialName("dailyGoalTarget") val dailyGoalTarget: Int? = null,
    @SerialName("themeMode") val themeMode: String? = null,
    @SerialName("hapticMode") val hapticMode: String? = null,
    @SerialName("reducedMotion") val reducedMotion: Boolean? = null,
    @SerialName("dynamicColor") val dynamicColor: Boolean? = null,
    @SerialName("counterScript") val counterScript: String? = null,
)

/** Summary of what a restore actually wrote, surfaced to the user. */
data class RestoreResult(
    val tasbihRestored: Int,
    val routinesRestored: Int,
    val sessionsRestored: Int,
    val sessionsSkipped: Int,
    val preferencesApplied: Boolean,
)
