package com.dhikr.app.core.database.seed

import com.dhikr.app.core.database.entity.RoutineEntity
import com.dhikr.app.core.database.entity.RoutineStepEntity
import com.dhikr.app.core.database.entity.TasbihEntity

object SeedData {
    private const val SEED_TIMESTAMP = 0L

    // Compact builder for the added dhikr below. Arabic is fully vowelled;
    // `pronunciation` is the Bangla transliteration; `translation` carries the
    // Bangla meaning followed by the English; `note` records source + grade and
    // any note on the recitation count. Counts follow an authentic sunnah figure
    // where a hadith fixes one, otherwise the user-supplied number.
    private fun dhikr(
        id: String,
        name: String,
        arabic: String,
        pronunciation: String,
        translation: String,
        lapTarget: Int,
        note: String = "",
        source: String? = null,
    ) = TasbihEntity(
        id = id,
        name = name,
        arabic = arabic,
        pronunciation = pronunciation,
        translation = translation,
        note = note,
        source = source,
        lapTarget = lapTarget,
        lapCount = 1,
        isFavorite = false,
        isBuiltIn = true,
        createdAt = SEED_TIMESTAMP,
        updatedAt = SEED_TIMESTAMP,
    )

    private fun name(
        n: Int,
        translit: String,
        arabic: String,
        bangla: String,
        meaningBn: String,
        meaningEn: String,
    ) = TasbihEntity(
        id = "asma_%02d".format(n),
        name = translit,
        arabic = arabic,
        pronunciation = bangla,
        translation = "$meaningBn — $meaningEn",
        note = "আসমাউল হুসনা #$n। ৯৯ নামের প্রসিদ্ধ তালিকা — তিরমিযি ৩৫০৭, ইবনে মাজাহ ৩৮৬১।",
        source = "Jami at-Tirmidhi 3507",
        lapTarget = 3,
        lapCount = 1,
        isFavorite = false,
        isBuiltIn = true,
        createdAt = SEED_TIMESTAMP,
        updatedAt = SEED_TIMESTAMP,
    )

    val builtInTasbih: List<TasbihEntity> by lazy {
        coreTasbih + asmaUlHusnaList
    }

    /**
     * Built-in dhikr ids retired from the free Tasbih library: situational /
     * occasion-bound duas (morning-evening adhkar, in-salah phrases, travel,
     * weather, greetings, funeral, hajj, one-off event duas) that don't fit a
     * "recite whenever you want" counter. They are gone from [builtInTasbih] for
     * fresh installs, and [DhikrApplication] purges them from existing databases
     * on launch — skipping any the user favourited or that a routine step still
     * references (routine_step -> tasbih is RESTRICT).
     */
    val retiredBuiltInIds: Set<String> = setOf(
        // From the original "added dhikr" block
        "malik_quddus", "kalimat_tammat",
        // Morning & evening adhkar
        "sayyidul_istighfar", "bismillah_la_yadurru", "raditu_billah", "asbahna_bika",
        "amsayna_bika", "asbahna_mulk", "amsayna_mulk", "afini_badan", "kufr_faqr",
        "rahmataka_arju", "alimal_ghayb", "wake_afiyah", "morning_three_quls",
        "afiyah_dunya_akhirah",
        // Waking & sleeping
        "wake_alhamdu", "sleep_bismika", "sleep_three_quls", "sleep_aslamtu",
        "night_wake_tahlil", "night_turn", "night_terror", "baqarah_last_two",
        // Wudu, toilet, home, clothes, eating
        "toilet_enter", "toilet_exit", "wudu_shahada", "wudu_tawwabin", "enter_home",
        "leave_home", "undress", "new_clothes", "eat_bismillah", "eat_forgot_bismillah",
        "eat_after", "after_milk",
        // Masjid & adhan
        "masjid_enter", "masjid_exit", "adhan_response", "after_adhan",
        // Inside salah
        "ruku", "sujud", "subbuh_quddus", "sami_allah", "rabbana_lakal_hamd",
        "between_sujud", "tashahhud", "durood_ibrahim", "dua_masura", "four_refuge_salah",
        "after_salah_salam", "ainni_dhikr", "tahajjud_hamd", "sujud_tilawah", "qunut",
        // Event / feeling triggered
        "amantu_billah", "masha_allah", "kaffarat_majlis", "khashyah_dua", "sahl",
        "musibah", "condolence", "good_news", "alhamdu_kulli_hal", "hamm_qalb_quran",
        "tiyarah", "taqabbal", "istikhara",
        // Distress / protection borderline, retired
        "karb_dua", "fear_dua", "ya_hayyu_aslih", "shirk_refuge", "hamm_hazan_full",
        "dua_yunus", "taawwudh",
        // Travel
        "ride_vehicle", "travel_return", "return_home_tawbah", "travel_ascend",
        "farewell_traveler", "farewell_traveler2", "traveler_farewell",
        // Weather & nature
        "rain_start", "rain_after", "rain_excess", "wind", "thunder", "new_moon",
        // Sneeze, greeting, social
        "sneeze_response", "sneeze_reply", "salam", "salam_reply", "jazakallah",
        "love_fillah", "love_reply", "musafaha", "newlywed", "barakallah_debt",
        "new_clothes_dua1", "new_clothes_dua2", "guest_dua", "iftar_host", "feeder_dua",
        "new_fruit",
        // Sickness & the deceased
        "visit_sick", "sick_visit_7", "see_afflicted", "children_protection", "janazah",
        "grave_lowering", "after_burial", "grave_visit",
        // Hajj / Umrah / Qurbani
        "safa_marwah", "hajar_aswad", "maqam_ibrahim", "qurbani",
    )

    private val coreTasbih: List<TasbihEntity> = listOf(
        TasbihEntity(
            id = "kursi",
            name = "Ayatul Kursi",
            arabic = "",
            pronunciation = "আল্লাহু লা ইলাহা ইল্লা হুয়াল হাইয়্যুল কইয়্যুমু লা তা খুজুহু সিনাত্যু ওয়ালা নাউম। " +
                "লাহু মা ফিছছামা ওয়াতি ওয়ামা ফিল আরদ। মান যাল্লাযী ইয়াস ফায়ু ইন দাহু ইল্লা বি ইজনিহি ইয়া লামু মা " +
                "বাইনা আইদিহিম ওয়ামা খল ফাহুম ওয়ালা ইউ হিতুনা বিশাই ইম্ মিন ইল্ মিহি ইল্লা বিমা সাআ ওয়াসিয়া " +
                "কুরসিইউ হুস ছামা ওয়াতি ওয়াল আরদ্ ওয়ালা ইয়া উদুহু হিফজুহুমা ওয়াহুয়াল আলিয়্যুল আজিম",
            translation = "",
            lapTarget = 7,
            lapCount = 1,
            isFavorite = true,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "subhan",
            name = "SubhanAllah",
            arabic = "سُبْحَانَ اللّٰه",
            pronunciation = "সুবহানাল্লাহ",
            translation = "Glory be to Allah",
            lapTarget = 33,
            lapCount = 3,
            isFavorite = true,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "hamd",
            name = "Alhamdulillah",
            arabic = "الْحَمْدُ لِلّٰه",
            pronunciation = "আলহামদুলিল্লাহ",
            translation = "All praise is due to Allah",
            lapTarget = 33,
            lapCount = 3,
            isFavorite = true,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "akbar",
            name = "Allahu Akbar",
            arabic = "اللّٰهُ أَكْبَر",
            pronunciation = "আল্লাহু আকবার",
            translation = "Allah is the greatest",
            lapTarget = 34,
            lapCount = 3,
            isFavorite = true,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "istighfar",
            name = "Astaghfirullah",
            arabic = "أَسْتَغْفِرُ اللّٰه",
            pronunciation = "আস্তাগফিরুল্লাহ",
            translation = "I seek forgiveness from Allah",
            lapTarget = 100,
            lapCount = 1,
            isFavorite = false,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "bihamdihi",
            name = "Subhanallahi wa bihamdihi",
            arabic = "سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ",
            pronunciation = "সুবহানাল্লাহি ওয়া বিহামদিহি",
            translation = "Glory be to Allah and praise be to Him",
            lapTarget = 100,
            lapCount = 1,
            isFavorite = false,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "hawla",
            name = "La hawla wa la quwwata illa billah",
            arabic = "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللّٰه",
            pronunciation = "লা হাওলা ওয়ালা কুওয়াতা ইল্লা বিল্লাহ",
            translation = "There is no power nor strength except with Allah",
            lapTarget = 33,
            lapCount = 1,
            isFavorite = false,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),

        // --- Added dhikr (researched + verified) ------------------------------
        dhikr(
            id = "tahlil",
            name = "La ilaha illallah",
            arabic = "لَا إِلَٰهَ إِلَّا اللّٰهُ",
            pronunciation = "লা ইলাহা ইল্লাল্লাহ",
            translation = "আল্লাহ ছাড়া কোনো সত্য উপাস্য নেই — There is no true god but Allah",
            lapTarget = 100,
            note = "শ্রেষ্ঠ যিকর। “আফযালুয যিকরি লা ইলাহা ইল্লাল্লাহ” — তিরমিযি ৩৩৮৩ (হাসান)।",
            source = "Jami at-Tirmidhi 3383",
        ),
        dhikr(
            id = "bihamdihi_azim",
            name = "Subhanallahi wa bihamdihi, Subhanallahil Azim",
            arabic = "سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ، سُبْحَانَ اللّٰهِ الْعَظِيمِ",
            pronunciation = "সুবহানাল্লাহি ওয়া বিহামদিহি, সুবহানাল্লাহিল আযীম",
            translation = "আল্লাহ পবিত্র ও তাঁরই প্রশংসা, মহান আল্লাহ পবিত্র — Glory and praise be to Allah, glory be to Allah the Most Great",
            lapTarget = 100,
            note = "জিহ্বায় হালকা, মিযানে ভারী, রহমানের কাছে প্রিয় দুই বাক্য — সহীহ বুখারি ৬৪০৬। নির্দিষ্ট সংখ্যা হাদিসে নেই; ১০০ ব্যবহারকারীর পছন্দ।",
            source = "Sahih al-Bukhari 6406",
        ),
        dhikr(
            id = "durood_ali",
            name = "Allahumma salli ala Muhammadin wa ala ali Muhammad",
            arabic = "اللّٰهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ",
            pronunciation = "আল্লাহুম্মা সাল্লি আলা মুহাম্মাদিন ওয়া আলা আলি মুহাম্মাদ",
            translation = "হে আল্লাহ, মুহাম্মাদ ও তাঁর পরিবারের প্রতি রহমত বর্ষণ করুন — O Allah, send blessings upon Muhammad and the family of Muhammad",
            lapTarget = 100,
            note = "দরূদ। সকাল-সন্ধ্যায় ১০ বার পড়লে কিয়ামতে শাফাআত — তাবারানি। নির্দিষ্ট ১০০ সংখ্যা হাদিসে নেই।",
            source = "al-Mu'jam al-Awsat (Tabarani)",
        ),
        dhikr(
            id = "tahlil_wahdahu",
            name = "La ilaha illallahu wahdahu la sharika lah",
            arabic = "لَا إِلَٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
            pronunciation = "লা ইলাহা ইল্লাল্লাহু ওয়াহদাহু লা শারিকা লাহু, লাহুল মুলকু ওয়া লাহুল হামদু ওয়া হুয়া আলা কুল্লি শাইইন কাদীর",
            translation = "আল্লাহ ছাড়া কোনো উপাস্য নেই, তিনি একক, তাঁর কোনো শরিক নেই; রাজত্ব ও প্রশংসা তাঁরই, তিনি সর্বশক্তিমান — There is no god but Allah alone, no partner has He; His is the dominion and the praise, and He is able to do all things",
            lapTarget = 100,
            note = "দিনে ১০০ বার = ১০ জন দাস মুক্তির সওয়াব, ১০০ নেকি, ১০০ গুনাহ মাফ, সন্ধ্যা পর্যন্ত শয়তান থেকে রক্ষা — সহীহ বুখারি ৩২৯৩, মুসলিম ২৬৯১। সুন্নাহ সংখ্যা ১০০।",
            source = "Sahih al-Bukhari 3293; Sahih Muslim 2691",
        ),
        dhikr(
            id = "hasbunallah",
            name = "Hasbunallahu wa ni'mal wakil",
            arabic = "حَسْبُنَا اللّٰهُ وَنِعْمَ الْوَكِيلُ",
            pronunciation = "হাসবুনাল্লাহু ওয়া নিমাল ওয়াকীল",
            translation = "আল্লাহই আমাদের জন্য যথেষ্ট, তিনিই উত্তম কর্মবিধায়ক — Allah is sufficient for us, and He is the best disposer of affairs",
            lapTarget = 100,
            note = "কুরআন ৩:১৭৩ — উহুদের পর সাহাবিদের এবং আগুনে নিক্ষেপের সময় ইবরাহিম (আঃ)-এর বাণী। নির্দিষ্ট সংখ্যা নেই।",
            source = "Quran 3:173",
        ),
        dhikr(
            id = "baqiyat",
            name = "Subhanallah walhamdulillah wa la ilaha illallahu wallahu akbar",
            arabic = "سُبْحَانَ اللّٰهِ وَالْحَمْدُ لِلّٰهِ وَلَا إِلَٰهَ إِلَّا اللّٰهُ وَاللّٰهُ أَكْبَرُ",
            pronunciation = "সুবহানাল্লাহি ওয়ালহামদু লিল্লাহি ওয়া লা ইলাহা ইল্লাল্লাহু ওয়াল্লাহু আকবার",
            translation = "আল্লাহ পবিত্র, সকল প্রশংসা আল্লাহর, আল্লাহ ছাড়া কোনো উপাস্য নেই, আল্লাহ সর্বমহান — Glory be to Allah, praise be to Allah, there is no god but Allah, and Allah is the Greatest",
            lapTarget = 33,
            note = "আল্লাহর কাছে সবচেয়ে প্রিয় চার বাক্য — সহীহ মুসলিম ২১৩৭। নির্দিষ্ট সংখ্যা নেই।",
            source = "Sahih Muslim 2137",
        ),
        dhikr(
            id = "afuww",
            name = "Allahumma innaka afuwwun tuhibbul afwa fa'fu anni",
            arabic = "اللّٰهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي",
            pronunciation = "আল্লাহুম্মা ইন্নাকা আফুউন তুহিব্বুল আফওয়া ফা'ফু আন্নি",
            translation = "হে আল্লাহ, আপনি ক্ষমাশীল, ক্ষমা ভালোবাসেন, তাই আমাকে ক্ষমা করুন — O Allah, You are Most Forgiving, You love to forgive, so forgive me",
            lapTarget = 33,
            note = "লাইলাতুল কদরের দুআ, নবি (সাঃ) আয়েশা (রাঃ)-কে শিখিয়েছেন — তিরমিযি ৩৫১৩, ইবনে মাজাহ ৩৮৫০ (হাসান)। “কারীম” শব্দ যোগ প্রমাণিত নয়।",
            source = "Jami at-Tirmidhi 3513",
        ),
        dhikr(
            id = "salli_nabiyyina",
            name = "Allahumma salli wa sallim ala nabiyyina Muhammad",
            arabic = "اللّٰهُمَّ صَلِّ وَسَلِّمْ عَلَىٰ نَبِيِّنَا مُحَمَّدٍ",
            pronunciation = "আল্লাহুম্মা সাল্লি ওয়া সাল্লিম আলা নাবিয়্যিনা মুহাম্মাদ",
            translation = "হে আল্লাহ, আমাদের নবি মুহাম্মাদের প্রতি রহমত ও শান্তি বর্ষণ করুন — O Allah, send blessings and peace upon our Prophet Muhammad",
            lapTarget = 33,
            note = "সাধারণ দরূদ; নবি (সাঃ)-এর প্রতি সালাত পাঠের আদেশ কুরআন ৩৩:৫৬-এ।",
            source = "Quran 33:56",
        ),
        dhikr(
            id = "musa_faqir",
            name = "Rabbi inni lima anzalta ilayya min khayrin faqir",
            arabic = "رَبِّ إِنِّي لِمَا أَنْزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ",
            pronunciation = "রব্বি ইন্নি লিমা আনযালতা ইলাইয়া মিন খাইরিন ফাকির",
            translation = "হে আমার রব, আপনি আমার প্রতি যে কল্যাণ নাযিল করবেন আমি তার মুখাপেক্ষী — My Lord, I am in need of whatever good You send down to me",
            lapTarget = 33,
            note = "কুরআন ২৮:২৪ — মাদইয়ানে মুসা (আঃ)-এর দুআ।",
            source = "Quran 28:24",
        ),
        dhikr(
            id = "ism_azam",
            name = "Dua with Allah's Greatest Name",
            arabic = "اللّٰهُمَّ إِنِّي أَسْأَلُكَ بِأَنِّي أَشْهَدُ أَنَّكَ أَنْتَ اللّٰهُ لَا إِلَٰهَ إِلَّا أَنْتَ الْأَحَدُ الصَّمَدُ الَّذِي لَمْ يَلِدْ وَلَمْ يُولَدْ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ",
            pronunciation = "আল্লাহুম্মা ইন্নি আসআলুকা বিআন্নি আশহাদু আন্নাকা আনতাল্লাহু লা ইলাহা ইল্লা আনতাল আহাদুস সামাদু আল্লাযি লাম ইয়ালিদ ওয়া লাম ইউলাদ ওয়া লাম ইয়াকুল্লাহু কুফুওয়ান আহাদ",
            translation = "হে আল্লাহ, আমি আপনার কাছে চাই এই সাক্ষ্যের অসিলায় যে আপনিই আল্লাহ, আপনি ছাড়া কোনো উপাস্য নেই, এক, অমুখাপেক্ষী, যিনি জন্ম দেননি ও জন্মগ্রহণ করেননি, তাঁর সমকক্ষ কেউ নেই — O Allah, I ask You by my testimony that You are Allah, there is no god but You, the One, the Eternal Refuge, who neither begets nor is born, and there is none comparable to Him",
            lapTarget = 33,
            note = "আল্লাহর ইসমে আযম দিয়ে দুআ — নবি (সাঃ) বলেছেন এই নামে চাইলে দেওয়া হয়, ডাকলে সাড়া দেওয়া হয়। আবু দাউদ ১৪৯৩, তিরমিযি ৩৪৭৫ (সহীহ)।",
            source = "Sunan Abi Dawud 1493",
        ),
        dhikr(
            id = "hasbiyallah_arsh",
            name = "Hasbiyallahu la ilaha illa huwa alayhi tawakkaltu",
            arabic = "حَسْبِيَ اللّٰهُ لَا إِلَٰهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
            pronunciation = "হাসবিয়াল্লাহু লা ইলাহা ইল্লা হুয়া আলাইহি তাওয়াক্কালতু ওয়া হুয়া রব্বুল আরশিল আযীম",
            translation = "আল্লাহই আমার জন্য যথেষ্ট, তিনি ছাড়া কোনো উপাস্য নেই, তাঁর ওপরই ভরসা করলাম, তিনি মহান আরশের রব — Allah is sufficient for me; there is no god but Him; in Him I put my trust; He is the Lord of the Mighty Throne",
            lapTarget = 7,
            note = "কুরআন ৯:১২৯-এর অংশ। সকালে ও সন্ধ্যায় ৭ বার পড়লে আল্লাহ দুনিয়া-আখিরাতের চিন্তা থেকে যথেষ্ট হন — আবু দাউদ ৫০৮১ (হাসান/সহীহ ইসনাদ)। সুন্নাহ সংখ্যা ৭।",
            source = "Sunan Abi Dawud 5081",
        ),
        dhikr(
            id = "maghfirli",
            name = "Allahummaghfirli",
            arabic = "اللّٰهُمَّ اغْفِرْ لِي",
            pronunciation = "আল্লাহুম্মাগফিরলি",
            translation = "হে আল্লাহ, আমাকে ক্ষমা করুন — O Allah, forgive me",
            lapTarget = 33,
            note = "সংক্ষিপ্ত ইস্তিগফার; নবি (সাঃ) সিজদায় ও অন্যত্র বহুবার পড়তেন।",
            source = null,
        ),
        dhikr(
            id = "parents_rahmah",
            name = "Rabbir hamhuma kama rabbayani sagira",
            arabic = "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
            pronunciation = "রব্বির হামহুমা কামা রব্বায়ানি সাগীরা",
            translation = "হে আমার রব, পিতা-মাতার প্রতি দয়া করুন যেভাবে তারা আমাকে ছোটবেলায় লালন করেছেন — My Lord, have mercy upon them as they raised me when I was small",
            lapTarget = 33,
            note = "কুরআন ১৭:২৪ — পিতা-মাতার জন্য দুআ।",
            source = "Quran 17:24",
        ),
        dhikr(
            id = "jannah_nar",
            name = "Allahumma inni as'alukal jannata wa a'udhu bika minan nar",
            arabic = "اللّٰهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ وَأَعُوذُ بِكَ مِنَ النَّارِ",
            pronunciation = "আল্লাহুম্মা ইন্নি আসআলুকাল জান্নাতা ওয়া আউযু বিকা মিনান নার",
            translation = "হে আল্লাহ, আমি আপনার কাছে জান্নাত চাই এবং জাহান্নাম থেকে আশ্রয় চাই — O Allah, I ask You for Paradise and seek refuge in You from the Fire",
            lapTarget = 3,
            note = "৩ বার চাইলে জান্নাত বলে “তাকে প্রবেশ করাও”, ৩ বার আশ্রয় চাইলে জাহান্নাম বলে “তাকে রক্ষা করো” — তিরমিযি ২৫৭২, ইবনে মাজাহ ৩৮৪৬। সুন্নাহ সংখ্যা ৩।",
            source = "Jami at-Tirmidhi 2572",
        ),
        dhikr(
            id = "istighfar_qayyum",
            name = "Astaghfirullahal azimalladhi la ilaha illa huwal hayyul qayyum wa atubu ilayh",
            arabic = "أَسْتَغْفِرُ اللّٰهَ الْعَظِيمَ الَّذِي لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
            pronunciation = "আস্তাগফিরুল্লাহাল আযীমাল্লাযি লা ইলাহা ইল্লা হুয়াল হাইয়্যুল কাইয়্যূমু ওয়া আতুবু ইলাইহি",
            translation = "আমি ক্ষমা চাই মহান আল্লাহর কাছে, যিনি ছাড়া কোনো উপাস্য নেই, চিরঞ্জীব, সর্বসত্তার ধারক, এবং তাঁর কাছেই তওবা করি — I seek forgiveness of Allah the Mighty, there is no god but Him, the Ever-Living, the Sustainer, and I turn to Him in repentance",
            lapTarget = 33,
            note = "এটি পড়লে গুনাহ মাফ হয় যদিও সে যুদ্ধক্ষেত্র থেকে পালিয়ে থাকে — আবু দাউদ ১৫১৭, তিরমিযি ৩৫৭৭ (হাকিম: সহীহ)। নির্দিষ্ট সংখ্যা নেই।",
            source = "Sunan Abi Dawud 1517",
        ),
        dhikr(
            id = "ya_hayyu_astaghith",
            name = "Ya Hayyu ya Qayyum bi rahmatika astaghith",
            arabic = "يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ",
            pronunciation = "ইয়া হাইয়্যু ইয়া কাইয়্যূমু বিরাহমাতিকা আসতাগীছু",
            translation = "হে চিরঞ্জীব, হে সর্বসত্তার ধারক, আপনার রহমতের অসিলায় সাহায্য প্রার্থনা করি — O Ever-Living, O Sustainer, by Your mercy I seek relief",
            lapTarget = 33,
            note = "কোনো বিষয় নবি (সাঃ)-কে পীড়া দিলে তিনি এটি পড়তেন — তিরমিযি ৩৫২৪ (হাসান ইসনাদ; আলবানি/মুনযিরি)।",
            source = "Jami at-Tirmidhi 3524",
        ),
        dhikr(
            id = "huda_tuqa",
            name = "Allahumma inni as'alukal huda wat tuqa wal afafa wal ghina",
            arabic = "اللّٰهُمَّ إِنِّي أَسْأَلُكَ الْهُدَىٰ وَالتُّقَىٰ وَالْعَفَافَ وَالْغِنَىٰ",
            pronunciation = "আল্লাহুম্মা ইন্নি আসআলুকাল হুদা ওয়াত তুকা ওয়াল আফাফা ওয়াল গিনা",
            translation = "হে আল্লাহ, আমি আপনার কাছে চাই হেদায়েত, তাকওয়া, পবিত্রতা ও অভাবমুক্তি — O Allah, I ask You for guidance, piety, chastity and self-sufficiency",
            lapTarget = 33,
            note = "নবি (সাঃ)-এর দুআ, ইবনে মাসউদ (রাঃ) বর্ণিত — সহীহ মুসলিম ২৭২১।",
            source = "Sahih Muslim 2721",
        ),
        dhikr(
            id = "muqallib_qulub",
            name = "Ya muqallibal qulubi thabbit qalbi ala dinik",
            arabic = "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَىٰ دِينِكَ",
            pronunciation = "ইয়া মুকাল্লিবাল কুলুবি ছাব্বিত কালবি আলা দীনিকা",
            translation = "হে অন্তরসমূহের পরিবর্তনকারী, আমার অন্তরকে আপনার দ্বীনের ওপর অবিচল রাখুন — O Turner of hearts, keep my heart firm upon Your religion",
            lapTarget = 33,
            note = "নবি (সাঃ) অধিক পড়তেন — তিরমিযি ২১৪০ (হাসান)।",
            source = "Jami at-Tirmidhi 2140",
        ),
        dhikr(
            id = "hamm_hazan",
            name = "Allahumma inni a'udhu bika minal hammi wal hazan",
            arabic = "اللّٰهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ",
            pronunciation = "আল্লাহুম্মা ইন্নি আউযু বিকা মিনাল হাম্মি ওয়াল হাযান",
            translation = "হে আল্লাহ, আমি দুশ্চিন্তা ও দুঃখ থেকে আপনার আশ্রয় চাই — O Allah, I seek refuge in You from anxiety and grief",
            lapTarget = 33,
            note = "পূর্ণ দুআ: “…ওয়াল আজযি ওয়াল কাসাল, ওয়াল জুবনি ওয়াল বুখল, ওয়া দালাইদ দাইন ওয়া গালাবাতির রিজাল” — সহীহ বুখারি ৬৩৬৯।",
            source = "Sahih al-Bukhari 6369",
        ),
        dhikr(
            id = "yassir_la_tuassir",
            name = "Allahumma yassir wa la tu'assir",
            arabic = "اللّٰهُمَّ يَسِّرْ وَلَا تُعَسِّرْ",
            pronunciation = "আল্লাহুম্মা ইয়াসসির ওয়ালা তুআসসির",
            translation = "হে আল্লাহ, সহজ করুন, কঠিন করবেন না — O Allah, make it easy and do not make it difficult",
            lapTarget = 33,
            note = "হাদিসের বাণী “ইয়াসসিরু ওয়ালা তুআসসিরু” (বুখারি ৬৯) থেকে গৃহীত দুআ-রূপ; হুবহু এই রূপে ছয় গ্রন্থে নেই। বৈধ সাধারণ দুআ।",
            source = "Sahih al-Bukhari 69",
        ),
        dhikr(
            id = "nuh_maghlub",
            name = "Rabbi inni maghlubun fantasir",
            arabic = "رَبِّ إِنِّي مَغْلُوبٌ فَانْتَصِرْ",
            pronunciation = "রব্বি ইন্নি মাগলুবুন ফানতাসির",
            translation = "হে আমার রব, আমি পরাভূত, তাই সাহায্য করুন — My Lord, I am overpowered, so help me",
            lapTarget = 100,
            note = "কুরআন ৫৪:১০ — নূহ (আঃ)-এর দুআ। তিলাওয়াতে “আন্নি”, দুআ হিসেবে “ইন্নি”। (আপনার তালিকায় ৩৩ ও ১০০ দুটোই ছিল।)",
            source = "Quran 54:10",
        ),
        dhikr(
            id = "short_salawat",
            name = "Sallallahu alaihi wa sallam",
            arabic = "صَلَّى اللّٰهُ عَلَيْهِ وَسَلَّمَ",
            pronunciation = "সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম",
            translation = "আল্লাহ তাঁর ওপর রহমত ও শান্তি বর্ষণ করুন — May Allah send blessings and peace upon him",
            lapTarget = 33,
            note = "নবি (সাঃ)-এর নাম উল্লেখে সংক্ষিপ্ত সালাত।",
            source = null,
        ),
        dhikr(
            id = "rabbighfir_tawwab",
            name = "Rabbighfir li wa tub alayya innaka antat tawwabur rahim",
            arabic = "رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ",
            pronunciation = "রব্বিগফির লি ওয়া তুব আলাইয়া ইন্নাকা আনতাত তাওয়াবুর রাহীম",
            translation = "হে আমার রব, আমাকে ক্ষমা করুন ও আমার তওবা কবুল করুন, নিশ্চয়ই আপনি তওবা কবুলকারী পরম দয়ালু — My Lord, forgive me and accept my repentance; indeed You are the Accepter of repentance, the Merciful",
            lapTarget = 100,
            note = "ইবনে উমার (রাঃ): নবি (সাঃ) এক বৈঠকে ১০০ বার এটি পড়তেন — আবু দাউদ ১৫১৬, তিরমিযি ৩৪৩৪ (সহীহ)। সুন্নাহ সংখ্যা ১০০।",
            source = "Jami at-Tirmidhi 3434",
        ),
        dhikr(
            id = "adada_khalqih",
            name = "Subhanallahi wa bihamdihi adada khalqih",
            arabic = "سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ عَدَدَ خَلْقِهِ وَرِضَا نَفْسِهِ وَزِنَةَ عَرْشِهِ وَمِدَادَ كَلِمَاتِهِ",
            pronunciation = "সুবহানাল্লাহি ওয়া বিহামদিহি আদাদা খালকিহি ওয়া রিদা নাফসিহি ওয়া যিনাতা আরশিহি ওয়া মিদাদা কালিমাতিহি",
            translation = "আল্লাহ পবিত্র ও তাঁরই প্রশংসা—তাঁর সৃষ্টির সংখ্যা, তাঁর সন্তুষ্টি, তাঁর আরশের ওজন ও তাঁর বাণীসমূহের কালি পরিমাণ — Glory and praise be to Allah, as many as His creation, as pleases Him, as the weight of His Throne and the ink of His words",
            lapTarget = 3,
            note = "জুওয়াইরিয়া (রাঃ)-কে নবি (সাঃ) শিখিয়েছেন, ৩ বার পড়লে সকাল থেকে পড়া সব যিকরের চেয়ে ভারী — সহীহ মুসলিম ২৭২৬। সুন্নাহ সংখ্যা ৩; পূর্ণ রূপটি দেওয়া হলো।",
            source = "Sahih Muslim 2726",
        ),
        dhikr(
            id = "kfini_halalik",
            name = "Allahumma-kfini bi halalika an haramik",
            arabic = "اللّٰهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ",
            pronunciation = "আল্লাহুম্মাকফিনি বিহালালিকা আন হারামিকা ওয়া আগনিনি বিফাদলিকা আম্মান সিওয়াক",
            translation = "হে আল্লাহ, আপনার হালাল দিয়ে আমাকে হারাম থেকে মুক্ত রাখুন এবং আপনার অনুগ্রহে অন্য সবার থেকে অমুখাপেক্ষী করুন — O Allah, suffice me with what You have made lawful against what You have forbidden, and make me independent of all besides You by Your grace",
            lapTarget = 33,
            note = "নবি (সাঃ) আলী (রাঃ)-কে ঋণমুক্তির জন্য শিখিয়েছেন — তিরমিযি ৩৫৬৩ (হাসান)।",
            source = "Jami at-Tirmidhi 3563",
        ),
        dhikr(
            id = "sharh_sadr",
            name = "Rabbi-shrah li sadri wa yassir li amri",
            arabic = "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي وَاحْلُلْ عُقْدَةً مِنْ لِسَانِي يَفْقَهُوا قَوْلِي",
            pronunciation = "রব্বিশরাহ লি সাদরি ওয়া ইয়াসসির লি আমরি ওয়াহলুল উকদাতান মিন লিসানি ইয়াফকাহু কাওলি",
            translation = "হে আমার রব, আমার বক্ষ প্রশস্ত করুন, কাজ সহজ করুন এবং জিহ্বার জড়তা দূর করুন যাতে তারা আমার কথা বোঝে — My Lord, expand my chest, ease my task, and untie the knot from my tongue so they understand my speech",
            lapTarget = 33,
            note = "কুরআন ২০:২৫-২৮ — তূর পাহাড়ে মুসা (আঃ)-এর দুআ।",
            source = "Quran 20:25-28",
        ),
        dhikr(
            id = "fath_mubin",
            name = "Inna fatahna laka fathan mubina",
            arabic = "إِنَّا فَتَحْنَا لَكَ فَتْحًا مُبِينًا",
            pronunciation = "ইন্না ফাতাহনা লাকা ফাতহাম মুবীনা",
            translation = "নিশ্চয়ই আমি আপনাকে সুস্পষ্ট বিজয় দান করেছি — Indeed, We have given you a clear conquest",
            lapTarget = 33,
            note = "কুরআন ৪৮:১ — সূরা আল-ফাতহের প্রথম আয়াত।",
            source = "Quran 48:1",
        ),
        dhikr(
            id = "ilm_nafi",
            name = "Allahumma inni as'aluka ilman nafi'an",
            arabic = "اللّٰهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلًا مُتَقَبَّلًا",
            pronunciation = "আল্লাহুম্মা ইন্নি আসআলুকা ইলমান নাফিআন ওয়া রিযকান তাইয়্যিবান ওয়া আমালান মুতাকাব্বালান",
            translation = "হে আল্লাহ, আমি আপনার কাছে চাই উপকারী জ্ঞান, পবিত্র রিযিক ও কবুলযোগ্য আমল — O Allah, I ask You for beneficial knowledge, wholesome provision and accepted deeds",
            lapTarget = 100,
            note = "নবি (সাঃ) ফজরের পর পড়তেন, উম্মে সালামা (রাঃ) বর্ণিত — ইবনে মাজাহ ৯২৫ (সহীহ)। নির্দিষ্ট সংখ্যা নেই।",
            source = "Sunan Ibn Majah 925",
        ),
        dhikr(
            id = "nafs_mutmainnah",
            name = "Allahumma inni as'aluka nafsan bika mutma'innah",
            arabic = "اللّٰهُمَّ إِنِّي أَسْأَلُكَ نَفْسًا بِكَ مُطْمَئِنَّةً تُؤْمِنُ بِلِقَائِكَ وَتَرْضَىٰ بِقَضَائِكَ وَتَقْنَعُ بِعَطَائِكَ",
            pronunciation = "আল্লাহুম্মা ইন্নি আসআলুকা নাফসান বিকা মুতমাইন্নাতান তু'মিনু বিলিকা'ইকা ওয়া তারদা বিকাদা'ইকা ওয়া তাকনাউ বিআতা'ইকা",
            translation = "হে আল্লাহ, আমি আপনার কাছে চাই এমন প্রশান্ত আত্মা যা আপনার সাক্ষাতে বিশ্বাস রাখে, আপনার ফয়সালায় সন্তুষ্ট ও আপনার দানে পরিতৃপ্ত থাকে — O Allah, I ask You for a soul at peace with You, believing in meeting You, pleased with Your decree and content with Your provision",
            lapTarget = 33,
            note = "নবি (সাঃ) এক ব্যক্তিকে শিখিয়েছেন, আবু উমামা (রাঃ) বর্ণিত — তাবারানি; ইবনে হিব্বান সহীহ বলেছেন।",
            source = "al-Mu'jam al-Kabir (Tabarani)",
        ),
        dhikr(
            id = "istighfar_atubu",
            name = "Astaghfirullaha wa atubu ilayh",
            arabic = "أَسْتَغْفِرُ اللّٰهَ وَأَتُوبُ إِلَيْهِ",
            pronunciation = "আস্তাগফিরুল্লাহা ওয়া আতুবু ইলাইহি",
            translation = "আমি আল্লাহর কাছে ক্ষমা চাই এবং তাঁর কাছে তওবা করি — I seek Allah's forgiveness and turn to Him in repentance",
            lapTarget = 100,
            note = "নবি (সাঃ) দিনে ১০০ বার (অন্য বর্ণনায় ৭০ বারের বেশি) ইস্তিগফার করতেন — সহীহ মুসলিম ২৭০২, বুখারি ৬৩০৭। সুন্নাহ সংখ্যা ১০০।",
            source = "Sahih Muslim 2702",
        ),
        dhikr(
            id = "maridtu_yashfin",
            name = "Wa idha maridtu fahuwa yashfin",
            arabic = "وَإِذَا مَرِضْتُ فَهُوَ يَشْفِينِ",
            pronunciation = "ওয়া ইযা মারিদতু ফাহুয়া ইয়াশফীন",
            translation = "আর যখন আমি অসুস্থ হই তখন তিনিই আমাকে সুস্থ করেন — And when I am ill, it is He who cures me",
            lapTarget = 33,
            note = "কুরআন ২৬:৮০ — ইবরাহিম (আঃ)-এর বাণী; শিফার ছয় আয়াতের একটি।",
            source = "Quran 26:80",
        ),

        // --- Istighfar collection (lifewithallah.com/dhikr-dua/main-adhkar/istighfar)
        // 9 Qur'anic + 9 sunnah forms of seeking forgiveness. Sunnah #4 of that
        // page (innaka afuwwun...) is already seeded above as `afuww`. All recite
        // as supplications, so lapTarget = 3. The "Istighfar" preset routine walks
        // every one of these in the page's order.
        dhikr(
            id = "istighfar_q_yunus",
            name = "La ilaha illa Anta subhanaka inni kuntu minaz zalimin",
            arabic = "لَا إِلَٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ",
            pronunciation = "লা ইলাহা ইল্লা আনতা সুবহানাকা ইন্নি কুনতু মিনায যালিমীন",
            translation = "আপনি ছাড়া কোনো উপাস্য নেই, আপনি পবিত্র, নিশ্চয়ই আমি সীমালঙ্ঘনকারীদের অন্তর্ভুক্ত ছিলাম — There is no god worthy of worship except You; You are free from all imperfection. Indeed, I have been of the wrongdoers",
            lapTarget = 3,
            note = "কুরআন ২১:৮৭ — মাছের পেটে ইউনুস (আঃ)-এর দুআ। নবি (সাঃ) বলেছেন কোনো মুসলিম এই দুআ দিয়ে প্রার্থনা করলে তা কবুল হয় — তিরমিযি ৩৫০৫।",
            source = "Quran 21:87; Jami at-Tirmidhi 3505",
        ),
        dhikr(
            id = "istighfar_q_musa",
            name = "Rabbi inni zalamtu nafsi faghfir li",
            arabic = "رَبِّ إِنِّي ظَلَمْتُ نَفْسِي فَاغْفِرْ لِي",
            pronunciation = "রব্বি ইন্নি যালামতু নাফসি ফাগফির লি",
            translation = "হে আমার রব, আমি নিজের উপর জুলুম করেছি, তাই আমাকে ক্ষমা করুন — My Lord, I have certainly wronged myself, so forgive me",
            lapTarget = 3,
            note = "কুরআন ২৮:১৬ — কিবতিকে অনিচ্ছাকৃত হত্যার পর মুসা (আঃ)-এর দুআ।",
            source = "Quran 28:16",
        ),
        dhikr(
            id = "istighfar_q_adam",
            name = "Rabbana zalamna anfusana wa il-lam taghfir lana",
            arabic = "رَبَّنَا ظَلَمْنَا أَنْفُسَنَا وَإِنْ لَمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ",
            pronunciation = "রব্বানা যালামনা আনফুসানা ওয়া ইল্লাম তাগফির লানা ওয়া তারহামনা লানাকুনান্না মিনাল খাসিরীন",
            translation = "হে আমাদের রব, আমরা নিজেদের উপর জুলুম করেছি; আপনি যদি আমাদের ক্ষমা না করেন ও দয়া না করেন তবে আমরা অবশ্যই ক্ষতিগ্রস্তদের অন্তর্ভুক্ত হব — Our Lord, we have wronged ourselves. If You do not forgive us and have mercy upon us, we will surely be amongst the losers",
            lapTarget = 3,
            note = "কুরআন ৭:২৩ — গাছ থেকে খাওয়ার পর আদম (আঃ) ও হাওয়া (আঃ)-এর দুআ।",
            source = "Quran 7:23",
        ),
        dhikr(
            id = "istighfar_q_waliyy",
            name = "Anta Waliyyuna faghfir lana warhamna",
            arabic = "أَنْتَ وَلِيُّنَا فَاغْفِرْ لَنَا وَارْحَمْنَا وَأَنْتَ خَيْرُ الْغَافِرِينَ",
            pronunciation = "আনতা ওয়ালিয়্যুনা ফাগফির লানা ওয়ারহামনা ওয়া আনতা খাইরুল গাফিরীন",
            translation = "আপনিই আমাদের অভিভাবক, তাই আমাদের ক্ষমা করুন ও দয়া করুন; আপনিই শ্রেষ্ঠ ক্ষমাকারী — You are our Protector, so forgive us and have mercy upon us. You are the best of those who forgive",
            lapTarget = 3,
            note = "কুরআন ৭:১৫৫ — আল্লাহর নাম ‘আল-ওয়ালী’-র অসিলায় মুসা (আঃ)-এর দুআ।",
            source = "Quran 7:155",
        ),
        dhikr(
            id = "istighfar_q_amanna",
            name = "Rabbana innana amanna faghfir lana dhunubana",
            arabic = "رَبَّنَا إِنَّنَا آمَنَّا فَاغْفِرْ لَنَا ذُنُوبَنَا وَقِنَا عَذَابَ النَّارِ",
            pronunciation = "রব্বানা ইন্নানা আমান্না ফাগফির লানা যুনুবানা ওয়া কিনা আযাবান নার",
            translation = "হে আমাদের রব, আমরা ঈমান এনেছি, তাই আমাদের গুনাহ ক্ষমা করুন এবং জাহান্নামের আযাব থেকে রক্ষা করুন — Our Lord, indeed we have believed, so forgive us our sins and protect us from the punishment of the Fire",
            lapTarget = 3,
            note = "কুরআন ৩:১৬ — মুত্তাকিদের দুআ; ঈমানের অসিলায় তাওয়াসসুল।",
            source = "Quran 3:16",
        ),
        dhikr(
            id = "istighfar_q_irham",
            name = "Rabbi-ghfir warham wa Anta khayrur rahimin",
            arabic = "رَبِّ اغْفِرْ وَارْحَمْ وَأَنْتَ خَيْرُ الرَّاحِمِينَ",
            pronunciation = "রব্বিগফির ওয়ারহাম ওয়া আনতা খাইরুর রাহিমীন",
            translation = "হে আমার রব, ক্ষমা করুন ও দয়া করুন; আপনিই শ্রেষ্ঠ দয়ালু — My Lord, forgive and have mercy. You are the Best of those who are merciful",
            lapTarget = 3,
            note = "কুরআন ২৩:১১৮ — সূরা আল-মুমিনূনের শেষ আয়াত।",
            source = "Quran 23:118",
        ),
        dhikr(
            id = "istighfar_q_ilm",
            name = "Rabbi inni a'udhu bika an as'alaka ma laysa li bihi ilm",
            arabic = "رَبِّ إِنِّي أَعُوذُ بِكَ أَنْ أَسْأَلَكَ مَا لَيْسَ لِي بِهِ عِلْمٌ وَإِلَّا تَغْفِرْ لِي وَتَرْحَمْنِي أَكُنْ مِنَ الْخَاسِرِينَ",
            pronunciation = "রব্বি ইন্নি আউযু বিকা আন আসআলাকা মা লাইসা লি বিহি ইলম, ওয়া ইল্লা তাগফির লি ওয়া তারহামনি আকুম মিনাল খাসিরীন",
            translation = "হে আমার রব, যে বিষয়ে আমার জ্ঞান নেই তা আপনার কাছে চাওয়া থেকে আমি আপনার আশ্রয় চাই; আপনি যদি আমাকে ক্ষমা ও দয়া না করেন তবে আমি ক্ষতিগ্রস্তদের অন্তর্ভুক্ত হব — My Lord, I seek Your protection from asking You anything about which I have no knowledge. And unless You forgive me and have mercy upon me, I shall be amongst the losers",
            lapTarget = 3,
            note = "কুরআন ১১:৪৭ — নূহ (আঃ)-এর দুআ।",
            source = "Quran 11:47",
        ),
        dhikr(
            id = "istighfar_q_ikhwan",
            name = "Rabbana-ghfir lana wa li-ikhwanina alladhina sabaquna bil-iman",
            arabic = "رَبَّنَا اغْفِرْ لَنَا وَلِإِخْوَانِنَا الَّذِينَ سَبَقُونَا بِالْإِيمَانِ وَلَا تَجْعَلْ فِي قُلُوبِنَا غِلًّا لِلَّذِينَ آمَنُوا رَبَّنَا إِنَّكَ رَءُوفٌ رَحِيمٌ",
            pronunciation = "রব্বানাগফির লানা ওয়া লিইখওয়ানিনাল্লাযিনা সাবাকুনা বিল ঈমান, ওয়া লা তাজআল ফি কুলুবিনা গিল্লাল লিল্লাযিনা আমানু রব্বানা ইন্নাকা রউফুর রাহীম",
            translation = "হে আমাদের রব, আমাদের ও ঈমানে আমাদের অগ্রগামী ভাইদের ক্ষমা করুন এবং মুমিনদের প্রতি আমাদের অন্তরে বিদ্বেষ রাখবেন না; হে আমাদের রব, নিশ্চয়ই আপনি অতি স্নেহশীল, পরম দয়ালু — Our Lord, forgive us and our brothers who preceded us in faith. Do not put in our hearts any hatred toward those who have believed. Our Lord, indeed You are the Most Compassionate, the Ever-Merciful",
            lapTarget = 3,
            note = "কুরআন ৫৯:১০ — পরবর্তী প্রজন্মের মুমিনদের দুআ; জীবিত ও মৃত ভাই-বোনদের জন্য।",
            source = "Quran 59:10",
        ),
        dhikr(
            id = "istighfar_q_nur",
            name = "Rabbana atmim lana nurana waghfir lana",
            arabic = "رَبَّنَا أَتْمِمْ لَنَا نُورَنَا وَاغْفِرْ لَنَا إِنَّكَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
            pronunciation = "রব্বানা আতমিম লানা নূরানা ওয়াগফির লানা ইন্নাকা আলা কুল্লি শাইইন কাদীর",
            translation = "হে আমাদের রব, আমাদের নূর পূর্ণ করুন ও আমাদের ক্ষমা করুন; নিশ্চয়ই আপনি সর্বশক্তিমান — Our Lord, perfect for us our light and forgive us. Indeed, You are All-Powerful over everything",
            lapTarget = 3,
            note = "কুরআন ৬৬:৮ — কিয়ামতের দিন মুমিনদের দুআ যখন মুনাফিকদের নূর নিভে যাবে।",
            source = "Quran 66:8",
        ),
        dhikr(
            id = "istighfar_sayyid",
            name = "Sayyid al-Istighfar",
            arabic = "اللّٰهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي، فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
            pronunciation = "আল্লাহুম্মা আনতা রব্বি লা ইলাহা ইল্লা আনতা, খালাকতানি ওয়া আনা আবদুকা, ওয়া আনা আলা আহদিকা ওয়া ওয়াদিকা মাসতাতাতু, আউযু বিকা মিন শাররি মা সানাতু, আবূউ লাকা বিনিমাতিকা আলাইয়া ওয়া আবূউ বিযামবি, ফাগফির লি ফাইন্নাহু লা ইয়াগফিরুয যুনূবা ইল্লা আনতা",
            translation = "হে আল্লাহ, আপনিই আমার রব, আপনি ছাড়া কোনো উপাস্য নেই; আপনি আমাকে সৃষ্টি করেছেন, আমি আপনার বান্দা; সাধ্যমতো আপনার অঙ্গীকার ও প্রতিশ্রুতির উপর আছি; আমি আমার কৃতকর্মের অনিষ্ট থেকে আপনার আশ্রয় চাই; আপনার নিয়ামত স্বীকার করছি এবং আমার গুনাহও স্বীকার করছি; আমাকে ক্ষমা করুন, কারণ আপনি ছাড়া গুনাহ কেউ ক্ষমা করতে পারে না — O Allah, You are my Lord. There is no god except You. You created me and I am Your slave, and I am upon Your covenant and pledge as much as I am able. I seek Your protection from the evil that I have done. I acknowledge Your favour upon me and I admit my sin. Forgive me, for none forgives sins but You",
            lapTarget = 3,
            note = "সর্বোত্তম ইস্তিগফার। দৃঢ় বিশ্বাসের সাথে দিনে পড়ে সন্ধ্যার আগে বা রাতে পড়ে সকালের আগে মারা গেলে জান্নাতি — সহীহ বুখারি ৬৩০৬।",
            source = "Sahih al-Bukhari 6306",
        ),
        dhikr(
            id = "istighfar_malik",
            name = "Allahumma Antal-Maliku la ilaha illa Ant",
            arabic = "اللّٰهُمَّ أَنْتَ الْمَلِكُ لَا إِلَٰهَ إِلَّا أَنْتَ، أَنْتَ رَبِّي وَأَنَا عَبْدُكَ، ظَلَمْتُ نَفْسِي وَاعْتَرَفْتُ بِذَنْبِي، فَاغْفِرْ لِي ذُنُوبِي جَمِيعًا، إِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ، وَاهْدِنِي لِأَحْسَنِ الْأَخْلَاقِ لَا يَهْدِي لِأَحْسَنِهَا إِلَّا أَنْتَ، وَاصْرِفْ عَنِّي سَيِّئَهَا لَا يَصْرِفُ عَنِّي سَيِّئَهَا إِلَّا أَنْتَ",
            pronunciation = "আল্লাহুম্মা আনতাল মালিকু লা ইলাহা ইল্লা আনতা, আনতা রব্বি ওয়া আনা আবদুকা, যালামতু নাফসি ওয়াতারাফতু বিযামবি, ফাগফির লি যুনূবি জামীআন, ইন্নাহু লা ইয়াগফিরুয যুনূবা ইল্লা আনতা, ওয়াহদিনি লিআহসানিল আখলাকি লা ইয়াহদি লিআহসানিহা ইল্লা আনতা, ওয়াসরিফ আন্নি সাইয়িআহা লা ইয়াসরিফু আন্নি সাইয়িআহা ইল্লা আনতা",
            translation = "হে আল্লাহ, আপনিই বাদশাহ, আপনি ছাড়া কোনো উপাস্য নেই; আপনি আমার রব, আমি আপনার বান্দা; আমি নিজের উপর জুলুম করেছি ও গুনাহ স্বীকার করছি; আমার সব গুনাহ ক্ষমা করুন, আপনি ছাড়া গুনাহ কেউ ক্ষমা করে না; আমাকে উত্তম চরিত্রের পথ দেখান, আপনি ছাড়া কেউ তার পথ দেখাতে পারে না; মন্দ চরিত্র আমার থেকে দূর করুন, আপনি ছাড়া কেউ তা দূর করতে পারে না — O Allah, You are the King, there is no god worthy of worship except You. You are my Lord and I am Your slave. I have wronged myself and I confess my sin. Forgive all my sins; none forgives sins but You. Guide me to the best of character, for none guides to it but You; and turn its evil away from me, for none turns it away but You",
            lapTarget = 3,
            note = "নবি (সাঃ) সালাত শুরুর দুআয় পড়তেন — সহীহ মুসলিম ৭৭১। শেষাংশ (‘লাব্বাইকা ওয়া সাদাইক…’) সংক্ষেপে দেওয়া হলো।",
            source = "Sahih Muslim 771",
        ),
        dhikr(
            id = "istighfar_khatiati",
            name = "Allahumma-ghfir li khati'ati wa jahli wa israfi fi amri",
            arabic = "اللّٰهُمَّ اغْفِرْ لِي خَطِيئَتِي وَجَهْلِي وَإِسْرَافِي فِي أَمْرِي، وَمَا أَنْتَ أَعْلَمُ بِهِ مِنِّي، اللّٰهُمَّ اغْفِرْ لِي جِدِّي وَهَزْلِي وَخَطَئِي وَعَمْدِي وَكُلُّ ذَٰلِكَ عِنْدِي",
            pronunciation = "আল্লাহুম্মাগফির লি খাতীআতি ওয়া জাহলি ওয়া ইসরাফি ফি আমরি, ওয়া মা আনতা আলামু বিহি মিন্নি, আল্লাহুম্মাগফির লি জিদ্দি ওয়া হাযলি ওয়া খাতাই ওয়া আমদি ওয়া কুল্লু যালিকা ইনদি",
            translation = "হে আল্লাহ, আমার ভুল, অজ্ঞতা, কাজে সীমালঙ্ঘন এবং যা আপনি আমার চেয়ে বেশি জানেন তা ক্ষমা করুন; হে আল্লাহ, আমার সিরিয়াসভাবে ও ঠাট্টাচ্ছলে, অনিচ্ছাকৃত ও ইচ্ছাকৃত—সব গুনাহ ক্ষমা করুন, এসবই আমার মধ্যে আছে — O Allah, forgive my mistakes, my ignorance, my transgression in my affairs, and what You know better than me. O Allah, forgive me for what I did in earnest and in jest, unintentionally and intentionally; all of that is in me",
            lapTarget = 3,
            note = "নবি (সাঃ) এই দুআ করতেন — সহীহ মুসলিম ২৭১৯।",
            source = "Sahih Muslim 2719",
        ),
        dhikr(
            id = "istighfar_rabba_muhammad",
            name = "Allahumma Rabba Muhammadin ighfir li dhambi",
            arabic = "اللّٰهُمَّ رَبَّ مُحَمَّدٍ اغْفِرْ لِي ذَنْبِي، وَأَذْهِبْ غَيْظَ قَلْبِي، وَأَعِذْنِي مِنْ مُضِلَّاتِ الْفِتَنِ",
            pronunciation = "আল্লাহুম্মা রব্বা মুহাম্মাদিন ইগফির লি যামবি, ওয়া আযহিব গাইযা কালবি, ওয়া আইযনি মিন মুদিল্লাতিল ফিতান",
            translation = "হে আল্লাহ, মুহাম্মাদের রব, আমার গুনাহ ক্ষমা করুন, আমার অন্তরের ক্রোধ দূর করুন এবং বিভ্রান্তিকর ফিতনা থেকে আমাকে রক্ষা করুন — O Allah, Lord of Muhammad, forgive my sin, remove the anger of my heart and protect me from misleading trials",
            lapTarget = 3,
            note = "আয়েশা (রাঃ) রাগান্বিত হলে নবি (সাঃ) তাঁকে এটি পড়তে বলতেন — ইবনুস সুন্নি ৪৫৬।",
            source = "Ibn as-Sunni 456",
        ),
        dhikr(
            id = "istighfar_diqqahu",
            name = "Allahumma-ghfir li dhambi kullah, diqqahu wa jillah",
            arabic = "اللّٰهُمَّ اغْفِرْ لِي ذَنْبِي كُلَّهُ، دِقَّهُ وَجِلَّهُ، وَأَوَّلَهُ وَآخِرَهُ، وَعَلَانِيَتَهُ وَسِرَّهُ",
            pronunciation = "আল্লাহুম্মাগফির লি যামবি কুল্লাহু, দিক্কাহু ওয়া জিল্লাহু, ওয়া আউওয়ালাহু ওয়া আখিরাহু, ওয়া আলানিয়াতাহু ওয়া সিররাহু",
            translation = "হে আল্লাহ, আমার সব গুনাহ ক্ষমা করুন—ছোট ও বড়, প্রথম ও শেষ, প্রকাশ্য ও গোপন — O Allah, forgive me all my sins: the minor and the major, the first and the last, the public and the private",
            lapTarget = 3,
            note = "নবি (সাঃ) সিজদায় এই দুআ পড়তেন — সহীহ মুসলিম ৪৮৩।",
            source = "Sahih Muslim 483",
        ),
        dhikr(
            id = "istighfar_kathira",
            name = "Allahumma inni zalamtu nafsi zulman kathira",
            arabic = "اللّٰهُمَّ إِنِّي ظَلَمْتُ نَفْسِي ظُلْمًا كَثِيرًا، وَلَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ، فَاغْفِرْ لِي مَغْفِرَةً مِنْ عِنْدِكَ، وَارْحَمْنِي، إِنَّكَ أَنْتَ الْغَفُورُ الرَّحِيمُ",
            pronunciation = "আল্লাহুম্মা ইন্নি যালামতু নাফসি যুলমান কাছীরা, ওয়া লা ইয়াগফিরুয যুনূবা ইল্লা আনতা, ফাগফির লি মাগফিরাতান মিন ইনদিকা, ওয়ারহামনি, ইন্নাকা আনতাল গাফুরুর রাহীম",
            translation = "হে আল্লাহ, আমি নিজের উপর অনেক বেশি জুলুম করেছি, আপনি ছাড়া গুনাহ কেউ ক্ষমা করে না; আপনার পক্ষ থেকে আমাকে ক্ষমা দান করুন ও দয়া করুন, নিশ্চয়ই আপনি ক্ষমাশীল, পরম দয়ালু — O Allah, I have wronged myself greatly and none forgives sins but You; so grant me forgiveness from You and have mercy on me. You are the Most Forgiving, the Most Merciful",
            lapTarget = 3,
            note = "নবি (সাঃ) আবু বকর (রাঃ)-কে সালাতে পড়ার জন্য এই দুআ শিখিয়েছেন — সহীহ বুখারি ৮৩৪।",
            source = "Sahih al-Bukhari 834",
        ),
        dhikr(
            id = "istighfar_afini",
            name = "Allahumma-ghfir li warhamni wa afini wahdini warzuqni",
            arabic = "اللّٰهُمَّ اغْفِرْ لِي، وَارْحَمْنِي، وَعَافِنِي، وَاهْدِنِي وَارْزُقْنِي",
            pronunciation = "আল্লাহুম্মাগফির লি, ওয়ারহামনি, ওয়া আফিনি, ওয়াহদিনি ওয়ারযুকনি",
            translation = "হে আল্লাহ, আমাকে ক্ষমা করুন, দয়া করুন, সুস্থতা দিন, হেদায়েত দিন ও রিযিক দিন — O Allah, forgive me, have mercy on me, grant me wellbeing, guide me and grant me sustenance",
            lapTarget = 3,
            note = "নবি (সাঃ) দুই সিজদার মাঝে এই দুআ পড়তেন — আবু দাউদ ৮৫০।",
            source = "Sunan Abi Dawud 850",
        ),
        dhikr(
            id = "istighfar_baaid",
            name = "Allahumma baa'id bayni wa bayna khatayaya",
            arabic = "اللّٰهُمَّ بَاعِدْ بَيْنِي وَبَيْنَ خَطَايَايَ كَمَا بَاعَدْتَ بَيْنَ الْمَشْرِقِ وَالْمَغْرِبِ، اللّٰهُمَّ نَقِّنِي مِنَ الْخَطَايَا كَمَا يُنَقَّى الثَّوْبُ الْأَبْيَضُ مِنَ الدَّنَسِ، اللّٰهُمَّ اغْسِلْ خَطَايَايَ بِالْمَاءِ وَالثَّلْجِ وَالْبَرَدِ",
            pronunciation = "আল্লাহুম্মা বাইদ বাইনি ওয়া বাইনা খাতায়ায়া কামা বাআদতা বাইনাল মাশরিকি ওয়াল মাগরিব, আল্লাহুম্মা নাক্কিনি মিনাল খাতায়া কামা ইউনাক্কাস সাউবুল আবয়াদু মিনাদ দানাস, আল্লাহুম্মাগসিল খাতায়ায়া বিল মাই ওয়াস সালজি ওয়াল বারাদ",
            translation = "হে আল্লাহ, আমার ও আমার গুনাহের মধ্যে দূরত্ব সৃষ্টি করুন যেমন পূর্ব ও পশ্চিমের মধ্যে দূরত্ব রেখেছেন; হে আল্লাহ, আমাকে গুনাহ থেকে পবিত্র করুন যেমন সাদা কাপড় ময়লা থেকে পরিষ্কার করা হয়; হে আল্লাহ, আমার গুনাহ পানি, বরফ ও শিলা দিয়ে ধুয়ে দিন — O Allah, distance me from my sins as You have distanced the East from the West. O Allah, purify me from my sins as a white cloth is purified from dirt. O Allah, wash away my sins with water, snow and hail",
            lapTarget = 3,
            note = "নবি (সাঃ) তাকবিরে তাহরিমা ও কিরাআতের মাঝে এই দুআ পড়তেন — সহীহ বুখারি ৭৪৪, সহীহ মুসলিম ৫৯৮।",
            source = "Sahih al-Bukhari 744; Sahih Muslim 598",
        ),
        dhikr(
            id = "istighfar_muminin",
            name = "Allahumma-ghfir lil-mu'minina wal-mu'minat",
            arabic = "اللّٰهُمَّ اغْفِرْ لِلْمُؤْمِنِينَ وَالْمُؤْمِنَاتِ",
            pronunciation = "আল্লাহুম্মাগফির লিল মুমিনীনা ওয়াল মুমিনাত",
            translation = "হে আল্লাহ, মুমিন পুরুষ ও মুমিন নারীদের ক্ষমা করুন — O Allah, forgive the believing men and the believing women",
            lapTarget = 3,
            note = "যে প্রতিদিন এটি বলে, প্রত্যেক মুমিন পুরুষ ও নারীর বিনিময়ে তার জন্য একটি নেকি লেখা হয় — তাবারানি, মুজামুল কাবির ও মুসনাদুশ শামিয়্যিন ২১৫৫।",
            source = "al-Mu'jam al-Kabir (Tabarani); Musnad ash-Shamiyyin 2155",
        ),

        // --- Morning adhkar (lifewithallah.com/dhikr-dua/main-adhkar/morning)
        // The dhikr from that page not already covered by an existing built-in.
        // Ayat al-Kursi (`kursi`), Subhanallahi wa bihamdihi (`bihamdihi`),
        // La ilaha illallahu wahdahu... (`tahlil_wahdahu`), Hasbiyallahu...
        // (`hasbiyallah_arsh`), the hamm/hazan dua (`hamm_hazan`), Ya Hayyu ya
        // Qayyum... (`ya_hayyu_astaghith`), Sayyid al-Istighfar
        // (`istighfar_sayyid`), Astaghfirullaha wa atubu ilayh
        // (`istighfar_atubu`), the durood (`durood_ali`) and adada khalqih
        // (`adada_khalqih`) are reused as-is. The "Morning Dhikr" preset walks
        // the whole page in order.
        dhikr(
            id = "morn_3quls",
            name = "Al-Ikhlas, Al-Falaq, An-Nas (3 Quls)",
            arabic = "قُلْ هُوَ اللّٰهُ أَحَدٌ… ۞ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ… ۞ قُلْ أَعُوذُ بِرَبِّ النَّاسِ…",
            pronunciation = "কুল হুওয়াল্লাহু আহাদ… কুল আউযু বিরব্বিল ফালাক… কুল আউযু বিরব্বিন নাস…",
            translation = "সূরা আল-ইখলাস, আল-ফালাক ও আন-নাস — Say: He is Allah, the One… ; Say: I seek refuge in the Lord of the daybreak… ; Say: I seek refuge in the Lord of mankind…",
            lapTarget = 3,
            note = "সকাল-সন্ধ্যায় তিনবার পড়লে সবকিছু থেকে যথেষ্ট হয় — তিরমিযি ৩৫৭৫। পূর্ণ সূরা তিনটি তিলাওয়াত করুন।",
            source = "Jami at-Tirmidhi 3575",
        ),
        dhikr(
            id = "morn_afiyah",
            name = "Allahumma inni as'alukal afiyata fid dunya wal akhirah",
            arabic = "اللّٰهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ، اللّٰهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي دِينِي وَدُنْيَايَ وَأَهْلِي وَمَالِي، اللّٰهُمَّ اسْتُرْ عَوْرَاتِي وَآمِنْ رَوْعَاتِي، اللّٰهُمَّ احْفَظْنِي مِنْ بَيْنِ يَدَيَّ وَمِنْ خَلْفِي وَعَنْ يَمِينِي وَعَنْ شِمَالِي وَمِنْ فَوْقِي، وَأَعُوذُ بِعَظَمَتِكَ أَنْ أُغْتَالَ مِنْ تَحْتِي",
            pronunciation = "আল্লাহুম্মা ইন্নি আসআলুকাল আফিয়াতা ফিদ দুনইয়া ওয়াল আখিরাহ, আল্লাহুম্মা ইন্নি আসআলুকাল আফওয়া ওয়াল আফিয়াতা ফি দিনি ওয়া দুনইয়ায়া ওয়া আহলি ওয়া মালি, আল্লাহুম্মাসতুর আওরাতি ওয়া আমিন রাওআতি, আল্লাহুম্মাহফাযনি মিন বাইনি ইয়াদাইয়া ওয়া মিন খালফি ওয়া আন ইয়ামিনি ওয়া আন শিমালি ওয়া মিন ফাওকি, ওয়া আউযু বিআযামাতিকা আন উগতালা মিন তাহতি",
            translation = "হে আল্লাহ, দুনিয়া ও আখিরাতে সুস্থতা চাই; হে আল্লাহ, আমার দ্বীন, দুনিয়া, পরিবার ও সম্পদে ক্ষমা ও সুস্থতা চাই; হে আল্লাহ, আমার দোষ ঢেকে দিন ও ভয় দূর করুন; হে আল্লাহ, আমার সামনে-পিছনে, ডানে-বামে ও উপর থেকে রক্ষা করুন, এবং নিচ থেকে অতর্কিতে ধ্বংস হওয়া থেকে আপনার মহত্ত্বের অসিলায় আশ্রয় চাই — O Allah, I ask You for wellbeing in this world and the next. O Allah, I ask You for pardon and wellbeing in my religion, my worldly affairs, my family and my wealth. O Allah, conceal my faults and calm my fears. O Allah, guard me from before me and behind me, from my right and my left and from above me, and I seek refuge in Your Greatness from being destroyed from beneath me",
            lapTarget = 1,
            note = "নবি (সাঃ) সকাল-সন্ধ্যায় কখনো এ দুআ ছাড়তেন না — আবু দাউদ ৫০৭৪, ইবনে মাজাহ ৩৮৭১।",
            source = "Sunan Abi Dawud 5074; Sunan Ibn Majah 3871",
        ),
        dhikr(
            id = "morn_fatir",
            name = "Allahumma Fatiras samawati wal ard, alimal ghaybi wash shahadah",
            arabic = "اللّٰهُمَّ فَاطِرَ السَّمَاوَاتِ وَالْأَرْضِ، عَالِمَ الْغَيْبِ وَالشَّهَادَةِ، رَبَّ كُلِّ شَيْءٍ وَمَلِيكَهُ، أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا أَنْتَ، أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي، وَمِنْ شَرِّ الشَّيْطَانِ وَشِرْكِهِ، وَأَنْ أَقْتَرِفَ عَلَىٰ نَفْسِي سُوءًا أَوْ أَجُرَّهُ إِلَىٰ مُسْلِمٍ",
            pronunciation = "আল্লাহুম্মা ফাতিরাস সামাওয়াতি ওয়াল আরদ, আলিমাল গাইবি ওয়াশ শাহাদাহ, রব্বা কুল্লি শাইইন ওয়া মালিকাহু, আশহাদু আন লা ইলাহা ইল্লা আনতা, আউযু বিকা মিন শাররি নাফসি, ওয়া মিন শাররিশ শাইতানি ওয়া শিরকিহি, ওয়া আন আকতারিফা আলা নাফসি সূআন আও আজুররাহু ইলা মুসলিম",
            translation = "হে আল্লাহ, আসমান-জমিনের স্রষ্টা, দৃশ্য-অদৃশ্যের জ্ঞানী, সবকিছুর রব ও মালিক; আমি সাক্ষ্য দিই আপনি ছাড়া কোনো উপাস্য নেই; আমার নফসের অনিষ্ট থেকে, শয়তান ও তার শিরক থেকে, এবং নিজের বা কোনো মুসলিমের উপর অনিষ্ট ডেকে আনা থেকে আপনার আশ্রয় চাই — O Allah, Creator of the heavens and the earth, Knower of the unseen and the seen, Lord and Sovereign of all things; I bear witness there is no god but You. I seek refuge in You from the evil of my self, from the evil of Shaytan and his shirk, and from bringing evil upon myself or upon a Muslim",
            lapTarget = 1,
            note = "নবি (সাঃ) আবু বকর (রাঃ)-কে সকাল-সন্ধ্যা ও শোয়ার সময় পড়তে বলেছেন — তিরমিযি ৩৩৯২।",
            source = "Jami at-Tirmidhi 3392",
        ),
        dhikr(
            id = "morn_nimah",
            name = "Allahumma ma asbaha bi min ni'matin",
            arabic = "اللّٰهُمَّ مَا أَصْبَحَ بِي مِنْ نِعْمَةٍ أَوْ بِأَحَدٍ مِنْ خَلْقِكَ فَمِنْكَ وَحْدَكَ لَا شَرِيكَ لَكَ، فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ",
            pronunciation = "আল্লাহুম্মা মা আসবাহা বি মিন নিমাতিন আও বিআহাদিন মিন খালকিকা ফামিনকা ওয়াহদাকা লা শারিকা লাকা, ফালাকাল হামদু ওয়া লাকাশ শুকর",
            translation = "হে আল্লাহ, সকালে আমার বা আপনার কোনো সৃষ্টির কাছে যে নিয়ামত পৌঁছেছে তা কেবল আপনার কাছ থেকে, আপনার কোনো শরিক নেই; সকল প্রশংসা ও কৃতজ্ঞতা আপনারই — O Allah, whatever blessing has come to me or to any of Your creation this morning is from You alone, no partner have You; to You is all praise and all thanks",
            lapTarget = 1,
            note = "যে সকালে এটি বলে সে সেদিনের শোকর আদায় করল, সন্ধ্যায় বললে সে রাতের শোকর আদায় করল — আবু দাউদ ৫০৭৩।",
            source = "Sunan Abi Dawud 5073",
        ),
        dhikr(
            id = "morn_fitrah",
            name = "Asbahna ala fitratil islam",
            arabic = "أَصْبَحْنَا عَلَىٰ فِطْرَةِ الْإِسْلَامِ، وَعَلَىٰ كَلِمَةِ الْإِخْلَاصِ، وَعَلَىٰ دِينِ نَبِيِّنَا مُحَمَّدٍ، وَعَلَىٰ مِلَّةِ أَبِينَا إِبْرَاهِيمَ حَنِيفًا مُسْلِمًا وَمَا كَانَ مِنَ الْمُشْرِكِينَ",
            pronunciation = "আসবাহনা আলা ফিতরাতিল ইসলাম, ওয়া আলা কালিমাতিল ইখলাস, ওয়া আলা দিনি নাবিয়্যিনা মুহাম্মাদ, ওয়া আলা মিল্লাতি আবিনা ইবরাহিমা হানিফাম মুসলিমাও ওয়া মা কানা মিনাল মুশরিকিন",
            translation = "আমরা সকালে উপনীত হলাম ইসলামের ফিতরাত, ইখলাসের কালিমা, আমাদের নবি মুহাম্মাদের দ্বীন ও আমাদের পিতা ইবরাহিমের মিল্লাতের উপর—যিনি একনিষ্ঠ মুসলিম ছিলেন, মুশরিকদের অন্তর্ভুক্ত ছিলেন না — We have entered the morning upon the natural way of Islam, the word of sincerity, the religion of our Prophet Muhammad, and the way of our father Ibrahim, upright and Muslim, and he was not of the polytheists",
            lapTarget = 1,
            note = "নবি (সাঃ) সকালে এটি পড়তেন — আহমাদ ১৫৩৬০।",
            source = "Musnad Ahmad 15360",
        ),
        dhikr(
            id = "morn_uthni",
            name = "Asbahtu uthni alayka hamda",
            arabic = "أَصْبَحْتُ أُثْنِي عَلَيْكَ حَمْدًا، وَأَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللّٰهُ",
            pronunciation = "আসবাহতু উছনি আলাইকা হামদা, ওয়া আশহাদু আন লা ইলাহা ইল্লাল্লাহ",
            translation = "আমি সকালে উপনীত হলাম আপনার প্রশংসা করতে করতে, এবং সাক্ষ্য দিই আল্লাহ ছাড়া কোনো উপাস্য নেই — I have entered the morning praising You, and I bear witness that there is no god but Allah",
            lapTarget = 3,
            note = "নাসাঈ, আস-সুনানুল কুবরা ১০৩৩১।",
            source = "an-Nasa'i, as-Sunan al-Kubra 10331",
        ),
        dhikr(
            id = "morn_mulk_shar",
            name = "Asbahna wa asbahal mulku lillah, Rabbi as'aluka khayra ma fi hadhal yawm",
            arabic = "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلّٰهِ وَالْحَمْدُ لِلّٰهِ، لَا إِلَٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَٰذَا الْيَوْمِ وَخَيْرَ مَا بَعْدَهُ، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَٰذَا الْيَوْمِ وَشَرِّ مَا بَعْدَهُ، رَبِّ أَعُوذُ بِكَ مِنَ الْكَسَلِ وَسُوءِ الْكِبَرِ، رَبِّ أَعُوذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ",
            pronunciation = "আসবাহনা ওয়া আসবাহাল মুলকু লিল্লাহি ওয়াল হামদু লিল্লাহ, লা ইলাহা ইল্লাল্লাহু ওয়াহদাহু লা শারিকা লাহু, লাহুল মুলকু ওয়া লাহুল হামদু ওয়া হুয়া আলা কুল্লি শাইইন কাদীর, রব্বি আসআলুকা খাইরা মা ফি হাযাল ইয়াওমি ওয়া খাইরা মা বাদাহু, ওয়া আউযু বিকা মিন শাররি মা ফি হাযাল ইয়াওমি ওয়া শাররি মা বাদাহু, রব্বি আউযু বিকা মিনাল কাসালি ওয়া সূইল কিবার, রব্বি আউযু বিকা মিন আযাবিন ফিন নারি ওয়া আযাবিন ফিল কাবর",
            translation = "আমরা সকালে উপনীত হলাম আর রাজত্ব আল্লাহরই, সকল প্রশংসা আল্লাহর; আল্লাহ ছাড়া কোনো উপাস্য নেই, তিনি একক, শরিকহীন; রাজত্ব ও প্রশংসা তাঁরই, তিনি সর্বশক্তিমান; হে রব, আজকের ও পরবর্তী কল্যাণ চাই, আজকের ও পরবর্তী অনিষ্ট থেকে আশ্রয় চাই; হে রব, অলসতা ও বার্ধক্যের মন্দ থেকে আশ্রয় চাই; হে রব, জাহান্নাম ও কবরের আযাব থেকে আশ্রয় চাই — We have entered the morning and the dominion belongs to Allah… My Lord, I ask You for the good of this day and what follows it, and I seek refuge in You from the evil of this day and what follows it. My Lord, I seek refuge in You from laziness and the misery of old age. My Lord, I seek refuge in You from the punishment of the Fire and the punishment of the grave",
            lapTarget = 1,
            note = "নবি (সাঃ) সকালে এটি পড়তেন — সহীহ মুসলিম ২৭২৩।",
            source = "Sahih Muslim 2723",
        ),
        dhikr(
            id = "morn_mulk_alamin",
            name = "Asbahna wa asbahal mulku lillahi Rabbil alamin",
            arabic = "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلّٰهِ رَبِّ الْعَالَمِينَ، اللّٰهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ هَٰذَا الْيَوْمِ، فَتْحَهُ وَنَصْرَهُ وَنُورَهُ وَبَرَكَتَهُ وَهُدَاهُ، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِيهِ وَشَرِّ مَا بَعْدَهُ",
            pronunciation = "আসবাহনা ওয়া আসবাহাল মুলকু লিল্লাহি রব্বিল আলামিন, আল্লাহুম্মা ইন্নি আসআলুকা খাইরা হাযাল ইয়াওম, ফাতহাহু ওয়া নাসরাহু ওয়া নূরাহু ওয়া বারাকাতাহু ওয়া হুদাহু, ওয়া আউযু বিকা মিন শাররি মা ফিহি ওয়া শাররি মা বাদাহু",
            translation = "আমরা সকালে উপনীত হলাম আর রাজত্ব বিশ্বজগতের রব আল্লাহরই; হে আল্লাহ, আমি এই দিনের কল্যাণ চাই—এর বিজয়, সাহায্য, নূর, বরকত ও হেদায়েত; আর এর ও পরবর্তীর অনিষ্ট থেকে আশ্রয় চাই — We have entered the morning and the dominion belongs to Allah, Lord of the worlds. O Allah, I ask You for the good of this day: its victory, its help, its light, its blessing and its guidance; and I seek refuge in You from the evil in it and the evil after it",
            lapTarget = 1,
            note = "আবু দাউদ ৫০৮৪।",
            source = "Sunan Abi Dawud 5084",
        ),
        dhikr(
            id = "morn_ushhiduka",
            name = "Allahumma inni asbahtu ush-hiduka wa ush-hidu hamalata arshik",
            arabic = "اللّٰهُمَّ إِنِّي أَصْبَحْتُ أُشْهِدُكَ، وَأُشْهِدُ حَمَلَةَ عَرْشِكَ وَمَلَائِكَتَكَ وَجَمِيعَ خَلْقِكَ، أَنَّكَ أَنْتَ اللّٰهُ لَا إِلَٰهَ إِلَّا أَنْتَ وَحْدَكَ لَا شَرِيكَ لَكَ، وَأَنَّ مُحَمَّدًا عَبْدُكَ وَرَسُولُكَ",
            pronunciation = "আল্লাহুম্মা ইন্নি আসবাহতু উশহিদুকা, ওয়া উশহিদু হামালাতা আরশিকা ওয়া মালাইকাতাকা ওয়া জামিআ খালকিকা, আন্নাকা আনতাল্লাহু লা ইলাহা ইল্লা আনতা ওয়াহদাকা লা শারিকা লাকা, ওয়া আন্না মুহাম্মাদান আবদুকা ওয়া রাসূলুকা",
            translation = "হে আল্লাহ, আমি সকালে উপনীত হয়ে আপনাকে, আপনার আরশ বহনকারীদের, ফেরেশতাদের ও সকল সৃষ্টিকে সাক্ষী রাখছি যে আপনিই আল্লাহ, আপনি ছাড়া কোনো উপাস্য নেই, একক, শরিকহীন, এবং মুহাম্মাদ (সাঃ) আপনার বান্দা ও রাসূল — O Allah, I have entered the morning calling You to witness, and calling the bearers of Your Throne, Your angels and all Your creation to witness, that You are Allah, none is worthy of worship but You alone, no partner have You, and that Muhammad is Your slave and Messenger",
            lapTarget = 4,
            note = "যে সকাল বা সন্ধ্যায় এটি চারবার বলে, আল্লাহ তাকে জাহান্নাম থেকে মুক্ত করে দেন — আবু দাউদ ৫০৬৯।",
            source = "Sunan Abi Dawud 5069",
        ),
        dhikr(
            id = "morn_bika_asbahna",
            name = "Allahumma bika asbahna wa bika amsayna",
            arabic = "اللّٰهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ",
            pronunciation = "আল্লাহুম্মা বিকা আসবাহনা ওয়া বিকা আমসাইনা ওয়া বিকা নাহইয়া ওয়া বিকা নামুতু ওয়া ইলাইকান নুশূর",
            translation = "হে আল্লাহ, আপনার অনুগ্রহে আমরা সকালে উপনীত হলাম, আপনার অনুগ্রহে সন্ধ্যায়, আপনার অনুগ্রহে বাঁচি ও মরি, এবং আপনার কাছেই পুনরুত্থান — O Allah, by You we enter the morning and by You we enter the evening, by You we live and by You we die, and to You is the resurrection",
            lapTarget = 1,
            note = "নবি (সাঃ) সকালে এটি পড়তেন — তিরমিযি ৩৩৯১, আবু দাউদ ৫০৬৮।",
            source = "Jami at-Tirmidhi 3391; Sunan Abi Dawud 5068",
        ),
        dhikr(
            id = "morn_afini_badani",
            name = "Allahumma afini fi badani",
            arabic = "اللّٰهُمَّ عَافِنِي فِي بَدَنِي، اللّٰهُمَّ عَافِنِي فِي سَمْعِي، اللّٰهُمَّ عَافِنِي فِي بَصَرِي، لَا إِلَٰهَ إِلَّا أَنْتَ، اللّٰهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ، وَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، لَا إِلَٰهَ إِلَّا أَنْتَ",
            pronunciation = "আল্লাহুম্মা আফিনি ফি বাদানি, আল্লাহুম্মা আফিনি ফি সামই, আল্লাহুম্মা আফিনি ফি বাসারি, লা ইলাহা ইল্লা আনতা, আল্লাহুম্মা ইন্নি আউযু বিকা মিনাল কুফরি ওয়াল ফাকর, ওয়া আউযু বিকা মিন আযাবিল কাবর, লা ইলাহা ইল্লা আনতা",
            translation = "হে আল্লাহ, আমার শরীরে সুস্থতা দিন, আমার শ্রবণে সুস্থতা দিন, আমার দৃষ্টিতে সুস্থতা দিন; আপনি ছাড়া কোনো উপাস্য নেই; হে আল্লাহ, কুফর ও দারিদ্র্য থেকে আপনার আশ্রয় চাই, কবরের আযাব থেকে আশ্রয় চাই; আপনি ছাড়া কোনো উপাস্য নেই — O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight. There is no god but You. O Allah, I seek refuge in You from disbelief and poverty, and I seek refuge in You from the punishment of the grave. There is no god but You",
            lapTarget = 3,
            note = "নবি (সাঃ) সকাল-সন্ধ্যায় এই দুআ ছাড়তেন না — আবু দাউদ ৫০৯০, আহমাদ ২০৪৩০।",
            source = "Sunan Abi Dawud 5090; Musnad Ahmad 20430",
        ),
        dhikr(
            id = "morn_raditu",
            name = "Raditu billahi Rabba wa bil-islami dina",
            arabic = "رَضِيتُ بِاللّٰهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ صَلَّى اللّٰهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا",
            pronunciation = "রাদিতু বিল্লাহি রব্বা, ওয়া বিল ইসলামি দিনা, ওয়া বিমুহাম্মাদিন সাল্লাল্লাহু আলাইহি ওয়া সাল্লামা নাবিয়্যা",
            translation = "আমি আল্লাহকে রব হিসেবে, ইসলামকে দ্বীন হিসেবে ও মুহাম্মাদ (সাঃ)-কে নবি হিসেবে পেয়ে সন্তুষ্ট — I am pleased with Allah as Lord, with Islam as religion and with Muhammad (peace be upon him) as Prophet",
            lapTarget = 3,
            note = "যে সকাল-সন্ধ্যায় তিনবার এটি বলে, কিয়ামতের দিন আল্লাহ তাকে সন্তুষ্ট করা তাঁর দায়িত্বে নিয়ে নেন — আহমাদ ১৮৯৬৭, আবু দাউদ ৫০৭২, তিরমিযি ৩৩৮৯।",
            source = "Musnad Ahmad 18967; Jami at-Tirmidhi 3389",
        ),
        dhikr(
            id = "morn_la_yadurru",
            name = "Bismillahilladhi la yadurru ma'asmihi shay'",
            arabic = "بِسْمِ اللّٰهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ، وَهُوَ السَّمِيعُ الْعَلِيمُ",
            pronunciation = "বিসমিল্লাহিল্লাযি লা ইয়াদুররু মাআসমিহি শাইউন ফিল আরদি ওয়া লা ফিস সামা, ওয়া হুয়াস সামিউল আলিম",
            translation = "সেই আল্লাহর নামে, যাঁর নামের সাথে আসমান-জমিনের কোনো কিছুই ক্ষতি করতে পারে না; তিনি সর্বশ্রোতা, সর্বজ্ঞ — In the name of Allah, with whose name nothing on earth or in the heaven can cause harm, and He is the All-Hearing, the All-Knowing",
            lapTarget = 3,
            note = "যে সকাল-সন্ধ্যায় তিনবার এটি বলে, কোনো কিছুই তার ক্ষতি করতে পারে না — আবু দাউদ ৫০৮৮, তিরমিযি ৩৩৮৮, ইবনে মাজাহ ৩৮৬৯।",
            source = "Sunan Abi Dawud 5088; Jami at-Tirmidhi 3388",
        ),
        dhikr(
            id = "morn_tasbih100",
            name = "Subhanallah, Alhamdulillah, Allahu Akbar",
            arabic = "سُبْحَانَ اللّٰهِ، وَالْحَمْدُ لِلّٰهِ، وَاللّٰهُ أَكْبَرُ",
            pronunciation = "সুবহানাল্লাহ, ওয়াল হামদু লিল্লাহ, ওয়াল্লাহু আকবার",
            translation = "আল্লাহ পবিত্র, সকল প্রশংসা আল্লাহর, আল্লাহ সর্বমহান — Glory be to Allah, all praise is due to Allah, and Allah is the Greatest",
            lapTarget = 100,
            note = "সকালে ১০০ বার তাসবিহ-তাহমিদ-তাকবির; সেদিন কেউ তার চেয়ে উত্তম আমল নিয়ে আসতে পারে না যে একই বা বেশি বলেছে — নাসাঈ, আস-সুনানুল কুবরা ১০৬৫৭।",
            source = "an-Nasa'i, as-Sunan al-Kubra 10657",
        ),

        // --- Batch 2 (retained): the four non-situational praise/dua items
        // kept when the occasion-bound adhkar were retired (see retiredBuiltInIds).
        dhikr(
            id = "azim_bihamdih",
            name = "Subhanallahil Azim wa bihamdih",
            arabic = "سُبْحَانَ اللّٰهِ الْعَظِيمِ وَبِحَمْدِهِ",
            pronunciation = "সুবহানাল্লাহিল আযীম ওয়া বিহামদিহি",
            translation = "মহান আল্লাহ পবিত্র এবং তাঁরই প্রশংসা — Glory be to Allah the Most Great, and praise be to Him",
            lapTarget = 100,
            note = "একবার পড়লে জান্নাতে একটি খেজুর গাছ রোপণ করা হয় — তিরমিযি ৩৪৬৪ (সহীহ)। নির্দিষ্ট সংখ্যা নেই।",
            source = "Jami at-Tirmidhi 3464",
        ),
        dhikr(
            id = "ajz_kasal",
            name = "A'udhu bika minal ajzi wal kasal",
            arabic = "اللّٰهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ، وَالْجُبْنِ وَالْهَرَمِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، وَمِنْ فِتْنَةِ الْمَحْيَا وَالْمَمَاتِ",
            pronunciation = "আল্লাহুম্মা ইন্নি আউযু বিকা মিনাল আজযি ওয়াল কাসালি, ওয়াল জুবনি ওয়াল হারামি ওয়াল বুখলি, ওয়া আউযু বিকা মিন আযাবিল ক্বাবরি, ওয়া মিন ফিতনাতিল মাহইয়া ওয়াল মামাতি",
            translation = "হে আল্লাহ, অক্ষমতা, অলসতা, ভীরুতা, অতি-বার্ধক্য ও কৃপণতা থেকে এবং কবরের আযাব ও জীবন-মৃত্যুর ফিতনা থেকে আপনার আশ্রয় চাই — O Allah, I seek refuge in You from incapacity, laziness, cowardice, decrepitude and miserliness, and from the punishment of the grave and the trial of life and death",
            lapTarget = 1,
            note = "নিয়মিত দোয়া — সহীহ বুখারি ৬৩৬৭, মুসলিম ২৭০৬।",
            source = "Sahih al-Bukhari 6367",
        ),
        dhikr(
            id = "munkarat_akhlaq",
            name = "A'udhu bika min munkaratil akhlaq",
            arabic = "اللّٰهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ مُنْكَرَاتِ الْأَخْلَاقِ وَالْأَعْمَالِ وَالْأَهْوَاءِ",
            pronunciation = "আল্লাহুম্মা ইন্নি আউযু বিকা মিন মুনকারাতিল আখলাক্বি ওয়াল আমালি ওয়াল আহওয়াই",
            translation = "হে আল্লাহ, অসৎ চরিত্র, গর্হিত কাজ ও কুপ্রবৃত্তি থেকে আপনার আশ্রয় চাই — O Allah, I seek refuge in You from evil character, deeds and desires",
            lapTarget = 33,
            note = "সাধারণ প্রার্থনা — তিরমিযি ৩৫৯১ (সহীহ)।",
            source = "Jami at-Tirmidhi 3591",
        ),
        dhikr(
            id = "rabbana_atina",
            name = "Rabbana atina fid dunya hasanah",
            arabic = "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
            pronunciation = "রাব্বানা আতিনা ফিদ দুনইয়া হাসানাতান ওয়া ফিল আখিরাতি হাসানাতান ওয়াক্বিনা আযাবান নার",
            translation = "হে আমাদের রব, আমাদের দুনিয়া ও আখিরাতে কল্যাণ দিন এবং জাহান্নামের আযাব থেকে রক্ষা করুন — Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire",
            lapTarget = 33,
            note = "কুরআন ২:২০১ — নবিজির সবচেয়ে বেশি পড়া দোয়া; তাওয়াফে রুকনে ইয়ামানী ও হাজারে আসওয়াদের মাঝে — সহীহ বুখারি ৪৫২২, আবু দাউদ ১৮৯২।",
            source = "Quran 2:201; Sahih al-Bukhari 4522",
        ),

        // --- Asma-ul-Husna: the 99 names of Allah ----------------------------
        // Canonical order follows the well-known al-Walid b. Muslim enumeration
        // appended to the hadith of Abu Hurayrah (Jami at-Tirmidhi 3507 / Sunan
        // Ibn Majah 3861) — the list used on virtually every printed poster and
        // app. `translation` carries the Bangla meaning followed by the English.
        // Each name recites lightly, so lapTarget = 3. The 99 rows live in
        // `asmaUlHusnaList` below and builtInTasbih concatenates them lazily.
    )

    private val asmaUlHusnaList: List<TasbihEntity> = listOf(
        name(1, "Ar-Rahman", "الرَّحْمَٰنُ", "আর-রহমান", "পরম করুণাময়", "The Most Compassionate"),
        name(2, "Ar-Rahim", "الرَّحِيمُ", "আর-রহীম", "পরম দয়ালু", "The Most Merciful"),
        name(3, "Al-Malik", "الْمَلِكُ", "আল-মালিক", "অধিপতি", "The King, the Sovereign"),
        name(4, "Al-Quddus", "الْقُدُّوسُ", "আল-কুদ্দূস", "মহাপবিত্র", "The Most Holy"),
        name(5, "As-Salam", "السَّلَامُ", "আস-সালাম", "শান্তির উৎস", "The Source of Peace"),
        name(6, "Al-Mu'min", "الْمُؤْمِنُ", "আল-মু'মিন", "নিরাপত্তাদাতা", "The Granter of Security"),
        name(7, "Al-Muhaymin", "الْمُهَيْمِنُ", "আল-মুহাইমিন", "রক্ষণাবেক্ষণকারী", "The Guardian, the Overseer"),
        name(8, "Al-Aziz", "الْعَزِيزُ", "আল-আযীয", "মহাপরাক্রমশালী", "The Almighty"),
        name(9, "Al-Jabbar", "الْجَبَّارُ", "আল-জাব্বার", "দুর্নিবার", "The Compeller, the Restorer"),
        name(10, "Al-Mutakabbir", "الْمُتَكَبِّرُ", "আল-মুতাকাব্বির", "মহিমান্বিত", "The Supreme in Greatness"),
        name(11, "Al-Khaliq", "الْخَالِقُ", "আল-খালিক", "সৃষ্টিকর্তা", "The Creator"),
        name(12, "Al-Bari'", "الْبَارِئُ", "আল-বারি", "উদ্ভাবনকারী", "The Originator"),
        name(13, "Al-Musawwir", "الْمُصَوِّرُ", "আল-মুসাউইর", "রূপদানকারী", "The Fashioner"),
        name(14, "Al-Ghaffar", "الْغَفَّارُ", "আল-গাফ্ফার", "পরম ক্ষমাশীল", "The All-Forgiving"),
        name(15, "Al-Qahhar", "الْقَهَّارُ", "আল-কাহহার", "মহাপ্রতাপশালী", "The All-Prevailing"),
        name(16, "Al-Wahhab", "الْوَهَّابُ", "আল-ওয়াহহাব", "মহাদাতা", "The Bestower"),
        name(17, "Ar-Razzaq", "الرَّزَّاقُ", "আর-রাযযাক", "রিযিকদাতা", "The Provider"),
        name(18, "Al-Fattah", "الْفَتَّاحُ", "আল-ফাত্তাহ", "মহাবিজয়দাতা", "The Opener, the Judge"),
        name(19, "Al-Alim", "الْعَلِيمُ", "আল-আলীম", "সর্বজ্ঞ", "The All-Knowing"),
        name(20, "Al-Qabid", "الْقَابِضُ", "আল-কাবিদ", "সংকোচনকারী", "The Withholder"),
        name(21, "Al-Basit", "الْبَاسِطُ", "আল-বাসিত", "প্রসারণকারী", "The Extender"),
        name(22, "Al-Khafid", "الْخَافِضُ", "আল-খাফিদ", "অবনতকারী", "The Reducer"),
        name(23, "Ar-Rafi'", "الرَّافِعُ", "আর-রাফি", "উন্নতকারী", "The Exalter"),
        name(24, "Al-Mu'izz", "الْمُعِزُّ", "আল-মুইয্য", "সম্মানদাতা", "The Honourer"),
        name(25, "Al-Mudhill", "الْمُذِلُّ", "আল-মুযিল্ল", "অপমানকারী", "The Dishonourer"),
        name(26, "As-Sami'", "السَّمِيعُ", "আস-সামী", "সর্বশ্রোতা", "The All-Hearing"),
        name(27, "Al-Basir", "الْبَصِيرُ", "আল-বাসীর", "সর্বদ্রষ্টা", "The All-Seeing"),
        name(28, "Al-Hakam", "الْحَكَمُ", "আল-হাকাম", "বিচারক", "The Judge"),
        name(29, "Al-Adl", "الْعَدْلُ", "আল-আদল", "ন্যায়পরায়ণ", "The Utterly Just"),
        name(30, "Al-Latif", "اللَّطِيفُ", "আল-লাতীফ", "সূক্ষ্মদর্শী", "The Subtle, the Gentle"),
        name(31, "Al-Khabir", "الْخَبِيرُ", "আল-খাবীর", "সম্যক অবগত", "The All-Aware"),
        name(32, "Al-Halim", "الْحَلِيمُ", "আল-হালীম", "পরম সহনশীল", "The Forbearing"),
        name(33, "Al-Azim", "الْعَظِيمُ", "আল-আযীম", "মহান", "The Magnificent"),
        name(34, "Al-Ghafur", "الْغَفُورُ", "আল-গাফূর", "ক্ষমাশীল", "The All-Forgiving"),
        name(35, "Ash-Shakur", "الشَّكُورُ", "আশ-শাকূর", "গুণগ্রাহী", "The Most Appreciative"),
        name(36, "Al-Ali", "الْعَلِيُّ", "আল-আলী", "সুউচ্চ", "The Most High"),
        name(37, "Al-Kabir", "الْكَبِيرُ", "আল-কাবীর", "সর্বাপেক্ষা বড়", "The Most Great"),
        name(38, "Al-Hafiz", "الْحَفِيظُ", "আল-হাফীয", "সংরক্ষণকারী", "The Preserver"),
        name(39, "Al-Muqit", "الْمُقِيتُ", "আল-মুকীত", "আহার্যদাতা", "The Sustainer"),
        name(40, "Al-Hasib", "الْحَسِيبُ", "আল-হাসীব", "হিসাবগ্রহণকারী", "The Reckoner"),
        name(41, "Al-Jalil", "الْجَلِيلُ", "আল-জালীল", "মহিমাময়", "The Majestic"),
        name(42, "Al-Karim", "الْكَرِيمُ", "আল-কারীম", "মহানুভব", "The Most Generous"),
        name(43, "Ar-Raqib", "الرَّقِيبُ", "আর-রাকীব", "পর্যবেক্ষণকারী", "The Watchful"),
        name(44, "Al-Mujib", "الْمُجِيبُ", "আল-মুজীব", "প্রার্থনা কবুলকারী", "The Responsive"),
        name(45, "Al-Wasi'", "الْوَاسِعُ", "আল-ওয়াসি", "সর্বব্যাপী", "The All-Encompassing"),
        name(46, "Al-Hakim", "الْحَكِيمُ", "আল-হাকীম", "প্রজ্ঞাময়", "The All-Wise"),
        name(47, "Al-Wadud", "الْوَدُودُ", "আল-ওয়াদূদ", "পরম প্রেমময়", "The Most Loving"),
        name(48, "Al-Majid", "الْمَجِيدُ", "আল-মাজীদ", "মহাগৌরবান্বিত", "The All-Glorious"),
        name(49, "Al-Ba'ith", "الْبَاعِثُ", "আল-বা'ইছ", "পুনরুত্থানকারী", "The Resurrector"),
        name(50, "Ash-Shahid", "الشَّهِيدُ", "আশ-শাহীদ", "সর্বজ্ঞ সাক্ষী", "The All-Witnessing"),
        name(51, "Al-Haqq", "الْحَقُّ", "আল-হাক্ক", "পরম সত্য", "The Absolute Truth"),
        name(52, "Al-Wakil", "الْوَكِيلُ", "আল-ওয়াকীল", "কর্মবিধায়ক", "The Trustee, the Disposer of Affairs"),
        name(53, "Al-Qawiyy", "الْقَوِيُّ", "আল-কাউইয়্য", "মহাশক্তিধর", "The All-Strong"),
        name(54, "Al-Matin", "الْمَتِينُ", "আল-মাতীন", "সুদৃঢ়", "The Firm, the Steadfast"),
        name(55, "Al-Waliyy", "الْوَلِيُّ", "আল-ওয়ালী", "অভিভাবক বন্ধু", "The Protecting Friend"),
        name(56, "Al-Hamid", "الْحَمِيدُ", "আল-হামীদ", "প্রশংসিত", "The Praiseworthy"),
        name(57, "Al-Muhsi", "الْمُحْصِي", "আল-মুহসী", "পূর্ণ গণনাকারী", "The All-Enumerating"),
        name(58, "Al-Mubdi'", "الْمُبْدِئُ", "আল-মুবদি", "প্রথম সৃষ্টিকারী", "The Originator"),
        name(59, "Al-Mu'id", "الْمُعِيدُ", "আল-মুঈদ", "পুনঃসৃষ্টিকারী", "The Restorer"),
        name(60, "Al-Muhyi", "الْمُحْيِي", "আল-মুহয়ী", "জীবনদাতা", "The Giver of Life"),
        name(61, "Al-Mumit", "الْمُمِيتُ", "আল-মুমীত", "মৃত্যুদাতা", "The Bringer of Death"),
        name(62, "Al-Hayy", "الْحَيُّ", "আল-হাইয়্য", "চিরঞ্জীব", "The Ever-Living"),
        name(63, "Al-Qayyum", "الْقَيُّومُ", "আল-কাইয়্যূম", "স্বয়ংস্থিত সর্বসত্তার ধারক", "The Self-Subsisting Sustainer of all"),
        name(64, "Al-Wajid", "الْوَاجِدُ", "আল-ওয়াজিদ", "অভাবমুক্ত", "The Perceiver, the Finder"),
        name(65, "Al-Majid", "الْمَاجِدُ", "আল-মাজিদ", "মহিমান্বিত", "The Illustrious"),
        name(66, "Al-Wahid", "الْوَاحِدُ", "আল-ওয়াহিদ", "এক", "The One"),
        name(67, "Al-Ahad", "الْأَحَدُ", "আল-আহাদ", "অদ্বিতীয়", "The Indivisible, the Unique"),
        name(68, "As-Samad", "الصَّمَدُ", "আস-সামাদ", "অমুখাপেক্ষী", "The Eternal, the Self-Sufficient"),
        name(69, "Al-Qadir", "الْقَادِرُ", "আল-কাদির", "সর্বশক্তিমান", "The All-Powerful"),
        name(70, "Al-Muqtadir", "الْمُقْتَدِرُ", "আল-মুকতাদির", "প্রবল ক্ষমতাধর", "The All-Determining"),
        name(71, "Al-Muqaddim", "الْمُقَدِّمُ", "আল-মুকাদ্দিম", "অগ্রসরকারী", "The Expediter"),
        name(72, "Al-Mu'akhkhir", "الْمُؤَخِّرُ", "আল-মু'আখখির", "বিলম্বকারী", "The Delayer"),
        name(73, "Al-Awwal", "الْأَوَّلُ", "আল-আউয়াল", "অনাদি", "The First"),
        name(74, "Al-Akhir", "الْآخِرُ", "আল-আখির", "অনন্ত", "The Last"),
        name(75, "Az-Zahir", "الظَّاهِرُ", "আয-যাহির", "প্রকাশ্য", "The Manifest"),
        name(76, "Al-Batin", "الْبَاطِنُ", "আল-বাতিন", "অপ্রকাশ্য", "The Hidden"),
        name(77, "Al-Wali", "الْوَالِي", "আল-ওয়ালী", "সর্বময় কর্তা", "The Governor"),
        name(78, "Al-Muta'ali", "الْمُتَعَالِي", "আল-মুতাআলী", "সর্বোচ্চ মহান", "The Most Exalted"),
        name(79, "Al-Barr", "الْبَرُّ", "আল-বার্র", "কল্যাণকারী", "The Source of All Goodness"),
        name(80, "At-Tawwab", "التَّوَّابُ", "আত-তাওয়াব", "তওবা কবুলকারী", "The Ever-Accepting of Repentance"),
        name(81, "Al-Muntaqim", "الْمُنْتَقِمُ", "আল-মুনতাকিম", "প্রতিশোধ গ্রহণকারী", "The Avenger"),
        name(82, "Al-Afuww", "الْعَفُوُّ", "আল-আফুউ", "পরম মার্জনাকারী", "The Pardoner"),
        name(83, "Ar-Ra'uf", "الرَّءُوفُ", "আর-রাঊফ", "পরম স্নেহশীল", "The Ever-Gentle, the Kind"),
        name(84, "Malik-ul-Mulk", "مَالِكُ الْمُلْكِ", "মালিকুল মুলক", "সমগ্র রাজত্বের অধিপতি", "Master of the Kingdom"),
        name(85, "Dhul-Jalali wal-Ikram", "ذُو الْجَلَالِ وَالْإِكْرَامِ", "যুল জালালি ওয়াল ইকরাম", "মহিমা ও সম্মানের অধিকারী", "Possessor of Majesty and Honour"),
        name(86, "Al-Muqsit", "الْمُقْسِطُ", "আল-মুকসিত", "ন্যায়বিচারক", "The Equitable"),
        name(87, "Al-Jami'", "الْجَامِعُ", "আল-জামি", "একত্রকারী", "The Gatherer"),
        name(88, "Al-Ghani", "الْغَنِيُّ", "আল-গানী", "অভাবমুক্ত ঐশ্বর্যবান", "The Self-Sufficient"),
        name(89, "Al-Mughni", "الْمُغْنِي", "আল-মুগনী", "অভাবমোচনকারী", "The Enricher"),
        name(90, "Al-Mani'", "الْمَانِعُ", "আল-মানি", "প্রতিরোধকারী", "The Withholder, the Preventer"),
        name(91, "Ad-Darr", "الضَّارُّ", "আদ-দার্র", "অনিষ্টের ক্ষমতাধর", "The Distresser"),
        name(92, "An-Nafi'", "النَّافِعُ", "আন-নাফি", "কল্যাণদাতা", "The Bestower of Benefit"),
        name(93, "An-Nur", "النُّورُ", "আন-নূর", "জ্যোতি", "The Light"),
        name(94, "Al-Hadi", "الْهَادِي", "আল-হাদী", "পথপ্রদর্শক", "The Guide"),
        name(95, "Al-Badi'", "الْبَدِيعُ", "আল-বাদী", "অতুলনীয় স্রষ্টা", "The Incomparable Originator"),
        name(96, "Al-Baqi", "الْبَاقِي", "আল-বাকী", "চিরস্থায়ী", "The Ever-Enduring"),
        name(97, "Al-Warith", "الْوَارِثُ", "আল-ওয়ারিছ", "চূড়ান্ত উত্তরাধিকারী", "The Inheritor"),
        name(98, "Ar-Rashid", "الرَّشِيدُ", "আর-রাশীদ", "সঠিক পথের পরিচালক", "The Guide to the Right Path"),
        name(99, "As-Sabur", "الصَّبُورُ", "আস-সাবূর", "পরম ধৈর্যশীল", "The Most Patient"),
    )

    // Presets seed as favorites so they appear on Home out of the box; the user
    // unstars one on the Routines page to remove it from Home.
    val presetRoutines: List<RoutineEntity> = listOf(
        RoutineEntity(id = "morning", name = "Morning Dhikr", isPreset = true, isFavorite = true, createdAt = SEED_TIMESTAMP, updatedAt = SEED_TIMESTAMP),
        RoutineEntity(id = "evening", name = "Evening Dhikr", isPreset = true, isFavorite = true, createdAt = SEED_TIMESTAMP, updatedAt = SEED_TIMESTAMP),
        RoutineEntity(id = "after_salah", name = "After Salah", isPreset = true, isFavorite = true, createdAt = SEED_TIMESTAMP, updatedAt = SEED_TIMESTAMP),
        RoutineEntity(id = "before_sleep", name = "Before Sleep", isPreset = true, isFavorite = true, createdAt = SEED_TIMESTAMP, updatedAt = SEED_TIMESTAMP),
        RoutineEntity(id = "asma_ul_husna", name = "Asma-ul-Husna", isPreset = true, isFavorite = true, createdAt = SEED_TIMESTAMP, updatedAt = SEED_TIMESTAMP),
        // Not favorited: lives on the Routines page only until the user stars it.
        RoutineEntity(id = "istighfar", name = "Istighfar", isPreset = true, isFavorite = false, createdAt = SEED_TIMESTAMP, updatedAt = SEED_TIMESTAMP),
    )

    val presetRoutineSteps: List<RoutineStepEntity> by lazy {
        coreRoutineSteps + asmaUlHusnaSteps + istighfarSteps + morningSteps
    }

    // Morning Dhikr: the full sequence from
    // lifewithallah.com/dhikr-dua/main-adhkar/morning, in page order. Replaces
    // the old 3-step SubhanAllah/Alhamdulillah/AllahuAkbar stub. Each pair is
    // (tasbihId, count). Reused existing dhikr: kursi, hamm_hazan,
    // ya_hayyu_astaghith, istighfar_sayyid, hasbiyallah_arsh, bihamdihi,
    // tahlil_wahdahu, durood_ali, istighfar_atubu, adada_khalqih.
    private val morningSteps: List<RoutineStepEntity> = listOf(
        "kursi" to 1,
        "morn_3quls" to 3,
        "istighfar_sayyid" to 1,
        "hamm_hazan" to 1,
        "morn_afiyah" to 1,
        "morn_fatir" to 1,
        "ya_hayyu_astaghith" to 1,
        "morn_nimah" to 1,
        "morn_fitrah" to 1,
        "morn_uthni" to 3,
        "morn_mulk_shar" to 1,
        "morn_mulk_alamin" to 1,
        "morn_ushhiduka" to 4,
        "morn_bika_asbahna" to 1,
        "morn_afini_badani" to 3,
        "hasbiyallah_arsh" to 7,
        "morn_raditu" to 3,
        "morn_la_yadurru" to 3,
        "bihamdihi" to 100,
        "tahlil_wahdahu" to 100,
        "morn_tasbih100" to 100,
        "durood_ali" to 10,
        "istighfar_atubu" to 100,
        "adada_khalqih" to 3,
    ).mapIndexed { i, (id, count) ->
        RoutineStepEntity(routineId = "morning", tasbihId = id, stepOrder = i, targetCount = count)
    }

    // Istighfar: the 9 Qur'anic + 10 sunnah forms from
    // lifewithallah.com/dhikr-dua/main-adhkar/istighfar, in the page's order.
    // Step 13 is the pre-existing `afuww` tasbih (that page's sunnah #4).
    private val istighfarSteps: List<RoutineStepEntity> = listOf(
        "istighfar_q_yunus", "istighfar_q_musa", "istighfar_q_adam", "istighfar_q_waliyy",
        "istighfar_q_amanna", "istighfar_q_irham", "istighfar_q_ilm", "istighfar_q_ikhwan",
        "istighfar_q_nur",
        "istighfar_sayyid", "istighfar_malik", "istighfar_khatiati", "afuww",
        "istighfar_rabba_muhammad", "istighfar_diqqahu", "istighfar_kathira",
        "istighfar_afini", "istighfar_baaid", "istighfar_muminin",
    ).mapIndexed { i, id ->
        RoutineStepEntity(routineId = "istighfar", tasbihId = id, stepOrder = i, targetCount = 3)
    }

    private val coreRoutineSteps: List<RoutineStepEntity> = listOf(
        // Morning Dhikr steps live in `morningSteps` (full lifewithallah sequence).
        // Evening Dhikr: same three, evening framing — no separate evening-specific
        // prototype data exists, so this reuses the same structure as Morning per
        // the plan's own "Evening Dhikr" listing (plan.md §22) which gives no
        // distinct counts of its own.
        RoutineStepEntity(routineId = "evening", tasbihId = "subhan", stepOrder = 0, targetCount = 33),
        RoutineStepEntity(routineId = "evening", tasbihId = "hamd", stepOrder = 1, targetCount = 33),
        RoutineStepEntity(routineId = "evening", tasbihId = "akbar", stepOrder = 2, targetCount = 34),
        // After Salah: matches the prototype's `salah` routine exactly (same 3 steps)
        RoutineStepEntity(routineId = "after_salah", tasbihId = "subhan", stepOrder = 0, targetCount = 33),
        RoutineStepEntity(routineId = "after_salah", tasbihId = "hamd", stepOrder = 1, targetCount = 33),
        RoutineStepEntity(routineId = "after_salah", tasbihId = "akbar", stepOrder = 2, targetCount = 34),
        // Before Sleep: matches the prototype's `sleep` routine exactly —
        // Astaghfirullah x100, Subhanallahi wa bihamdihi x100
        RoutineStepEntity(routineId = "before_sleep", tasbihId = "istighfar", stepOrder = 0, targetCount = 100),
        RoutineStepEntity(routineId = "before_sleep", tasbihId = "bihamdihi", stepOrder = 1, targetCount = 100),
    )

    // Asma-ul-Husna: walk all 99 names in canonical order, 3 recitations each.
    private val asmaUlHusnaSteps: List<RoutineStepEntity> = (1..99).map { n ->
        RoutineStepEntity(
            routineId = "asma_ul_husna",
            tasbihId = "asma_%02d".format(n),
            stepOrder = n - 1,
            targetCount = 3,
        )
    }
}
