package com.dhikr.app.core.database.seed

import com.dhikr.app.core.database.entity.RoutineEntity
import com.dhikr.app.core.database.entity.RoutineStepEntity
import com.dhikr.app.core.database.entity.TasbihEntity

object SeedData {
    private const val SEED_TIMESTAMP = 0L

    // Compact builder for the added dhikr below. Arabic is fully vowelled. Every
    // text field is bilingual: the plain field is the English side, the `*Bn`
    // field the Bangla side. `pronunciation` is the Roman-script recitation
    // guide, `pronunciationBn` the same words in Bangla script. `translation` /
    // `translationBn` carry the meaning; `note` / `noteBn` the source, grade and
    // any note on the count. Counts follow an authentic sunnah figure where a
    // hadith fixes one, otherwise the user-supplied number.
    private fun dhikr(
        id: String,
        name: String,
        nameBn: String,
        arabic: String,
        pronunciation: String,
        pronunciationBn: String,
        translation: String,
        translationBn: String,
        lapTarget: Int,
        note: String = "",
        noteBn: String = "",
        source: String? = null,
    ) = TasbihEntity(
        id = id,
        name = name,
        nameBn = nameBn,
        arabic = arabic,
        pronunciation = pronunciation,
        pronunciationBn = pronunciationBn,
        translation = translation,
        translationBn = translationBn,
        note = note,
        noteBn = noteBn,
        source = source,
        lapTarget = lapTarget,
        lapCount = 1,
        isFavorite = false,
        isBuiltIn = true,
        createdAt = SEED_TIMESTAMP,
        updatedAt = SEED_TIMESTAMP,
    )

    private fun name(
        n: Int,
        translit: String,
        arabic: String,
        bangla: String,
        meaningBn: String,
        meaningEn: String,
    ) = TasbihEntity(
        id = "asma_%02d".format(n),
        name = translit,
        nameBn = bangla,
        arabic = arabic,
        pronunciation = translit,
        pronunciationBn = bangla,
        translation = meaningEn,
        translationBn = meaningBn,
        note = "Asma-ul-Husna #$n. From the well-known list of the 99 names of Allah — Jami at-Tirmidhi 3507, Sunan Ibn Majah 3861.",
        noteBn = "আসমাউল হুসনা #$n। ৯৯ নামের প্রসিদ্ধ তালিকা — তিরমিযি ৩৫০৭, ইবনে মাজাহ ৩৮৬১।",
        source = "Jami at-Tirmidhi 3507",
        lapTarget = 3,
        lapCount = 1,
        isFavorite = false,
        isBuiltIn = true,
        createdAt = SEED_TIMESTAMP,
        updatedAt = SEED_TIMESTAMP,
    )

    val builtInTasbih: List<TasbihEntity> by lazy {
        coreTasbih + asmaUlHusnaList
    }

    /**
     * Built-in dhikr ids retired from the free Tasbih library: situational /
     * occasion-bound duas (morning-evening adhkar, in-salah phrases, travel,
     * weather, greetings, funeral, hajj, one-off event duas) that don't fit a
     * "recite whenever you want" counter. They are gone from [builtInTasbih] for
     * fresh installs, and [DhikrApplication] purges them from existing databases
     * on launch — skipping any the user favourited or that a routine step still
     * references (routine_step -> tasbih is RESTRICT).
     */
    val retiredBuiltInIds: Set<String> = setOf(
        // From the original "added dhikr" block
        "malik_quddus", "kalimat_tammat",
        // Morning & evening adhkar
        "sayyidul_istighfar", "bismillah_la_yadurru", "raditu_billah", "asbahna_bika",
        "amsayna_bika", "asbahna_mulk", "amsayna_mulk", "afini_badan", "kufr_faqr",
        "rahmataka_arju", "alimal_ghayb", "wake_afiyah", "morning_three_quls",
        "afiyah_dunya_akhirah",
        // Waking & sleeping
        "wake_alhamdu", "sleep_bismika", "sleep_three_quls", "sleep_aslamtu",
        "night_wake_tahlil", "night_turn", "night_terror", "baqarah_last_two",
        // Wudu, toilet, home, clothes, eating
        "toilet_enter", "toilet_exit", "wudu_shahada", "wudu_tawwabin", "enter_home",
        "leave_home", "undress", "new_clothes", "eat_bismillah", "eat_forgot_bismillah",
        "eat_after", "after_milk",
        // Masjid & adhan
        "masjid_enter", "masjid_exit", "adhan_response", "after_adhan",
        // Inside salah
        "ruku", "sujud", "subbuh_quddus", "sami_allah", "rabbana_lakal_hamd",
        "between_sujud", "tashahhud", "durood_ibrahim", "dua_masura", "four_refuge_salah",
        "after_salah_salam", "ainni_dhikr", "tahajjud_hamd", "sujud_tilawah", "qunut",
        // Event / feeling triggered
        "amantu_billah", "masha_allah", "kaffarat_majlis", "khashyah_dua", "sahl",
        "musibah", "condolence", "good_news", "alhamdu_kulli_hal", "hamm_qalb_quran",
        "tiyarah", "taqabbal", "istikhara",
        // Distress / protection borderline, retired
        "karb_dua", "fear_dua", "ya_hayyu_aslih", "shirk_refuge", "hamm_hazan_full",
        "dua_yunus", "taawwudh",
        // Travel
        "ride_vehicle", "travel_return", "return_home_tawbah", "travel_ascend",
        "farewell_traveler", "farewell_traveler2", "traveler_farewell",
        // Weather & nature
        "rain_start", "rain_after", "rain_excess", "wind", "thunder", "new_moon",
        // Sneeze, greeting, social
        "sneeze_response", "sneeze_reply", "salam", "salam_reply", "jazakallah",
        "love_fillah", "love_reply", "musafaha", "newlywed", "barakallah_debt",
        "new_clothes_dua1", "new_clothes_dua2", "guest_dua", "iftar_host", "feeder_dua",
        "new_fruit",
        // Sickness & the deceased
        "visit_sick", "sick_visit_7", "see_afflicted", "children_protection", "janazah",
        "grave_lowering", "after_burial", "grave_visit",
        // Hajj / Umrah / Qurbani
        "safa_marwah", "hajar_aswad", "maqam_ibrahim", "qurbani",
    )

    private val coreTasbih: List<TasbihEntity> = listOf(
        TasbihEntity(
            id = "kursi",
            name = "Ayatul Kursi",
            nameBn = "আয়াতুল কুরসি",
            arabic = "",
            pronunciation = "Allahu la ilaha illa huwal hayyul qayyum, la ta'khudhuhu sinatun wa la nawm, " +
                "lahu ma fis samawati wa ma fil ard, man dhal ladhi yashfa'u indahu illa bi idhnih, " +
                "ya'lamu ma bayna aydihim wa ma khalfahum, wa la yuhituna bi shay'in min ilmihi illa bima sha', " +
                "wasi'a kursiyyuhus samawati wal ard, wa la ya'uduhu hifzuhuma, wa huwal aliyyul azim",
            pronunciationBn = "আল্লাহু লা ইলাহা ইল্লা হুয়াল হাইয়্যুল কইয়্যুমু লা তা খুজুহু সিনাত্যু ওয়ালা নাউম। " +
                "লাহু মা ফিছছামা ওয়াতি ওয়ামা ফিল আরদ। মান যাল্লাযী ইয়াস ফায়ু ইন দাহু ইল্লা বি ইজনিহি ইয়া লামু মা " +
                "বাইনা আইদিহিম ওয়ামা খল ফাহুম ওয়ালা ইউ হিতুনা বিশাই ইম্ মিন ইল্ মিহি ইল্লা বিমা সাআ ওয়াসিয়া " +
                "কুরসিইউ হুস ছামা ওয়াতি ওয়াল আরদ্ ওয়ালা ইয়া উদুহু হিফজুহুমা ওয়াহুয়াল আলিয়্যুল আজিম",
            translation = "Allah! There is no god but He, the Ever-Living, the Sustainer of all. Neither " +
                "drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever " +
                "is on the earth. Who is it that can intercede with Him except by His permission? He knows " +
                "what is before them and what is behind them, and they encompass nothing of His knowledge " +
                "except what He wills. His Kursi extends over the heavens and the earth, and their upkeep " +
                "tires Him not. He is the Most High, the Most Great.",
            translationBn = "আল্লাহ! তিনি ছাড়া কোনো উপাস্য নেই, চিরঞ্জীব, সর্বসত্তার ধারক। তন্দ্রা ও নিদ্রা তাঁকে স্পর্শ " +
                "করে না। আসমান ও জমিনে যা কিছু আছে সবই তাঁর। তাঁর অনুমতি ছাড়া কে তাঁর কাছে সুপারিশ করবে? তাদের " +
                "সামনে ও পিছনে যা আছে তিনি জানেন, আর তারা তাঁর জ্ঞানের কিছুই আয়ত্ত করতে পারে না যা তিনি চান তা " +
                "ছাড়া। তাঁর কুরসি আসমান ও জমিন জুড়ে বিস্তৃত, আর এ দুটির রক্ষণাবেক্ষণ তাঁকে ক্লান্ত করে না। তিনি " +
                "সুউচ্চ, মহান।",
            note = "",
            noteBn = "",
            lapTarget = 7,
            lapCount = 1,
            isFavorite = true,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "subhan",
            name = "SubhanAllah",
            nameBn = "সুবহানাল্লাহ",
            arabic = "سُبْحَانَ اللّٰه",
            pronunciation = "SubhanAllah",
            pronunciationBn = "সুবহানাল্লাহ",
            translation = "Glory be to Allah",
            translationBn = "আল্লাহ পবিত্র",
            lapTarget = 33,
            lapCount = 3,
            isFavorite = true,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "hamd",
            name = "Alhamdulillah",
            nameBn = "আলহামদুলিল্লাহ",
            arabic = "الْحَمْدُ لِلّٰه",
            pronunciation = "Alhamdulillah",
            pronunciationBn = "আলহামদুলিল্লাহ",
            translation = "All praise is due to Allah",
            translationBn = "সমস্ত প্রশংসা আল্লাহর",
            lapTarget = 33,
            lapCount = 3,
            isFavorite = true,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "akbar",
            name = "Allahu Akbar",
            nameBn = "আল্লাহু আকবার",
            arabic = "اللّٰهُ أَكْبَر",
            pronunciation = "Allahu Akbar",
            pronunciationBn = "আল্লাহু আকবার",
            translation = "Allah is the greatest",
            translationBn = "আল্লাহ সর্বমহান",
            lapTarget = 34,
            lapCount = 3,
            isFavorite = true,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "istighfar",
            name = "Astaghfirullah",
            nameBn = "আস্তাগফিরুল্লাহ",
            arabic = "أَسْتَغْفِرُ اللّٰه",
            pronunciation = "Astaghfirullah",
            pronunciationBn = "আস্তাগফিরুল্লাহ",
            translation = "I seek forgiveness from Allah",
            translationBn = "আমি আল্লাহর কাছে ক্ষমা চাই",
            lapTarget = 100,
            lapCount = 1,
            isFavorite = false,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "bihamdihi",
            name = "Subhanallahi wa bihamdihi",
            nameBn = "সুবহানাল্লাহি ওয়া বিহামদিহি",
            arabic = "سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ",
            pronunciation = "Subhanallahi wa bihamdihi",
            pronunciationBn = "সুবহানাল্লাহি ওয়া বিহামদিহি",
            translation = "Glory be to Allah and praise be to Him",
            translationBn = "আল্লাহ পবিত্র ও সকল প্রশংসা তাঁর",
            lapTarget = 100,
            lapCount = 1,
            isFavorite = false,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "hawla",
            name = "La hawla wa la quwwata illa billah",
            nameBn = "লা হাওলা ওয়ালা কুওয়াতা ইল্লা বিল্লাহ",
            arabic = "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللّٰه",
            pronunciation = "La hawla wa la quwwata illa billah",
            pronunciationBn = "লা হাওলা ওয়ালা কুওয়াতা ইল্লা বিল্লাহ",
            translation = "There is no power nor strength except with Allah",
            translationBn = "আল্লাহ ছাড়া কোনো শক্তি বা সামর্থ্য নেই",
            lapTarget = 33,
            lapCount = 1,
            isFavorite = false,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),

        // --- Added dhikr (researched + verified) ------------------------------
        dhikr(
            id = "tahlil",
            name = "La ilaha illallah",
            nameBn = "লা ইলাহা ইল্লাল্লাহ",
            arabic = "لَا إِلَٰهَ إِلَّا اللّٰهُ",
            pronunciation = "La ilaha illallah",
            pronunciationBn = "লা ইলাহা ইল্লাল্লাহ",
            translation = "There is no true god but Allah",
            translationBn = "আল্লাহ ছাড়া কোনো সত্য উপাস্য নেই",
            lapTarget = 100,
            note = "The best remembrance. \"The best remembrance is La ilaha illallah\" — Jami at-Tirmidhi 3383 (hasan).",
            noteBn = "শ্রেষ্ঠ যিকর। “আফযালুয যিকরি লা ইলাহা ইল্লাল্লাহ” — তিরমিযি ৩৩৮৩ (হাসান)।",
            source = "Jami at-Tirmidhi 3383",
        ),
        dhikr(
            id = "bihamdihi_azim",
            name = "Subhanallahi wa bihamdihi, Subhanallahil Azim",
            nameBn = "সুবহানাল্লাহি ওয়া বিহামদিহি, সুবহানাল্লাহিল আযীম",
            arabic = "سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ، سُبْحَانَ اللّٰهِ الْعَظِيمِ",
            pronunciation = "Subhanallahi wa bihamdihi, Subhanallahil Azim",
            pronunciationBn = "সুবহানাল্লাহি ওয়া বিহামদিহি, সুবহানাল্লাহিল আযীম",
            translation = "Glory and praise be to Allah, glory be to Allah the Most Great",
            translationBn = "আল্লাহ পবিত্র ও তাঁরই প্রশংসা, মহান আল্লাহ পবিত্র",
            lapTarget = 100,
            note = "Two phrases light on the tongue, heavy on the scale, beloved to the Most Merciful — Sahih al-Bukhari 6406. No fixed count in the hadith; 100 is the user's choice.",
            noteBn = "জিহ্বায় হালকা, মিযানে ভারী, রহমানের কাছে প্রিয় দুই বাক্য — সহীহ বুখারি ৬৪০৬। নির্দিষ্ট সংখ্যা হাদিসে নেই; ১০০ ব্যবহারকারীর পছন্দ।",
            source = "Sahih al-Bukhari 6406",
        ),
        dhikr(
            id = "durood_ali",
            name = "Allahumma salli ala Muhammadin wa ala ali Muhammad",
            nameBn = "আল্লাহুম্মা সাল্লি আলা মুহাম্মাদিন ওয়া আলা আলি মুহাম্মাদ",
            arabic = "اللّٰهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ",
            pronunciation = "Allahumma salli ala Muhammadin wa ala ali Muhammad",
            pronunciationBn = "আল্লাহুম্মা সাল্লি আলা মুহাম্মাদিন ওয়া আলা আলি মুহাম্মাদ",
            translation = "O Allah, send blessings upon Muhammad and the family of Muhammad",
            translationBn = "হে আল্লাহ, মুহাম্মাদ ও তাঁর পরিবারের প্রতি রহমত বর্ষণ করুন",
            lapTarget = 100,
            note = "Salawat. Reciting it 10 times morning and evening brings the Prophet's intercession on the Day of Judgement — Tabarani. The count of 100 is not from the hadith.",
            noteBn = "দরূদ। সকাল-সন্ধ্যায় ১০ বার পড়লে কিয়ামতে শাফাআত — তাবারানি। নির্দিষ্ট ১০০ সংখ্যা হাদিসে নেই।",
            source = "al-Mu'jam al-Awsat (Tabarani)",
        ),
        dhikr(
            id = "tahlil_wahdahu",
            name = "La ilaha illallahu wahdahu la sharika lah",
            nameBn = "লা ইলাহা ইল্লাল্লাহু ওয়াহদাহু লা শারিকা লাহু",
            arabic = "لَا إِلَٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
            pronunciation = "La ilaha illallahu wahdahu la sharika lah, lahul mulku wa lahul hamdu wa huwa ala kulli shay'in qadir",
            pronunciationBn = "লা ইলাহা ইল্লাল্লাহু ওয়াহদাহু লা শারিকা লাহু, লাহুল মুলকু ওয়া লাহুল হামদু ওয়া হুয়া আলা কুল্লি শাইইন কাদীর",
            translation = "There is no god but Allah alone, no partner has He; His is the dominion and the praise, and He is able to do all things",
            translationBn = "আল্লাহ ছাড়া কোনো উপাস্য নেই, তিনি একক, তাঁর কোনো শরিক নেই; রাজত্ব ও প্রশংসা তাঁরই, তিনি সর্বশক্তিমান",
            lapTarget = 100,
            note = "Said 100 times a day: the reward of freeing 10 slaves, 100 good deeds recorded, 100 sins erased, and protection from Shaytan until evening — Sahih al-Bukhari 3293, Sahih Muslim 2691. Sunnah count is 100.",
            noteBn = "দিনে ১০০ বার = ১০ জন দাস মুক্তির সওয়াব, ১০০ নেকি, ১০০ গুনাহ মাফ, সন্ধ্যা পর্যন্ত শয়তান থেকে রক্ষা — সহীহ বুখারি ৩২৯৩, মুসলিম ২৬৯১। সুন্নাহ সংখ্যা ১০০।",
            source = "Sahih al-Bukhari 3293; Sahih Muslim 2691",
        ),
        dhikr(
            id = "hasbunallah",
            name = "Hasbunallahu wa ni'mal wakil",
            nameBn = "হাসবুনাল্লাহু ওয়া নিমাল ওয়াকীল",
            arabic = "حَسْبُنَا اللّٰهُ وَنِعْمَ الْوَكِيلُ",
            pronunciation = "Hasbunallahu wa ni'mal wakil",
            pronunciationBn = "হাসবুনাল্লাহু ওয়া নিমাল ওয়াকীল",
            translation = "Allah is sufficient for us, and He is the best disposer of affairs",
            translationBn = "আল্লাহই আমাদের জন্য যথেষ্ট, তিনিই উত্তম কর্মবিধায়ক",
            lapTarget = 100,
            note = "Quran 3:173 — the words of the Companions after Uhud, and of Ibrahim (as) when cast into the fire. No fixed count.",
            noteBn = "কুরআন ৩:১৭৩ — উহুদের পর সাহাবিদের এবং আগুনে নিক্ষেপের সময় ইবরাহিম (আঃ)-এর বাণী। নির্দিষ্ট সংখ্যা নেই।",
            source = "Quran 3:173",
        ),
        dhikr(
            id = "baqiyat",
            name = "Subhanallah walhamdulillah wa la ilaha illallahu wallahu akbar",
            nameBn = "সুবহানাল্লাহি ওয়ালহামদু লিল্লাহি ওয়া লা ইলাহা ইল্লাল্লাহু ওয়াল্লাহু আকবার",
            arabic = "سُبْحَانَ اللّٰهِ وَالْحَمْدُ لِلّٰهِ وَلَا إِلَٰهَ إِلَّا اللّٰهُ وَاللّٰهُ أَكْبَرُ",
            pronunciation = "Subhanallahi walhamdu lillahi wa la ilaha illallahu wallahu akbar",
            pronunciationBn = "সুবহানাল্লাহি ওয়ালহামদু লিল্লাহি ওয়া লা ইলাহা ইল্লাল্লাহু ওয়াল্লাহু আকবার",
            translation = "Glory be to Allah, praise be to Allah, there is no god but Allah, and Allah is the Greatest",
            translationBn = "আল্লাহ পবিত্র, সকল প্রশংসা আল্লাহর, আল্লাহ ছাড়া কোনো উপাস্য নেই, আল্লাহ সর্বমহান",
            lapTarget = 33,
            note = "The four phrases most beloved to Allah — Sahih Muslim 2137. No fixed count.",
            noteBn = "আল্লাহর কাছে সবচেয়ে প্রিয় চার বাক্য — সহীহ মুসলিম ২১৩৭। নির্দিষ্ট সংখ্যা নেই।",
            source = "Sahih Muslim 2137",
        ),
        dhikr(
            id = "afuww",
            name = "Allahumma innaka afuwwun tuhibbul afwa fa'fu anni",
            nameBn = "আল্লাহুম্মা ইন্নাকা আফুউন তুহিব্বুল আফওয়া ফা'ফু আন্নি",
            arabic = "اللّٰهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي",
            pronunciation = "Allahumma innaka afuwwun tuhibbul afwa fa'fu anni",
            pronunciationBn = "আল্লাহুম্মা ইন্নাকা আফুউন তুহিব্বুল আফওয়া ফা'ফু আন্নি",
            translation = "O Allah, You are Most Forgiving, You love to forgive, so forgive me",
            translationBn = "হে আল্লাহ, আপনি ক্ষমাশীল, ক্ষমা ভালোবাসেন, তাই আমাকে ক্ষমা করুন",
            lapTarget = 33,
            note = "The dua of Laylatul Qadr, taught by the Prophet (saw) to Aisha (ra) — Jami at-Tirmidhi 3513, Ibn Majah 3850 (hasan). Adding the word \"karim\" is not established.",
            noteBn = "লাইলাতুল কদরের দুআ, নবি (সাঃ) আয়েশা (রাঃ)-কে শিখিয়েছেন — তিরমিযি ৩৫১৩, ইবনে মাজাহ ৩৮৫০ (হাসান)। “কারীম” শব্দ যোগ প্রমাণিত নয়।",
            source = "Jami at-Tirmidhi 3513",
        ),
        dhikr(
            id = "salli_nabiyyina",
            name = "Allahumma salli wa sallim ala nabiyyina Muhammad",
            nameBn = "আল্লাহুম্মা সাল্লি ওয়া সাল্লিম আলা নাবিয়্যিনা মুহাম্মাদ",
            arabic = "اللّٰهُمَّ صَلِّ وَسَلِّمْ عَلَىٰ نَبِيِّنَا مُحَمَّدٍ",
            pronunciation = "Allahumma salli wa sallim ala nabiyyina Muhammad",
            pronunciationBn = "আল্লাহুম্মা সাল্লি ওয়া সাল্লিম আলা নাবিয়্যিনা মুহাম্মাদ",
            translation = "O Allah, send blessings and peace upon our Prophet Muhammad",
            translationBn = "হে আল্লাহ, আমাদের নবি মুহাম্মাদের প্রতি রহমত ও শান্তি বর্ষণ করুন",
            lapTarget = 33,
            note = "A general salawat; the command to send blessings on the Prophet (saw) is in Quran 33:56.",
            noteBn = "সাধারণ দরূদ; নবি (সাঃ)-এর প্রতি সালাত পাঠের আদেশ কুরআন ৩৩:৫৬-এ।",
            source = "Quran 33:56",
        ),
        dhikr(
            id = "musa_faqir",
            name = "Rabbi inni lima anzalta ilayya min khayrin faqir",
            nameBn = "রব্বি ইন্নি লিমা আনযালতা ইলাইয়া মিন খাইরিন ফাকির",
            arabic = "رَبِّ إِنِّي لِمَا أَنْزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ",
            pronunciation = "Rabbi inni lima anzalta ilayya min khayrin faqir",
            pronunciationBn = "রব্বি ইন্নি লিমা আনযালতা ইলাইয়া মিন খাইরিন ফাকির",
            translation = "My Lord, I am in need of whatever good You send down to me",
            translationBn = "হে আমার রব, আপনি আমার প্রতি যে কল্যাণ নাযিল করবেন আমি তার মুখাপেক্ষী",
            lapTarget = 33,
            note = "Quran 28:24 — the dua of Musa (as) at Madyan.",
            noteBn = "কুরআন ২৮:২৪ — মাদইয়ানে মুসা (আঃ)-এর দুআ।",
            source = "Quran 28:24",
        ),
        dhikr(
            id = "ism_azam",
            name = "Dua with Allah's Greatest Name",
            nameBn = "আল্লাহর ইসমে আযম দিয়ে দুআ",
            arabic = "اللّٰهُمَّ إِنِّي أَسْأَلُكَ بِأَنِّي أَشْهَدُ أَنَّكَ أَنْتَ اللّٰهُ لَا إِلَٰهَ إِلَّا أَنْتَ الْأَحَدُ الصَّمَدُ الَّذِي لَمْ يَلِدْ وَلَمْ يُولَدْ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ",
            pronunciation = "Allahumma inni as'aluka bi anni ash-hadu annaka antallahu la ilaha illa antal ahadus samad alladhi lam yalid wa lam yulad wa lam yakun lahu kufuwan ahad",
            pronunciationBn = "আল্লাহুম্মা ইন্নি আসআলুকা বিআন্নি আশহাদু আন্নাকা আনতাল্লাহু লা ইলাহা ইল্লা আনতাল আহাদুস সামাদু আল্লাযি লাম ইয়ালিদ ওয়া লাম ইউলাদ ওয়া লাম ইয়াকুল্লাহু কুফুওয়ান আহাদ",
            translation = "O Allah, I ask You by my testimony that You are Allah, there is no god but You, the One, the Eternal Refuge, who neither begets nor is born, and there is none comparable to Him",
            translationBn = "হে আল্লাহ, আমি আপনার কাছে চাই এই সাক্ষ্যের অসিলায় যে আপনিই আল্লাহ, আপনি ছাড়া কোনো উপাস্য নেই, এক, অমুখাপেক্ষী, যিনি জন্ম দেননি ও জন্মগ্রহণ করেননি, তাঁর সমকক্ষ কেউ নেই",
            lapTarget = 33,
            note = "A dua by Allah's Greatest Name — the Prophet (saw) said whoever asks by this name is given, and whoever calls by it is answered. Sunan Abi Dawud 1493, Jami at-Tirmidhi 3475 (sahih).",
            noteBn = "আল্লাহর ইসমে আযম দিয়ে দুআ — নবি (সাঃ) বলেছেন এই নামে চাইলে দেওয়া হয়, ডাকলে সাড়া দেওয়া হয়। আবু দাউদ ১৪৯৩, তিরমিযি ৩৪৭৫ (সহীহ)।",
            source = "Sunan Abi Dawud 1493",
        ),
        dhikr(
            id = "hasbiyallah_arsh",
            name = "Hasbiyallahu la ilaha illa huwa alayhi tawakkaltu",
            nameBn = "হাসবিয়াল্লাহু লা ইলাহা ইল্লা হুয়া আলাইহি তাওয়াক্কালতু",
            arabic = "حَسْبِيَ اللّٰهُ لَا إِلَٰهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
            pronunciation = "Hasbiyallahu la ilaha illa huwa alayhi tawakkaltu wa huwa rabbul arshil azim",
            pronunciationBn = "হাসবিয়াল্লাহু লা ইলাহা ইল্লা হুয়া আলাইহি তাওয়াক্কালতু ওয়া হুয়া রব্বুল আরশিল আযীম",
            translation = "Allah is sufficient for me; there is no god but Him; in Him I put my trust; He is the Lord of the Mighty Throne",
            translationBn = "আল্লাহই আমার জন্য যথেষ্ট, তিনি ছাড়া কোনো উপাস্য নেই, তাঁর ওপরই ভরসা করলাম, তিনি মহান আরশের রব",
            lapTarget = 7,
            note = "Part of Quran 9:129. Said 7 times morning and evening, Allah suffices him against the worries of this world and the next — Sunan Abi Dawud 5081 (hasan/sahih isnad). Sunnah count is 7.",
            noteBn = "কুরআন ৯:১২৯-এর অংশ। সকালে ও সন্ধ্যায় ৭ বার পড়লে আল্লাহ দুনিয়া-আখিরাতের চিন্তা থেকে যথেষ্ট হন — আবু দাউদ ৫০৮১ (হাসান/সহীহ ইসনাদ)। সুন্নাহ সংখ্যা ৭।",
            source = "Sunan Abi Dawud 5081",
        ),
        dhikr(
            id = "maghfirli",
            name = "Allahummaghfirli",
            nameBn = "আল্লাহুম্মাগফিরলি",
            arabic = "اللّٰهُمَّ اغْفِرْ لِي",
            pronunciation = "Allahummaghfirli",
            pronunciationBn = "আল্লাহুম্মাগফিরলি",
            translation = "O Allah, forgive me",
            translationBn = "হে আল্লাহ, আমাকে ক্ষমা করুন",
            lapTarget = 33,
            note = "A short istighfar; the Prophet (saw) said it many times, in sujud and elsewhere.",
            noteBn = "সংক্ষিপ্ত ইস্তিগফার; নবি (সাঃ) সিজদায় ও অন্যত্র বহুবার পড়তেন।",
            source = null,
        ),
        dhikr(
            id = "parents_rahmah",
            name = "Rabbir hamhuma kama rabbayani sagira",
            nameBn = "রব্বির হামহুমা কামা রব্বায়ানি সাগীরা",
            arabic = "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
            pronunciation = "Rabbir hamhuma kama rabbayani sagira",
            pronunciationBn = "রব্বির হামহুমা কামা রব্বায়ানি সাগীরা",
            translation = "My Lord, have mercy upon them as they raised me when I was small",
            translationBn = "হে আমার রব, পিতা-মাতার প্রতি দয়া করুন যেভাবে তারা আমাকে ছোটবেলায় লালন করেছেন",
            lapTarget = 33,
            note = "Quran 17:24 — a dua for one's parents.",
            noteBn = "কুরআন ১৭:২৪ — পিতা-মাতার জন্য দুআ।",
            source = "Quran 17:24",
        ),
        dhikr(
            id = "jannah_nar",
            name = "Allahumma inni as'alukal jannata wa a'udhu bika minan nar",
            nameBn = "আল্লাহুম্মা ইন্নি আসআলুকাল জান্নাতা ওয়া আউযু বিকা মিনান নার",
            arabic = "اللّٰهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ وَأَعُوذُ بِكَ مِنَ النَّارِ",
            pronunciation = "Allahumma inni as'alukal jannata wa a'udhu bika minan nar",
            pronunciationBn = "আল্লাহুম্মা ইন্নি আসআলুকাল জান্নাতা ওয়া আউযু বিকা মিনান নার",
            translation = "O Allah, I ask You for Paradise and seek refuge in You from the Fire",
            translationBn = "হে আল্লাহ, আমি আপনার কাছে জান্নাত চাই এবং জাহান্নাম থেকে আশ্রয় চাই",
            lapTarget = 3,
            note = "Asked 3 times for Paradise, it says \"admit him\"; refuge sought 3 times from the Fire, it says \"protect him\" — Jami at-Tirmidhi 2572, Ibn Majah 3846. Sunnah count is 3.",
            noteBn = "৩ বার চাইলে জান্নাত বলে “তাকে প্রবেশ করাও”, ৩ বার আশ্রয় চাইলে জাহান্নাম বলে “তাকে রক্ষা করো” — তিরমিযি ২৫৭২, ইবনে মাজাহ ৩৮৪৬। সুন্নাহ সংখ্যা ৩।",
            source = "Jami at-Tirmidhi 2572",
        ),
        dhikr(
            id = "istighfar_qayyum",
            name = "Astaghfirullahal azimalladhi la ilaha illa huwal hayyul qayyum wa atubu ilayh",
            nameBn = "আস্তাগফিরুল্লাহাল আযীমাল্লাযি লা ইলাহা ইল্লা হুয়াল হাইয়্যুল কাইয়্যূমু ওয়া আতুবু ইলাইহি",
            arabic = "أَسْتَغْفِرُ اللّٰهَ الْعَظِيمَ الَّذِي لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
            pronunciation = "Astaghfirullahal azimalladhi la ilaha illa huwal hayyul qayyum wa atubu ilayh",
            pronunciationBn = "আস্তাগফিরুল্লাহাল আযীমাল্লাযি লা ইলাহা ইল্লা হুয়াল হাইয়্যুল কাইয়্যূমু ওয়া আতুবু ইলাইহি",
            translation = "I seek forgiveness of Allah the Mighty, there is no god but Him, the Ever-Living, the Sustainer, and I turn to Him in repentance",
            translationBn = "আমি ক্ষমা চাই মহান আল্লাহর কাছে, যিনি ছাড়া কোনো উপাস্য নেই, চিরঞ্জীব, সর্বসত্তার ধারক, এবং তাঁর কাছেই তওবা করি",
            lapTarget = 33,
            note = "Whoever says it is forgiven, even if he fled from the battlefield — Sunan Abi Dawud 1517, Jami at-Tirmidhi 3577 (Hakim: sahih). No fixed count.",
            noteBn = "এটি পড়লে গুনাহ মাফ হয় যদিও সে যুদ্ধক্ষেত্র থেকে পালিয়ে থাকে — আবু দাউদ ১৫১৭, তিরমিযি ৩৫৭৭ (হাকিম: সহীহ)। নির্দিষ্ট সংখ্যা নেই।",
            source = "Sunan Abi Dawud 1517",
        ),
        dhikr(
            id = "ya_hayyu_astaghith",
            name = "Ya Hayyu ya Qayyum bi rahmatika astaghith",
            nameBn = "ইয়া হাইয়্যু ইয়া কাইয়্যূমু বিরাহমাতিকা আসতাগীছু",
            arabic = "يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ",
            pronunciation = "Ya Hayyu ya Qayyum bi rahmatika astaghith",
            pronunciationBn = "ইয়া হাইয়্যু ইয়া কাইয়্যূমু বিরাহমাতিকা আসতাগীছু",
            translation = "O Ever-Living, O Sustainer, by Your mercy I seek relief",
            translationBn = "হে চিরঞ্জীব, হে সর্বসত্তার ধারক, আপনার রহমতের অসিলায় সাহায্য প্রার্থনা করি",
            lapTarget = 33,
            note = "When something distressed the Prophet (saw), he would say it — Jami at-Tirmidhi 3524 (hasan isnad; Albani/Mundhiri).",
            noteBn = "কোনো বিষয় নবি (সাঃ)-কে পীড়া দিলে তিনি এটি পড়তেন — তিরমিযি ৩৫২৪ (হাসান ইসনাদ; আলবানি/মুনযিরি)।",
            source = "Jami at-Tirmidhi 3524",
        ),
        dhikr(
            id = "huda_tuqa",
            name = "Allahumma inni as'alukal huda wat tuqa wal afafa wal ghina",
            nameBn = "আল্লাহুম্মা ইন্নি আসআলুকাল হুদা ওয়াত তুকা ওয়াল আফাফা ওয়াল গিনা",
            arabic = "اللّٰهُمَّ إِنِّي أَسْأَلُكَ الْهُدَىٰ وَالتُّقَىٰ وَالْعَفَافَ وَالْغِنَىٰ",
            pronunciation = "Allahumma inni as'alukal huda wat tuqa wal afafa wal ghina",
            pronunciationBn = "আল্লাহুম্মা ইন্নি আসআলুকাল হুদা ওয়াত তুকা ওয়াল আফাফা ওয়াল গিনা",
            translation = "O Allah, I ask You for guidance, piety, chastity and self-sufficiency",
            translationBn = "হে আল্লাহ, আমি আপনার কাছে চাই হেদায়েত, তাকওয়া, পবিত্রতা ও অভাবমুক্তি",
            lapTarget = 33,
            note = "A dua of the Prophet (saw), narrated by Ibn Mas'ud (ra) — Sahih Muslim 2721.",
            noteBn = "নবি (সাঃ)-এর দুআ, ইবনে মাসউদ (রাঃ) বর্ণিত — সহীহ মুসলিম ২৭২১।",
            source = "Sahih Muslim 2721",
        ),
        dhikr(
            id = "muqallib_qulub",
            name = "Ya muqallibal qulubi thabbit qalbi ala dinik",
            nameBn = "ইয়া মুকাল্লিবাল কুলুবি ছাব্বিত কালবি আলা দীনিকা",
            arabic = "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَىٰ دِينِكَ",
            pronunciation = "Ya muqallibal qulubi thabbit qalbi ala dinik",
            pronunciationBn = "ইয়া মুকাল্লিবাল কুলুবি ছাব্বিত কালবি আলা দীনিকা",
            translation = "O Turner of hearts, keep my heart firm upon Your religion",
            translationBn = "হে অন্তরসমূহের পরিবর্তনকারী, আমার অন্তরকে আপনার দ্বীনের ওপর অবিচল রাখুন",
            lapTarget = 33,
            note = "The Prophet (saw) said it often — Jami at-Tirmidhi 2140 (hasan).",
            noteBn = "নবি (সাঃ) অধিক পড়তেন — তিরমিযি ২১৪০ (হাসান)।",
            source = "Jami at-Tirmidhi 2140",
        ),
        dhikr(
            id = "hamm_hazan",
            name = "Allahumma inni a'udhu bika minal hammi wal hazan",
            nameBn = "আল্লাহুম্মা ইন্নি আউযু বিকা মিনাল হাম্মি ওয়াল হাযান",
            arabic = "اللّٰهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ",
            pronunciation = "Allahumma inni a'udhu bika minal hammi wal hazan",
            pronunciationBn = "আল্লাহুম্মা ইন্নি আউযু বিকা মিনাল হাম্মি ওয়াল হাযান",
            translation = "O Allah, I seek refuge in You from anxiety and grief",
            translationBn = "হে আল্লাহ, আমি দুশ্চিন্তা ও দুঃখ থেকে আপনার আশ্রয় চাই",
            lapTarget = 33,
            note = "Full dua: \"…wal ajzi wal kasal, wal jubni wal bukhl, wa dala'id dayn wa ghalabatir rijal\" — Sahih al-Bukhari 6369.",
            noteBn = "পূর্ণ দুআ: “…ওয়াল আজযি ওয়াল কাসাল, ওয়াল জুবনি ওয়াল বুখল, ওয়া দালাইদ দাইন ওয়া গালাবাতির রিজাল” — সহীহ বুখারি ৬৩৬৯।",
            source = "Sahih al-Bukhari 6369",
        ),
        dhikr(
            id = "yassir_la_tuassir",
            name = "Allahumma yassir wa la tu'assir",
            nameBn = "আল্লাহুম্মা ইয়াসসির ওয়ালা তুআসসির",
            arabic = "اللّٰهُمَّ يَسِّرْ وَلَا تُعَسِّرْ",
            pronunciation = "Allahumma yassir wa la tu'assir",
            pronunciationBn = "আল্লাহুম্মা ইয়াসসির ওয়ালা তুআসসির",
            translation = "O Allah, make it easy and do not make it difficult",
            translationBn = "হে আল্লাহ, সহজ করুন, কঠিন করবেন না",
            lapTarget = 33,
            note = "Adapted as a dua from the hadith \"Yassiru wa la tu'assiru\" (Bukhari 69); not found in exactly this form in the six books. A valid general dua.",
            noteBn = "হাদিসের বাণী “ইয়াসসিরু ওয়ালা তুআসসিরু” (বুখারি ৬৯) থেকে গৃহীত দুআ-রূপ; হুবহু এই রূপে ছয় গ্রন্থে নেই। বৈধ সাধারণ দুআ।",
            source = "Sahih al-Bukhari 69",
        ),
        dhikr(
            id = "nuh_maghlub",
            name = "Rabbi inni maghlubun fantasir",
            nameBn = "রব্বি ইন্নি মাগলুবুন ফানতাসির",
            arabic = "رَبِّ إِنِّي مَغْلُوبٌ فَانْتَصِرْ",
            pronunciation = "Rabbi inni maghlubun fantasir",
            pronunciationBn = "রব্বি ইন্নি মাগলুবুন ফানতাসির",
            translation = "My Lord, I am overpowered, so help me",
            translationBn = "হে আমার রব, আমি পরাভূত, তাই সাহায্য করুন",
            lapTarget = 100,
            note = "Quran 54:10 — the dua of Nuh (as). In recitation \"anni\", as a dua \"inni\".",
            noteBn = "কুরআন ৫৪:১০ — নূহ (আঃ)-এর দুআ। তিলাওয়াতে “আন্নি”, দুআ হিসেবে “ইন্নি”।",
            source = "Quran 54:10",
        ),
        dhikr(
            id = "short_salawat",
            name = "Sallallahu alaihi wa sallam",
            nameBn = "সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম",
            arabic = "صَلَّى اللّٰهُ عَلَيْهِ وَسَلَّمَ",
            pronunciation = "Sallallahu alaihi wa sallam",
            pronunciationBn = "সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম",
            translation = "May Allah send blessings and peace upon him",
            translationBn = "আল্লাহ তাঁর ওপর রহমত ও শান্তি বর্ষণ করুন",
            lapTarget = 33,
            note = "A brief salawat on mentioning the Prophet's (saw) name.",
            noteBn = "নবি (সাঃ)-এর নাম উল্লেখে সংক্ষিপ্ত সালাত।",
            source = null,
        ),
        dhikr(
            id = "rabbighfir_tawwab",
            name = "Rabbighfir li wa tub alayya innaka antat tawwabur rahim",
            nameBn = "রব্বিগফির লি ওয়া তুব আলাইয়া ইন্নাকা আনতাত তাওয়াবুর রাহীম",
            arabic = "رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ",
            pronunciation = "Rabbighfir li wa tub alayya innaka antat tawwabur rahim",
            pronunciationBn = "রব্বিগফির লি ওয়া তুব আলাইয়া ইন্নাকা আনতাত তাওয়াবুর রাহীম",
            translation = "My Lord, forgive me and accept my repentance; indeed You are the Accepter of repentance, the Merciful",
            translationBn = "হে আমার রব, আমাকে ক্ষমা করুন ও আমার তওবা কবুল করুন, নিশ্চয়ই আপনি তওবা কবুলকারী পরম দয়ালু",
            lapTarget = 100,
            note = "Ibn Umar (ra): the Prophet (saw) would say it 100 times in a single sitting — Sunan Abi Dawud 1516, Jami at-Tirmidhi 3434 (sahih). Sunnah count is 100.",
            noteBn = "ইবনে উমার (রাঃ): নবি (সাঃ) এক বৈঠকে ১০০ বার এটি পড়তেন — আবু দাউদ ১৫১৬, তিরমিযি ৩৪৩৪ (সহীহ)। সুন্নাহ সংখ্যা ১০০।",
            source = "Jami at-Tirmidhi 3434",
        ),
        dhikr(
            id = "adada_khalqih",
            name = "Subhanallahi wa bihamdihi adada khalqih",
            nameBn = "সুবহানাল্লাহি ওয়া বিহামদিহি আদাদা খালকিহি",
            arabic = "سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ عَدَدَ خَلْقِهِ وَرِضَا نَفْسِهِ وَزِنَةَ عَرْشِهِ وَمِدَادَ كَلِمَاتِهِ",
            pronunciation = "Subhanallahi wa bihamdihi adada khalqih wa rida nafsih wa zinata arshih wa midada kalimatih",
            pronunciationBn = "সুবহানাল্লাহি ওয়া বিহামদিহি আদাদা খালকিহি ওয়া রিদা নাফসিহি ওয়া যিনাতা আরশিহি ওয়া মিদাদা কালিমাতিহি",
            translation = "Glory and praise be to Allah, as many as His creation, as pleases Him, as the weight of His Throne and the ink of His words",
            translationBn = "আল্লাহ পবিত্র ও তাঁরই প্রশংসা—তাঁর সৃষ্টির সংখ্যা, তাঁর সন্তুষ্টি, তাঁর আরশের ওজন ও তাঁর বাণীসমূহের কালি পরিমাণ",
            lapTarget = 3,
            note = "Taught by the Prophet (saw) to Juwayriyah (ra); said 3 times it outweighs all the dhikr said since morning — Sahih Muslim 2726. Sunnah count is 3; the full form is given.",
            noteBn = "জুওয়াইরিয়া (রাঃ)-কে নবি (সাঃ) শিখিয়েছেন, ৩ বার পড়লে সকাল থেকে পড়া সব যিকরের চেয়ে ভারী — সহীহ মুসলিম ২৭২৬। সুন্নাহ সংখ্যা ৩; পূর্ণ রূপটি দেওয়া হলো।",
            source = "Sahih Muslim 2726",
        ),
        dhikr(
            id = "kfini_halalik",
            name = "Allahumma-kfini bi halalika an haramik",
            nameBn = "আল্লাহুম্মাকফিনি বিহালালিকা আন হারামিকা",
            arabic = "اللّٰهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ",
            pronunciation = "Allahumma-kfini bi halalika an haramik wa aghnini bi fadlika amman siwak",
            pronunciationBn = "আল্লাহুম্মাকফিনি বিহালালিকা আন হারামিকা ওয়া আগনিনি বিফাদলিকা আম্মান সিওয়াক",
            translation = "O Allah, suffice me with what You have made lawful against what You have forbidden, and make me independent of all besides You by Your grace",
            translationBn = "হে আল্লাহ, আপনার হালাল দিয়ে আমাকে হারাম থেকে মুক্ত রাখুন এবং আপনার অনুগ্রহে অন্য সবার থেকে অমুখাপেক্ষী করুন",
            lapTarget = 33,
            note = "The Prophet (saw) taught it to Ali (ra) for clearing debt — Jami at-Tirmidhi 3563 (hasan).",
            noteBn = "নবি (সাঃ) আলী (রাঃ)-কে ঋণমুক্তির জন্য শিখিয়েছেন — তিরমিযি ৩৫৬৩ (হাসান)।",
            source = "Jami at-Tirmidhi 3563",
        ),
        dhikr(
            id = "sharh_sadr",
            name = "Rabbi-shrah li sadri wa yassir li amri",
            nameBn = "রব্বিশরাহ লি সাদরি ওয়া ইয়াসসির লি আমরি",
            arabic = "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي وَاحْلُلْ عُقْدَةً مِنْ لِسَانِي يَفْقَهُوا قَوْلِي",
            pronunciation = "Rabbi-shrah li sadri wa yassir li amri wahlul uqdatan min lisani yafqahu qawli",
            pronunciationBn = "রব্বিশরাহ লি সাদরি ওয়া ইয়াসসির লি আমরি ওয়াহলুল উকদাতান মিন লিসানি ইয়াফকাহু কাওলি",
            translation = "My Lord, expand my chest, ease my task, and untie the knot from my tongue so they understand my speech",
            translationBn = "হে আমার রব, আমার বক্ষ প্রশস্ত করুন, কাজ সহজ করুন এবং জিহ্বার জড়তা দূর করুন যাতে তারা আমার কথা বোঝে",
            lapTarget = 33,
            note = "Quran 20:25-28 — the dua of Musa (as) at Mount Tur.",
            noteBn = "কুরআন ২০:২৫-২৮ — তূর পাহাড়ে মুসা (আঃ)-এর দুআ।",
            source = "Quran 20:25-28",
        ),
        dhikr(
            id = "fath_mubin",
            name = "Inna fatahna laka fathan mubina",
            nameBn = "ইন্না ফাতাহনা লাকা ফাতহাম মুবীনা",
            arabic = "إِنَّا فَتَحْنَا لَكَ فَتْحًا مُبِينًا",
            pronunciation = "Inna fatahna laka fathan mubina",
            pronunciationBn = "ইন্না ফাতাহনা লাকা ফাতহাম মুবীনা",
            translation = "Indeed, We have given you a clear conquest",
            translationBn = "নিশ্চয়ই আমি আপনাকে সুস্পষ্ট বিজয় দান করেছি",
            lapTarget = 33,
            note = "Quran 48:1 — the first verse of Surah al-Fath.",
            noteBn = "কুরআন ৪৮:১ — সূরা আল-ফাতহের প্রথম আয়াত।",
            source = "Quran 48:1",
        ),
        dhikr(
            id = "ilm_nafi",
            name = "Allahumma inni as'aluka ilman nafi'an",
            nameBn = "আল্লাহুম্মা ইন্নি আসআলুকা ইলমান নাফিআন",
            arabic = "اللّٰهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلًا مُتَقَبَّلًا",
            pronunciation = "Allahumma inni as'aluka ilman nafi'an wa rizqan tayyiban wa amalan mutaqabbala",
            pronunciationBn = "আল্লাহুম্মা ইন্নি আসআলুকা ইলমান নাফিআন ওয়া রিযকান তাইয়্যিবান ওয়া আমালান মুতাকাব্বালান",
            translation = "O Allah, I ask You for beneficial knowledge, wholesome provision and accepted deeds",
            translationBn = "হে আল্লাহ, আমি আপনার কাছে চাই উপকারী জ্ঞান, পবিত্র রিযিক ও কবুলযোগ্য আমল",
            lapTarget = 100,
            note = "The Prophet (saw) would say it after Fajr, narrated by Umm Salamah (ra) — Sunan Ibn Majah 925 (sahih). No fixed count.",
            noteBn = "নবি (সাঃ) ফজরের পর পড়তেন, উম্মে সালামা (রাঃ) বর্ণিত — ইবনে মাজাহ ৯২৫ (সহীহ)। নির্দিষ্ট সংখ্যা নেই।",
            source = "Sunan Ibn Majah 925",
        ),
        dhikr(
            id = "nafs_mutmainnah",
            name = "Allahumma inni as'aluka nafsan bika mutma'innah",
            nameBn = "আল্লাহুম্মা ইন্নি আসআলুকা নাফসান বিকা মুতমাইন্নাতান",
            arabic = "اللّٰهُمَّ إِنِّي أَسْأَلُكَ نَفْسًا بِكَ مُطْمَئِنَّةً تُؤْمِنُ بِلِقَائِكَ وَتَرْضَىٰ بِقَضَائِكَ وَتَقْنَعُ بِعَطَائِكَ",
            pronunciation = "Allahumma inni as'aluka nafsan bika mutma'innah tu'minu bi liqa'ik wa tarda bi qada'ik wa taqna'u bi ata'ik",
            pronunciationBn = "আল্লাহুম্মা ইন্নি আসআলুকা নাফসান বিকা মুতমাইন্নাতান তু'মিনু বিলিকা'ইকা ওয়া তারদা বিকাদা'ইকা ওয়া তাকনাউ বিআতা'ইকা",
            translation = "O Allah, I ask You for a soul at peace with You, believing in meeting You, pleased with Your decree and content with Your provision",
            translationBn = "হে আল্লাহ, আমি আপনার কাছে চাই এমন প্রশান্ত আত্মা যা আপনার সাক্ষাতে বিশ্বাস রাখে, আপনার ফয়সালায় সন্তুষ্ট ও আপনার দানে পরিতৃপ্ত থাকে",
            lapTarget = 33,
            note = "Taught by the Prophet (saw) to a man, narrated by Abu Umamah (ra) — Tabarani; Ibn Hibban graded it sahih.",
            noteBn = "নবি (সাঃ) এক ব্যক্তিকে শিখিয়েছেন, আবু উমামা (রাঃ) বর্ণিত — তাবারানি; ইবনে হিব্বান সহীহ বলেছেন।",
            source = "al-Mu'jam al-Kabir (Tabarani)",
        ),
        dhikr(
            id = "istighfar_atubu",
            name = "Astaghfirullaha wa atubu ilayh",
            nameBn = "আস্তাগফিরুল্লাহা ওয়া আতুবু ইলাইহি",
            arabic = "أَسْتَغْفِرُ اللّٰهَ وَأَتُوبُ إِلَيْهِ",
            pronunciation = "Astaghfirullaha wa atubu ilayh",
            pronunciationBn = "আস্তাগফিরুল্লাহা ওয়া আতুবু ইলাইহি",
            translation = "I seek Allah's forgiveness and turn to Him in repentance",
            translationBn = "আমি আল্লাহর কাছে ক্ষমা চাই এবং তাঁর কাছে তওবা করি",
            lapTarget = 100,
            note = "The Prophet (saw) sought forgiveness 100 times a day (in another narration, more than 70) — Sahih Muslim 2702, Sahih al-Bukhari 6307. Sunnah count is 100.",
            noteBn = "নবি (সাঃ) দিনে ১০০ বার (অন্য বর্ণনায় ৭০ বারের বেশি) ইস্তিগফার করতেন — সহীহ মুসলিম ২৭০২, বুখারি ৬৩০৭। সুন্নাহ সংখ্যা ১০০।",
            source = "Sahih Muslim 2702",
        ),
        dhikr(
            id = "maridtu_yashfin",
            name = "Wa idha maridtu fahuwa yashfin",
            nameBn = "ওয়া ইযা মারিদতু ফাহুয়া ইয়াশফীন",
            arabic = "وَإِذَا مَرِضْتُ فَهُوَ يَشْفِينِ",
            pronunciation = "Wa idha maridtu fahuwa yashfin",
            pronunciationBn = "ওয়া ইযা মারিদতু ফাহুয়া ইয়াশফীন",
            translation = "And when I am ill, it is He who cures me",
            translationBn = "আর যখন আমি অসুস্থ হই তখন তিনিই আমাকে সুস্থ করেন",
            lapTarget = 33,
            note = "Quran 26:80 — the words of Ibrahim (as); one of the six verses of healing.",
            noteBn = "কুরআন ২৬:৮০ — ইবরাহিম (আঃ)-এর বাণী; শিফার ছয় আয়াতের একটি।",
            source = "Quran 26:80",
        ),

        // --- Batch 2 (retained): the four non-situational praise/dua items
        // kept when the occasion-bound adhkar were retired (see retiredBuiltInIds).
        dhikr(
            id = "azim_bihamdih",
            name = "Subhanallahil Azim wa bihamdih",
            nameBn = "সুবহানাল্লাহিল আযীম ওয়া বিহামদিহি",
            arabic = "سُبْحَانَ اللّٰهِ الْعَظِيمِ وَبِحَمْدِهِ",
            pronunciation = "Subhanallahil Azim wa bihamdih",
            pronunciationBn = "সুবহানাল্লাহিল আযীম ওয়া বিহামদিহি",
            translation = "Glory be to Allah the Most Great, and praise be to Him",
            translationBn = "মহান আল্লাহ পবিত্র এবং তাঁরই প্রশংসা",
            lapTarget = 100,
            note = "Said once, a date-palm is planted for him in Paradise — Jami at-Tirmidhi 3464 (sahih). No fixed count.",
            noteBn = "একবার পড়লে জান্নাতে একটি খেজুর গাছ রোপণ করা হয় — তিরমিযি ৩৪৬৪ (সহীহ)। নির্দিষ্ট সংখ্যা নেই।",
            source = "Jami at-Tirmidhi 3464",
        ),
        dhikr(
            id = "ajz_kasal",
            name = "A'udhu bika minal ajzi wal kasal",
            nameBn = "আল্লাহুম্মা ইন্নি আউযু বিকা মিনাল আজযি ওয়াল কাসাল",
            arabic = "اللّٰهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ، وَالْجُبْنِ وَالْهَرَمِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، وَمِنْ فِتْنَةِ الْمَحْيَا وَالْمَمَاتِ",
            pronunciation = "Allahumma inni a'udhu bika minal ajzi wal kasal, wal jubni wal harami wal bukhl, wa a'udhu bika min adhabil qabr, wa min fitnatil mahya wal mamat",
            pronunciationBn = "আল্লাহুম্মা ইন্নি আউযু বিকা মিনাল আজযি ওয়াল কাসালি, ওয়াল জুবনি ওয়াল হারামি ওয়াল বুখলি, ওয়া আউযু বিকা মিন আযাবিল ক্বাবরি, ওয়া মিন ফিতনাতিল মাহইয়া ওয়াল মামাতি",
            translation = "O Allah, I seek refuge in You from incapacity, laziness, cowardice, decrepitude and miserliness, and from the punishment of the grave and the trial of life and death",
            translationBn = "হে আল্লাহ, অক্ষমতা, অলসতা, ভীরুতা, অতি-বার্ধক্য ও কৃপণতা থেকে এবং কবরের আযাব ও জীবন-মৃত্যুর ফিতনা থেকে আপনার আশ্রয় চাই",
            lapTarget = 1,
            note = "A regular dua — Sahih al-Bukhari 6367, Sahih Muslim 2706.",
            noteBn = "নিয়মিত দোয়া — সহীহ বুখারি ৬৩৬৭, মুসলিম ২৭০৬।",
            source = "Sahih al-Bukhari 6367",
        ),
        dhikr(
            id = "munkarat_akhlaq",
            name = "A'udhu bika min munkaratil akhlaq",
            nameBn = "আল্লাহুম্মা ইন্নি আউযু বিকা মিন মুনকারাতিল আখলাক্বি",
            arabic = "اللّٰهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ مُنْكَرَاتِ الْأَخْلَاقِ وَالْأَعْمَالِ وَالْأَهْوَاءِ",
            pronunciation = "Allahumma inni a'udhu bika min munkaratil akhlaqi wal a'mali wal ahwa'",
            pronunciationBn = "আল্লাহুম্মা ইন্নি আউযু বিকা মিন মুনকারাতিল আখলাক্বি ওয়াল আমালি ওয়াল আহওয়াই",
            translation = "O Allah, I seek refuge in You from evil character, deeds and desires",
            translationBn = "হে আল্লাহ, অসৎ চরিত্র, গর্হিত কাজ ও কুপ্রবৃত্তি থেকে আপনার আশ্রয় চাই",
            lapTarget = 33,
            note = "A general supplication — Jami at-Tirmidhi 3591 (sahih).",
            noteBn = "সাধারণ প্রার্থনা — তিরমিযি ৩৫৯১ (সহীহ)।",
            source = "Jami at-Tirmidhi 3591",
        ),
        dhikr(
            id = "rabbana_atina",
            name = "Rabbana atina fid dunya hasanah",
            nameBn = "রাব্বানা আতিনা ফিদ দুনইয়া হাসানাতান",
            arabic = "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
            pronunciation = "Rabbana atina fid dunya hasanah wa fil akhirati hasanah wa qina adhaban nar",
            pronunciationBn = "রাব্বানা আতিনা ফিদ দুনইয়া হাসানাতান ওয়া ফিল আখিরাতি হাসানাতান ওয়াক্বিনা আযাবান নার",
            translation = "Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire",
            translationBn = "হে আমাদের রব, আমাদের দুনিয়া ও আখিরাতে কল্যাণ দিন এবং জাহান্নামের আযাব থেকে রক্ষা করুন",
            lapTarget = 33,
            note = "Quran 2:201 — the dua the Prophet (saw) made most often; between the Yemeni Corner and the Black Stone during tawaf — Sahih al-Bukhari 4522, Sunan Abi Dawud 1892.",
            noteBn = "কুরআন ২:২০১ — নবিজির সবচেয়ে বেশি পড়া দোয়া; তাওয়াফে রুকনে ইয়ামানী ও হাজারে আসওয়াদের মাঝে — সহীহ বুখারি ৪৫২২, আবু দাউদ ১৮৯২।",
            source = "Quran 2:201; Sahih al-Bukhari 4522",
        ),

        // --- Asma-ul-Husna: the 99 names of Allah ----------------------------
        // Canonical order follows the well-known al-Walid b. Muslim enumeration
        // appended to the hadith of Abu Hurayrah (Jami at-Tirmidhi 3507 / Sunan
        // Ibn Majah 3861) — the list used on virtually every printed poster and
        // app. `translation` carries the English meaning, `translationBn` the
        // Bangla. Each name recites lightly, so lapTarget = 3. The 99 rows live
        // in `asmaUlHusnaList` below and builtInTasbih concatenates them lazily.
    )

    private val asmaUlHusnaList: List<TasbihEntity> = listOf(
        name(1, "Ar-Rahman", "الرَّحْمَٰنُ", "আর-রহমান", "পরম করুণাময়", "The Most Compassionate"),
        name(2, "Ar-Rahim", "الرَّحِيمُ", "আর-রহীম", "পরম দয়ালু", "The Most Merciful"),
        name(3, "Al-Malik", "الْمَلِكُ", "আল-মালিক", "অধিপতি", "The King, the Sovereign"),
        name(4, "Al-Quddus", "الْقُدُّوسُ", "আল-কুদ্দূস", "মহাপবিত্র", "The Most Holy"),
        name(5, "As-Salam", "السَّلَامُ", "আস-সালাম", "শান্তির উৎস", "The Source of Peace"),
        name(6, "Al-Mu'min", "الْمُؤْمِنُ", "আল-মু'মিন", "নিরাপত্তাদাতা", "The Granter of Security"),
        name(7, "Al-Muhaymin", "الْمُهَيْمِنُ", "আল-মুহাইমিন", "রক্ষণাবেক্ষণকারী", "The Guardian, the Overseer"),
        name(8, "Al-Aziz", "الْعَزِيزُ", "আল-আযীয", "মহাপরাক্রমশালী", "The Almighty"),
        name(9, "Al-Jabbar", "الْجَبَّارُ", "আল-জাব্বার", "দুর্নিবার", "The Compeller, the Restorer"),
        name(10, "Al-Mutakabbir", "الْمُتَكَبِّرُ", "আল-মুতাকাব্বির", "মহিমান্বিত", "The Supreme in Greatness"),
        name(11, "Al-Khaliq", "الْخَالِقُ", "আল-খালিক", "সৃষ্টিকর্তা", "The Creator"),
        name(12, "Al-Bari'", "الْبَارِئُ", "আল-বারি", "উদ্ভাবনকারী", "The Originator"),
        name(13, "Al-Musawwir", "الْمُصَوِّرُ", "আল-মুসাউইর", "রূপদানকারী", "The Fashioner"),
        name(14, "Al-Ghaffar", "الْغَفَّارُ", "আল-গাফ্ফার", "পরম ক্ষমাশীল", "The All-Forgiving"),
        name(15, "Al-Qahhar", "الْقَهَّارُ", "আল-কাহহার", "মহাপ্রতাপশালী", "The All-Prevailing"),
        name(16, "Al-Wahhab", "الْوَهَّابُ", "আল-ওয়াহহাব", "মহাদাতা", "The Bestower"),
        name(17, "Ar-Razzaq", "الرَّزَّاقُ", "আর-রাযযাক", "রিযিকদাতা", "The Provider"),
        name(18, "Al-Fattah", "الْفَتَّاحُ", "আল-ফাত্তাহ", "মহাবিজয়দাতা", "The Opener, the Judge"),
        name(19, "Al-Alim", "الْعَلِيمُ", "আল-আলীম", "সর্বজ্ঞ", "The All-Knowing"),
        name(20, "Al-Qabid", "الْقَابِضُ", "আল-কাবিদ", "সংকোচনকারী", "The Withholder"),
        name(21, "Al-Basit", "الْبَاسِطُ", "আল-বাসিত", "প্রসারণকারী", "The Extender"),
        name(22, "Al-Khafid", "الْخَافِضُ", "আল-খাফিদ", "অবনতকারী", "The Reducer"),
        name(23, "Ar-Rafi'", "الرَّافِعُ", "আর-রাফি", "উন্নতকারী", "The Exalter"),
        name(24, "Al-Mu'izz", "الْمُعِزُّ", "আল-মুইয্য", "সম্মানদাতা", "The Honourer"),
        name(25, "Al-Mudhill", "الْمُذِلُّ", "আল-মুযিল্ল", "অপমানকারী", "The Dishonourer"),
        name(26, "As-Sami'", "السَّمِيعُ", "আস-সামী", "সর্বশ্রোতা", "The All-Hearing"),
        name(27, "Al-Basir", "الْبَصِيرُ", "আল-বাসীর", "সর্বদ্রষ্টা", "The All-Seeing"),
        name(28, "Al-Hakam", "الْحَكَمُ", "আল-হাকাম", "বিচারক", "The Judge"),
        name(29, "Al-Adl", "الْعَدْلُ", "আল-আদল", "ন্যায়পরায়ণ", "The Utterly Just"),
        name(30, "Al-Latif", "اللَّطِيفُ", "আল-লাতীফ", "সূক্ষ্মদর্শী", "The Subtle, the Gentle"),
        name(31, "Al-Khabir", "الْخَبِيرُ", "আল-খাবীর", "সম্যক অবগত", "The All-Aware"),
        name(32, "Al-Halim", "الْحَلِيمُ", "আল-হালীম", "পরম সহনশীল", "The Forbearing"),
        name(33, "Al-Azim", "الْعَظِيمُ", "আল-আযীম", "মহান", "The Magnificent"),
        name(34, "Al-Ghafur", "الْغَفُورُ", "আল-গাফূর", "ক্ষমাশীল", "The All-Forgiving"),
        name(35, "Ash-Shakur", "الشَّكُورُ", "আশ-শাকূর", "গুণগ্রাহী", "The Most Appreciative"),
        name(36, "Al-Ali", "الْعَلِيُّ", "আল-আলী", "সুউচ্চ", "The Most High"),
        name(37, "Al-Kabir", "الْكَبِيرُ", "আল-কাবীর", "সর্বাপেক্ষা বড়", "The Most Great"),
        name(38, "Al-Hafiz", "الْحَفِيظُ", "আল-হাফীয", "সংরক্ষণকারী", "The Preserver"),
        name(39, "Al-Muqit", "الْمُقِيتُ", "আল-মুকীত", "আহার্যদাতা", "The Sustainer"),
        name(40, "Al-Hasib", "الْحَسِيبُ", "আল-হাসীব", "হিসাবগ্রহণকারী", "The Reckoner"),
        name(41, "Al-Jalil", "الْجَلِيلُ", "আল-জালীল", "মহিমাময়", "The Majestic"),
        name(42, "Al-Karim", "الْكَرِيمُ", "আল-কারীম", "মহানুভব", "The Most Generous"),
        name(43, "Ar-Raqib", "الرَّقِيبُ", "আর-রাকীব", "পর্যবেক্ষণকারী", "The Watchful"),
        name(44, "Al-Mujib", "الْمُجِيبُ", "আল-মুজীব", "প্রার্থনা কবুলকারী", "The Responsive"),
        name(45, "Al-Wasi'", "الْوَاسِعُ", "আল-ওয়াসি", "সর্বব্যাপী", "The All-Encompassing"),
        name(46, "Al-Hakim", "الْحَكِيمُ", "আল-হাকীম", "প্রজ্ঞাময়", "The All-Wise"),
        name(47, "Al-Wadud", "الْوَدُودُ", "আল-ওয়াদূদ", "পরম প্রেমময়", "The Most Loving"),
        name(48, "Al-Majid", "الْمَجِيدُ", "আল-মাজীদ", "মহাগৌরবান্বিত", "The All-Glorious"),
        name(49, "Al-Ba'ith", "الْبَاعِثُ", "আল-বা'ইছ", "পুনরুত্থানকারী", "The Resurrector"),
        name(50, "Ash-Shahid", "الشَّهِيدُ", "আশ-শাহীদ", "সর্বজ্ঞ সাক্ষী", "The All-Witnessing"),
        name(51, "Al-Haqq", "الْحَقُّ", "আল-হাক্ক", "পরম সত্য", "The Absolute Truth"),
        name(52, "Al-Wakil", "الْوَكِيلُ", "আল-ওয়াকীল", "কর্মবিধায়ক", "The Trustee, the Disposer of Affairs"),
        name(53, "Al-Qawiyy", "الْقَوِيُّ", "আল-কাউইয়্য", "মহাশক্তিধর", "The All-Strong"),
        name(54, "Al-Matin", "الْمَتِينُ", "আল-মাতীন", "সুদৃঢ়", "The Firm, the Steadfast"),
        name(55, "Al-Waliyy", "الْوَلِيُّ", "আল-ওয়ালী", "অভিভাবক বন্ধু", "The Protecting Friend"),
        name(56, "Al-Hamid", "الْحَمِيدُ", "আল-হামীদ", "প্রশংসিত", "The Praiseworthy"),
        name(57, "Al-Muhsi", "الْمُحْصِي", "আল-মুহসী", "পূর্ণ গণনাকারী", "The All-Enumerating"),
        name(58, "Al-Mubdi'", "الْمُبْدِئُ", "আল-মুবদি", "প্রথম সৃষ্টিকারী", "The Originator"),
        name(59, "Al-Mu'id", "الْمُعِيدُ", "আল-মুঈদ", "পুনঃসৃষ্টিকারী", "The Restorer"),
        name(60, "Al-Muhyi", "الْمُحْيِي", "আল-মুহয়ী", "জীবনদাতা", "The Giver of Life"),
        name(61, "Al-Mumit", "الْمُمِيتُ", "আল-মুমীত", "মৃত্যুদাতা", "The Bringer of Death"),
        name(62, "Al-Hayy", "الْحَيُّ", "আল-হাইয়্য", "চিরঞ্জীব", "The Ever-Living"),
        name(63, "Al-Qayyum", "الْقَيُّومُ", "আল-কাইয়্যূম", "স্বয়ংস্থিত সর্বসত্তার ধারক", "The Self-Subsisting Sustainer of all"),
        name(64, "Al-Wajid", "الْوَاجِدُ", "আল-ওয়াজিদ", "অভাবমুক্ত", "The Perceiver, the Finder"),
        name(65, "Al-Majid", "الْمَاجِدُ", "আল-মাজিদ", "মহিমান্বিত", "The Illustrious"),
        name(66, "Al-Wahid", "الْوَاحِدُ", "আল-ওয়াহিদ", "এক", "The One"),
        name(67, "Al-Ahad", "الْأَحَدُ", "আল-আহাদ", "অদ্বিতীয়", "The Indivisible, the Unique"),
        name(68, "As-Samad", "الصَّمَدُ", "আস-সামাদ", "অমুখাপেক্ষী", "The Eternal, the Self-Sufficient"),
        name(69, "Al-Qadir", "الْقَادِرُ", "আল-কাদির", "সর্বশক্তিমান", "The All-Powerful"),
        name(70, "Al-Muqtadir", "الْمُقْتَدِرُ", "আল-মুকতাদির", "প্রবল ক্ষমতাধর", "The All-Determining"),
        name(71, "Al-Muqaddim", "الْمُقَدِّمُ", "আল-মুকাদ্দিম", "অগ্রসরকারী", "The Expediter"),
        name(72, "Al-Mu'akhkhir", "الْمُؤَخِّرُ", "আল-মু'আখখির", "বিলম্বকারী", "The Delayer"),
        name(73, "Al-Awwal", "الْأَوَّلُ", "আল-আউয়াল", "অনাদি", "The First"),
        name(74, "Al-Akhir", "الْآخِرُ", "আল-আখির", "অনন্ত", "The Last"),
        name(75, "Az-Zahir", "الظَّاهِرُ", "আয-যাহির", "প্রকাশ্য", "The Manifest"),
        name(76, "Al-Batin", "الْبَاطِنُ", "আল-বাতিন", "অপ্রকাশ্য", "The Hidden"),
        name(77, "Al-Wali", "الْوَالِي", "আল-ওয়ালী", "সর্বময় কর্তা", "The Governor"),
        name(78, "Al-Muta'ali", "الْمُتَعَالِي", "আল-মুতাআলী", "সর্বোচ্চ মহান", "The Most Exalted"),
        name(79, "Al-Barr", "الْبَرُّ", "আল-বার্র", "কল্যাণকারী", "The Source of All Goodness"),
        name(80, "At-Tawwab", "التَّوَّابُ", "আত-তাওয়াব", "তওবা কবুলকারী", "The Ever-Accepting of Repentance"),
        name(81, "Al-Muntaqim", "الْمُنْتَقِمُ", "আল-মুনতাকিম", "প্রতিশোধ গ্রহণকারী", "The Avenger"),
        name(82, "Al-Afuww", "الْعَفُوُّ", "আল-আফুউ", "পরম মার্জনাকারী", "The Pardoner"),
        name(83, "Ar-Ra'uf", "الرَّءُوفُ", "আর-রাঊফ", "পরম স্নেহশীল", "The Ever-Gentle, the Kind"),
        name(84, "Malik-ul-Mulk", "مَالِكُ الْمُلْكِ", "মালিকুল মুলক", "সমগ্র রাজত্বের অধিপতি", "Master of the Kingdom"),
        name(85, "Dhul-Jalali wal-Ikram", "ذُو الْجَلَالِ وَالْإِكْرَامِ", "যুল জালালি ওয়াল ইকরাম", "মহিমা ও সম্মানের অধিকারী", "Possessor of Majesty and Honour"),
        name(86, "Al-Muqsit", "الْمُقْسِطُ", "আল-মুকসিত", "ন্যায়বিচারক", "The Equitable"),
        name(87, "Al-Jami'", "الْجَامِعُ", "আল-জামি", "একত্রকারী", "The Gatherer"),
        name(88, "Al-Ghani", "الْغَنِيُّ", "আল-গানী", "অভাবমুক্ত ঐশ্বর্যবান", "The Self-Sufficient"),
        name(89, "Al-Mughni", "الْمُغْنِي", "আল-মুগনী", "অভাবমোচনকারী", "The Enricher"),
        name(90, "Al-Mani'", "الْمَانِعُ", "আল-মানি", "প্রতিরোধকারী", "The Withholder, the Preventer"),
        name(91, "Ad-Darr", "الضَّارُّ", "আদ-দার্র", "অনিষ্টের ক্ষমতাধর", "The Distresser"),
        name(92, "An-Nafi'", "النَّافِعُ", "আন-নাফি", "কল্যাণদাতা", "The Bestower of Benefit"),
        name(93, "An-Nur", "النُّورُ", "আন-নূর", "জ্যোতি", "The Light"),
        name(94, "Al-Hadi", "الْهَادِي", "আল-হাদী", "পথপ্রদর্শক", "The Guide"),
        name(95, "Al-Badi'", "الْبَدِيعُ", "আল-বাদী", "অতুলনীয় স্রষ্টা", "The Incomparable Originator"),
        name(96, "Al-Baqi", "الْبَاقِي", "আল-বাকী", "চিরস্থায়ী", "The Ever-Enduring"),
        name(97, "Al-Warith", "الْوَارِثُ", "আল-ওয়ারিছ", "চূড়ান্ত উত্তরাধিকারী", "The Inheritor"),
        name(98, "Ar-Rashid", "الرَّشِيدُ", "আর-রাশীদ", "সঠিক পথের পরিচালক", "The Guide to the Right Path"),
        name(99, "As-Sabur", "الصَّبُورُ", "আস-সাবূর", "পরম ধৈর্যশীল", "The Most Patient"),
    )

    // Presets seed as favorites so they appear on Home out of the box; the user
    // unstars one on the Routines page to remove it from Home.
    val presetRoutines: List<RoutineEntity> = listOf(
        RoutineEntity(id = "morning", name = "Morning Dhikr", nameBn = "সকালের যিকর", isPreset = true, isFavorite = true, createdAt = SEED_TIMESTAMP, updatedAt = SEED_TIMESTAMP),
        RoutineEntity(id = "evening", name = "Evening Dhikr", nameBn = "সন্ধ্যার যিকর", isPreset = true, isFavorite = true, createdAt = SEED_TIMESTAMP, updatedAt = SEED_TIMESTAMP),
        RoutineEntity(id = "after_salah", name = "After Salah", nameBn = "সালাতের পর", isPreset = true, isFavorite = true, createdAt = SEED_TIMESTAMP, updatedAt = SEED_TIMESTAMP),
        RoutineEntity(id = "before_sleep", name = "Before Sleep", nameBn = "ঘুমানোর আগে", isPreset = true, isFavorite = true, createdAt = SEED_TIMESTAMP, updatedAt = SEED_TIMESTAMP),
        RoutineEntity(id = "asma_ul_husna", name = "Asma-ul-Husna", nameBn = "আসমাউল হুসনা", isPreset = true, isFavorite = true, createdAt = SEED_TIMESTAMP, updatedAt = SEED_TIMESTAMP),
    )

    val presetRoutineSteps: List<RoutineStepEntity> by lazy {
        coreRoutineSteps + asmaUlHusnaSteps
    }

    private val coreRoutineSteps: List<RoutineStepEntity> = listOf(
        // Morning Dhikr: SubhanAllah x33, Alhamdulillah x33, AllahuAkbar x34 (matches
        // the prototype's ROUTINES array and design README's own example exactly —
        // design/Dhikr Android App.dc.html's `morning`/`salah` routine definitions)
        RoutineStepEntity(routineId = "morning", tasbihId = "subhan", stepOrder = 0, targetCount = 33),
        RoutineStepEntity(routineId = "morning", tasbihId = "hamd", stepOrder = 1, targetCount = 33),
        RoutineStepEntity(routineId = "morning", tasbihId = "akbar", stepOrder = 2, targetCount = 34),
        // Evening Dhikr: same three, evening framing — no separate evening-specific
        // prototype data exists, so this reuses the same structure as Morning per
        // the plan's own "Evening Dhikr" listing (plan.md §22) which gives no
        // distinct counts of its own.
        RoutineStepEntity(routineId = "evening", tasbihId = "subhan", stepOrder = 0, targetCount = 33),
        RoutineStepEntity(routineId = "evening", tasbihId = "hamd", stepOrder = 1, targetCount = 33),
        RoutineStepEntity(routineId = "evening", tasbihId = "akbar", stepOrder = 2, targetCount = 34),
        // After Salah: matches the prototype's `salah` routine exactly (same 3 steps)
        RoutineStepEntity(routineId = "after_salah", tasbihId = "subhan", stepOrder = 0, targetCount = 33),
        RoutineStepEntity(routineId = "after_salah", tasbihId = "hamd", stepOrder = 1, targetCount = 33),
        RoutineStepEntity(routineId = "after_salah", tasbihId = "akbar", stepOrder = 2, targetCount = 34),
        // Before Sleep: matches the prototype's `sleep` routine exactly —
        // Astaghfirullah x100, Subhanallahi wa bihamdihi x100
        RoutineStepEntity(routineId = "before_sleep", tasbihId = "istighfar", stepOrder = 0, targetCount = 100),
        RoutineStepEntity(routineId = "before_sleep", tasbihId = "bihamdihi", stepOrder = 1, targetCount = 100),
    )

    // Asma-ul-Husna: walk all 99 names in canonical order, 3 recitations each.
    private val asmaUlHusnaSteps: List<RoutineStepEntity> = (1..99).map { n ->
        RoutineStepEntity(
            routineId = "asma_ul_husna",
            tasbihId = "asma_%02d".format(n),
            stepOrder = n - 1,
            targetCount = 3,
        )
    }
}
