package com.dhikr.app.core.database.seed

import com.dhikr.app.core.database.entity.RoutineEntity
import com.dhikr.app.core.database.entity.RoutineStepEntity
import com.dhikr.app.core.database.entity.TasbihEntity

object SeedData {
    private const val SEED_TIMESTAMP = 0L

    // Compact builder for the added dhikr below. Arabic is fully vowelled;
    // `pronunciation` is the Bangla transliteration; `translation` carries the
    // Bangla meaning followed by the English; `note` records source + grade and
    // any note on the recitation count. Counts follow an authentic sunnah figure
    // where a hadith fixes one, otherwise the user-supplied number.
    private fun dhikr(
        id: String,
        name: String,
        arabic: String,
        pronunciation: String,
        translation: String,
        lapTarget: Int,
        note: String = "",
        source: String? = null,
    ) = TasbihEntity(
        id = id,
        name = name,
        arabic = arabic,
        pronunciation = pronunciation,
        translation = translation,
        note = note,
        source = source,
        lapTarget = lapTarget,
        lapCount = 1,
        isFavorite = false,
        isBuiltIn = true,
        createdAt = SEED_TIMESTAMP,
        updatedAt = SEED_TIMESTAMP,
    )

    val builtInTasbih: List<TasbihEntity> = listOf(
        TasbihEntity(
            id = "kursi",
            name = "Ayatul Kursi",
            arabic = "",
            pronunciation = "আল্লাহু লা ইলাহা ইল্লা হুয়াল হাইয়্যুল কইয়্যুমু লা তা খুজুহু সিনাত্যু ওয়ালা নাউম। " +
                "লাহু মা ফিছছামা ওয়াতি ওয়ামা ফিল আরদ। মান যাল্লাযী ইয়াস ফায়ু ইন দাহু ইল্লা বি ইজনিহি ইয়া লামু মা " +
                "বাইনা আইদিহিম ওয়ামা খল ফাহুম ওয়ালা ইউ হিতুনা বিশাই ইম্ মিন ইল্ মিহি ইল্লা বিমা সাআ ওয়াসিয়া " +
                "কুরসিইউ হুস ছামা ওয়াতি ওয়াল আরদ্ ওয়ালা ইয়া উদুহু হিফজুহুমা ওয়াহুয়াল আলিয়্যুল আজিম",
            translation = "",
            lapTarget = 7,
            lapCount = 1,
            isFavorite = true,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "subhan",
            name = "SubhanAllah",
            arabic = "سُبْحَانَ اللّٰه",
            pronunciation = "সুবহানাল্লাহ",
            translation = "Glory be to Allah",
            lapTarget = 33,
            lapCount = 3,
            isFavorite = true,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "hamd",
            name = "Alhamdulillah",
            arabic = "الْحَمْدُ لِلّٰه",
            pronunciation = "আলহামদুলিল্লাহ",
            translation = "All praise is due to Allah",
            lapTarget = 33,
            lapCount = 3,
            isFavorite = true,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "akbar",
            name = "Allahu Akbar",
            arabic = "اللّٰهُ أَكْبَر",
            pronunciation = "আল্লাহু আকবার",
            translation = "Allah is the greatest",
            lapTarget = 34,
            lapCount = 3,
            isFavorite = true,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "istighfar",
            name = "Astaghfirullah",
            arabic = "أَسْتَغْفِرُ اللّٰه",
            pronunciation = "আস্তাগফিরুল্লাহ",
            translation = "I seek forgiveness from Allah",
            lapTarget = 100,
            lapCount = 1,
            isFavorite = false,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "bihamdihi",
            name = "Subhanallahi wa bihamdihi",
            arabic = "سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ",
            pronunciation = "সুবহানাল্লাহি ওয়া বিহামদিহি",
            translation = "Glory be to Allah and praise be to Him",
            lapTarget = 100,
            lapCount = 1,
            isFavorite = false,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),
        TasbihEntity(
            id = "hawla",
            name = "La hawla wa la quwwata illa billah",
            arabic = "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللّٰه",
            pronunciation = "লা হাওলা ওয়ালা কুওয়াতা ইল্লা বিল্লাহ",
            translation = "There is no power nor strength except with Allah",
            lapTarget = 33,
            lapCount = 1,
            isFavorite = false,
            isBuiltIn = true,
            createdAt = SEED_TIMESTAMP,
            updatedAt = SEED_TIMESTAMP,
        ),

        // --- Added dhikr (researched + verified) ------------------------------
        dhikr(
            id = "tahlil",
            name = "La ilaha illallah",
            arabic = "لَا إِلَٰهَ إِلَّا اللّٰهُ",
            pronunciation = "লা ইলাহা ইল্লাল্লাহ",
            translation = "আল্লাহ ছাড়া কোনো সত্য উপাস্য নেই — There is no true god but Allah",
            lapTarget = 100,
            note = "শ্রেষ্ঠ যিকর। “আফযালুয যিকরি লা ইলাহা ইল্লাল্লাহ” — তিরমিযি ৩৩৮৩ (হাসান)।",
            source = "Jami at-Tirmidhi 3383",
        ),
        dhikr(
            id = "bihamdihi_azim",
            name = "Subhanallahi wa bihamdihi, Subhanallahil Azim",
            arabic = "سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ، سُبْحَانَ اللّٰهِ الْعَظِيمِ",
            pronunciation = "সুবহানাল্লাহি ওয়া বিহামদিহি, সুবহানাল্লাহিল আযীম",
            translation = "আল্লাহ পবিত্র ও তাঁরই প্রশংসা, মহান আল্লাহ পবিত্র — Glory and praise be to Allah, glory be to Allah the Most Great",
            lapTarget = 100,
            note = "জিহ্বায় হালকা, মিযানে ভারী, রহমানের কাছে প্রিয় দুই বাক্য — সহীহ বুখারি ৬৪০৬। নির্দিষ্ট সংখ্যা হাদিসে নেই; ১০০ ব্যবহারকারীর পছন্দ।",
            source = "Sahih al-Bukhari 6406",
        ),
        dhikr(
            id = "durood_ali",
            name = "Allahumma salli ala Muhammadin wa ala ali Muhammad",
            arabic = "اللّٰهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ",
            pronunciation = "আল্লাহুম্মা সাল্লি আলা মুহাম্মাদিন ওয়া আলা আলি মুহাম্মাদ",
            translation = "হে আল্লাহ, মুহাম্মাদ ও তাঁর পরিবারের প্রতি রহমত বর্ষণ করুন — O Allah, send blessings upon Muhammad and the family of Muhammad",
            lapTarget = 100,
            note = "দরূদ। সকাল-সন্ধ্যায় ১০ বার পড়লে কিয়ামতে শাফাআত — তাবারানি। নির্দিষ্ট ১০০ সংখ্যা হাদিসে নেই।",
            source = "al-Mu'jam al-Awsat (Tabarani)",
        ),
        dhikr(
            id = "tahlil_wahdahu",
            name = "La ilaha illallahu wahdahu la sharika lah",
            arabic = "لَا إِلَٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
            pronunciation = "লা ইলাহা ইল্লাল্লাহু ওয়াহদাহু লা শারিকা লাহু, লাহুল মুলকু ওয়া লাহুল হামদু ওয়া হুয়া আলা কুল্লি শাইইন কাদীর",
            translation = "আল্লাহ ছাড়া কোনো উপাস্য নেই, তিনি একক, তাঁর কোনো শরিক নেই; রাজত্ব ও প্রশংসা তাঁরই, তিনি সর্বশক্তিমান — There is no god but Allah alone, no partner has He; His is the dominion and the praise, and He is able to do all things",
            lapTarget = 100,
            note = "দিনে ১০০ বার = ১০ জন দাস মুক্তির সওয়াব, ১০০ নেকি, ১০০ গুনাহ মাফ, সন্ধ্যা পর্যন্ত শয়তান থেকে রক্ষা — সহীহ বুখারি ৩২৯৩, মুসলিম ২৬৯১। সুন্নাহ সংখ্যা ১০০।",
            source = "Sahih al-Bukhari 3293; Sahih Muslim 2691",
        ),
        dhikr(
            id = "hasbunallah",
            name = "Hasbunallahu wa ni'mal wakil",
            arabic = "حَسْبُنَا اللّٰهُ وَنِعْمَ الْوَكِيلُ",
            pronunciation = "হাসবুনাল্লাহু ওয়া নিমাল ওয়াকীল",
            translation = "আল্লাহই আমাদের জন্য যথেষ্ট, তিনিই উত্তম কর্মবিধায়ক — Allah is sufficient for us, and He is the best disposer of affairs",
            lapTarget = 100,
            note = "কুরআন ৩:১৭৩ — উহুদের পর সাহাবিদের এবং আগুনে নিক্ষেপের সময় ইবরাহিম (আঃ)-এর বাণী। নির্দিষ্ট সংখ্যা নেই।",
            source = "Quran 3:173",
        ),
        dhikr(
            id = "baqiyat",
            name = "Subhanallah walhamdulillah wa la ilaha illallahu wallahu akbar",
            arabic = "سُبْحَانَ اللّٰهِ وَالْحَمْدُ لِلّٰهِ وَلَا إِلَٰهَ إِلَّا اللّٰهُ وَاللّٰهُ أَكْبَرُ",
            pronunciation = "সুবহানাল্লাহি ওয়ালহামদু লিল্লাহি ওয়া লা ইলাহা ইল্লাল্লাহু ওয়াল্লাহু আকবার",
            translation = "আল্লাহ পবিত্র, সকল প্রশংসা আল্লাহর, আল্লাহ ছাড়া কোনো উপাস্য নেই, আল্লাহ সর্বমহান — Glory be to Allah, praise be to Allah, there is no god but Allah, and Allah is the Greatest",
            lapTarget = 33,
            note = "আল্লাহর কাছে সবচেয়ে প্রিয় চার বাক্য — সহীহ মুসলিম ২১৩৭। নির্দিষ্ট সংখ্যা নেই।",
            source = "Sahih Muslim 2137",
        ),
        dhikr(
            id = "afuww",
            name = "Allahumma innaka afuwwun tuhibbul afwa fa'fu anni",
            arabic = "اللّٰهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي",
            pronunciation = "আল্লাহুম্মা ইন্নাকা আফুউন তুহিব্বুল আফওয়া ফা'ফু আন্নি",
            translation = "হে আল্লাহ, আপনি ক্ষমাশীল, ক্ষমা ভালোবাসেন, তাই আমাকে ক্ষমা করুন — O Allah, You are Most Forgiving, You love to forgive, so forgive me",
            lapTarget = 33,
            note = "লাইলাতুল কদরের দুআ, নবি (সাঃ) আয়েশা (রাঃ)-কে শিখিয়েছেন — তিরমিযি ৩৫১৩, ইবনে মাজাহ ৩৮৫০ (হাসান)। “কারীম” শব্দ যোগ প্রমাণিত নয়।",
            source = "Jami at-Tirmidhi 3513",
        ),
        dhikr(
            id = "salli_nabiyyina",
            name = "Allahumma salli wa sallim ala nabiyyina Muhammad",
            arabic = "اللّٰهُمَّ صَلِّ وَسَلِّمْ عَلَىٰ نَبِيِّنَا مُحَمَّدٍ",
            pronunciation = "আল্লাহুম্মা সাল্লি ওয়া সাল্লিম আলা নাবিয়্যিনা মুহাম্মাদ",
            translation = "হে আল্লাহ, আমাদের নবি মুহাম্মাদের প্রতি রহমত ও শান্তি বর্ষণ করুন — O Allah, send blessings and peace upon our Prophet Muhammad",
            lapTarget = 33,
            note = "সাধারণ দরূদ; নবি (সাঃ)-এর প্রতি সালাত পাঠের আদেশ কুরআন ৩৩:৫৬-এ।",
            source = "Quran 33:56",
        ),
        dhikr(
            id = "musa_faqir",
            name = "Rabbi inni lima anzalta ilayya min khayrin faqir",
            arabic = "رَبِّ إِنِّي لِمَا أَنْزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ",
            pronunciation = "রব্বি ইন্নি লিমা আনযালতা ইলাইয়া মিন খাইরিন ফাকির",
            translation = "হে আমার রব, আপনি আমার প্রতি যে কল্যাণ নাযিল করবেন আমি তার মুখাপেক্ষী — My Lord, I am in need of whatever good You send down to me",
            lapTarget = 33,
            note = "কুরআন ২৮:২৪ — মাদইয়ানে মুসা (আঃ)-এর দুআ।",
            source = "Quran 28:24",
        ),
        dhikr(
            id = "malik_quddus",
            name = "Subhanal Malikil Quddus",
            arabic = "سُبْحَانَ الْمَلِكِ الْقُدُّوسِ",
            pronunciation = "সুবহানাল মালিকিল কুদ্দূস",
            translation = "পবিত্র সেই বাদশাহ, মহাপবিত্র — Glory be to the Sovereign, the Most Holy",
            lapTarget = 3,
            note = "বিতরের সালামের পর ৩ বার, তৃতীয়বার আওয়াজ উঁচু করে — সুনানে নাসাঈ ১৭৩৩। সুন্নাহ সংখ্যা ৩ (আপনার তালিকায় ৩৩ ছিল)।",
            source = "Sunan an-Nasa'i 1733",
        ),
        dhikr(
            id = "ism_azam",
            name = "Dua with Allah's Greatest Name",
            arabic = "اللّٰهُمَّ إِنِّي أَسْأَلُكَ بِأَنِّي أَشْهَدُ أَنَّكَ أَنْتَ اللّٰهُ لَا إِلَٰهَ إِلَّا أَنْتَ الْأَحَدُ الصَّمَدُ الَّذِي لَمْ يَلِدْ وَلَمْ يُولَدْ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ",
            pronunciation = "আল্লাহুম্মা ইন্নি আসআলুকা বিআন্নি আশহাদু আন্নাকা আনতাল্লাহু লা ইলাহা ইল্লা আনতাল আহাদুস সামাদু আল্লাযি লাম ইয়ালিদ ওয়া লাম ইউলাদ ওয়া লাম ইয়াকুল্লাহু কুফুওয়ান আহাদ",
            translation = "হে আল্লাহ, আমি আপনার কাছে চাই এই সাক্ষ্যের অসিলায় যে আপনিই আল্লাহ, আপনি ছাড়া কোনো উপাস্য নেই, এক, অমুখাপেক্ষী, যিনি জন্ম দেননি ও জন্মগ্রহণ করেননি, তাঁর সমকক্ষ কেউ নেই — O Allah, I ask You by my testimony that You are Allah, there is no god but You, the One, the Eternal Refuge, who neither begets nor is born, and there is none comparable to Him",
            lapTarget = 33,
            note = "আল্লাহর ইসমে আযম দিয়ে দুআ — নবি (সাঃ) বলেছেন এই নামে চাইলে দেওয়া হয়, ডাকলে সাড়া দেওয়া হয়। আবু দাউদ ১৪৯৩, তিরমিযি ৩৪৭৫ (সহীহ)।",
            source = "Sunan Abi Dawud 1493",
        ),
        dhikr(
            id = "hasbiyallah_arsh",
            name = "Hasbiyallahu la ilaha illa huwa alayhi tawakkaltu",
            arabic = "حَسْبِيَ اللّٰهُ لَا إِلَٰهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
            pronunciation = "হাসবিয়াল্লাহু লা ইলাহা ইল্লা হুয়া আলাইহি তাওয়াক্কালতু ওয়া হুয়া রব্বুল আরশিল আযীম",
            translation = "আল্লাহই আমার জন্য যথেষ্ট, তিনি ছাড়া কোনো উপাস্য নেই, তাঁর ওপরই ভরসা করলাম, তিনি মহান আরশের রব — Allah is sufficient for me; there is no god but Him; in Him I put my trust; He is the Lord of the Mighty Throne",
            lapTarget = 7,
            note = "কুরআন ৯:১২৯-এর অংশ। সকালে ও সন্ধ্যায় ৭ বার পড়লে আল্লাহ দুনিয়া-আখিরাতের চিন্তা থেকে যথেষ্ট হন — আবু দাউদ ৫০৮১ (হাসান/সহীহ ইসনাদ)। সুন্নাহ সংখ্যা ৭।",
            source = "Sunan Abi Dawud 5081",
        ),
        dhikr(
            id = "maghfirli",
            name = "Allahummaghfirli",
            arabic = "اللّٰهُمَّ اغْفِرْ لِي",
            pronunciation = "আল্লাহুম্মাগফিরলি",
            translation = "হে আল্লাহ, আমাকে ক্ষমা করুন — O Allah, forgive me",
            lapTarget = 33,
            note = "সংক্ষিপ্ত ইস্তিগফার; নবি (সাঃ) সিজদায় ও অন্যত্র বহুবার পড়তেন।",
            source = null,
        ),
        dhikr(
            id = "aud_bus_taas",
            name = "A'udhu bika minal bu'si wat ta'as",
            arabic = "اللّٰهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْبُؤْسِ وَالتَّعَسِ",
            pronunciation = "আল্লাহুম্মা ইন্নি আউযু বিকা মিনাল বু'সি ওয়াত তা'আস",
            translation = "হে আল্লাহ, আমি দুর্দশা ও ধ্বংস থেকে আপনার আশ্রয় চাই — O Allah, I seek refuge in You from misery and ruin",
            lapTarget = 33,
            note = "⚠️ এই নির্দিষ্ট শব্দে কোনো সহীহ বর্ণনা পাওয়া যায়নি; অর্থ সঠিক। মিলিত অর্থের সহীহ দুআ: “আউযু বিকা মিন জাহদিল বালা…” (বুখারি ৬৩৪৭)।",
            source = null,
        ),
        dhikr(
            id = "parents_rahmah",
            name = "Rabbir hamhuma kama rabbayani sagira",
            arabic = "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
            pronunciation = "রব্বির হামহুমা কামা রব্বায়ানি সাগীরা",
            translation = "হে আমার রব, পিতা-মাতার প্রতি দয়া করুন যেভাবে তারা আমাকে ছোটবেলায় লালন করেছেন — My Lord, have mercy upon them as they raised me when I was small",
            lapTarget = 33,
            note = "কুরআন ১৭:২৪ — পিতা-মাতার জন্য দুআ।",
            source = "Quran 17:24",
        ),
        dhikr(
            id = "jannah_nar",
            name = "Allahumma inni as'alukal jannata wa a'udhu bika minan nar",
            arabic = "اللّٰهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ وَأَعُوذُ بِكَ مِنَ النَّارِ",
            pronunciation = "আল্লাহুম্মা ইন্নি আসআলুকাল জান্নাতা ওয়া আউযু বিকা মিনান নার",
            translation = "হে আল্লাহ, আমি আপনার কাছে জান্নাত চাই এবং জাহান্নাম থেকে আশ্রয় চাই — O Allah, I ask You for Paradise and seek refuge in You from the Fire",
            lapTarget = 3,
            note = "৩ বার চাইলে জান্নাত বলে “তাকে প্রবেশ করাও”, ৩ বার আশ্রয় চাইলে জাহান্নাম বলে “তাকে রক্ষা করো” — তিরমিযি ২৫৭২, ইবনে মাজাহ ৩৮৪৬। সুন্নাহ সংখ্যা ৩।",
            source = "Jami at-Tirmidhi 2572",
        ),
        dhikr(
            id = "istighfar_qayyum",
            name = "Astaghfirullahal azimalladhi la ilaha illa huwal hayyul qayyum wa atubu ilayh",
            arabic = "أَسْتَغْفِرُ اللّٰهَ الْعَظِيمَ الَّذِي لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
            pronunciation = "আস্তাগফিরুল্লাহাল আযীমাল্লাযি লা ইলাহা ইল্লা হুয়াল হাইয়্যুল কাইয়্যূমু ওয়া আতুবু ইলাইহি",
            translation = "আমি ক্ষমা চাই মহান আল্লাহর কাছে, যিনি ছাড়া কোনো উপাস্য নেই, চিরঞ্জীব, সর্বসত্তার ধারক, এবং তাঁর কাছেই তওবা করি — I seek forgiveness of Allah the Mighty, there is no god but Him, the Ever-Living, the Sustainer, and I turn to Him in repentance",
            lapTarget = 33,
            note = "এটি পড়লে গুনাহ মাফ হয় যদিও সে যুদ্ধক্ষেত্র থেকে পালিয়ে থাকে — আবু দাউদ ১৫১৭, তিরমিযি ৩৫৭৭ (হাকিম: সহীহ)। নির্দিষ্ট সংখ্যা নেই।",
            source = "Sunan Abi Dawud 1517",
        ),
        dhikr(
            id = "ya_hayyu_astaghith",
            name = "Ya Hayyu ya Qayyum bi rahmatika astaghith",
            arabic = "يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ",
            pronunciation = "ইয়া হাইয়্যু ইয়া কাইয়্যূমু বিরাহমাতিকা আসতাগীছু",
            translation = "হে চিরঞ্জীব, হে সর্বসত্তার ধারক, আপনার রহমতের অসিলায় সাহায্য প্রার্থনা করি — O Ever-Living, O Sustainer, by Your mercy I seek relief",
            lapTarget = 33,
            note = "কোনো বিষয় নবি (সাঃ)-কে পীড়া দিলে তিনি এটি পড়তেন — তিরমিযি ৩৫২৪ (হাসান ইসনাদ; আলবানি/মুনযিরি)।",
            source = "Jami at-Tirmidhi 3524",
        ),
        dhikr(
            id = "huda_tuqa",
            name = "Allahumma inni as'alukal huda wat tuqa wal afafa wal ghina",
            arabic = "اللّٰهُمَّ إِنِّي أَسْأَلُكَ الْهُدَىٰ وَالتُّقَىٰ وَالْعَفَافَ وَالْغِنَىٰ",
            pronunciation = "আল্লাহুম্মা ইন্নি আসআলুকাল হুদা ওয়াত তুকা ওয়াল আফাফা ওয়াল গিনা",
            translation = "হে আল্লাহ, আমি আপনার কাছে চাই হেদায়েত, তাকওয়া, পবিত্রতা ও অভাবমুক্তি — O Allah, I ask You for guidance, piety, chastity and self-sufficiency",
            lapTarget = 33,
            note = "নবি (সাঃ)-এর দুআ, ইবনে মাসউদ (রাঃ) বর্ণিত — সহীহ মুসলিম ২৭২১।",
            source = "Sahih Muslim 2721",
        ),
        dhikr(
            id = "muqallib_qulub",
            name = "Ya muqallibal qulubi thabbit qalbi ala dinik",
            arabic = "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَىٰ دِينِكَ",
            pronunciation = "ইয়া মুকাল্লিবাল কুলুবি ছাব্বিত কালবি আলা দীনিকা",
            translation = "হে অন্তরসমূহের পরিবর্তনকারী, আমার অন্তরকে আপনার দ্বীনের ওপর অবিচল রাখুন — O Turner of hearts, keep my heart firm upon Your religion",
            lapTarget = 33,
            note = "নবি (সাঃ) অধিক পড়তেন — তিরমিযি ২১৪০ (হাসান)।",
            source = "Jami at-Tirmidhi 2140",
        ),
        dhikr(
            id = "hamm_hazan",
            name = "Allahumma inni a'udhu bika minal hammi wal hazan",
            arabic = "اللّٰهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ",
            pronunciation = "আল্লাহুম্মা ইন্নি আউযু বিকা মিনাল হাম্মি ওয়াল হাযান",
            translation = "হে আল্লাহ, আমি দুশ্চিন্তা ও দুঃখ থেকে আপনার আশ্রয় চাই — O Allah, I seek refuge in You from anxiety and grief",
            lapTarget = 33,
            note = "পূর্ণ দুআ: “…ওয়াল আজযি ওয়াল কাসাল, ওয়াল জুবনি ওয়াল বুখল, ওয়া দালাইদ দাইন ওয়া গালাবাতির রিজাল” — সহীহ বুখারি ৬৩৬৯।",
            source = "Sahih al-Bukhari 6369",
        ),
        dhikr(
            id = "ya_muizz",
            name = "Ya Mu'izz",
            arabic = "يَا مُعِزُّ",
            pronunciation = "ইয়া মুইয্‌যু",
            translation = "হে সম্মানদাতা — O Bestower of honour",
            lapTarget = 33,
            note = "⚠️ আল্লাহর একটি নাম। নির্দিষ্ট সংখ্যায় এই নাম জপের কোনো সহীহ বর্ণনা নেই; দুআয় আল্লাহকে তাঁর সুন্দর নামে ডাকা বৈধ (কুরআন ৭:১৮০)।",
            source = null,
        ),
        dhikr(
            id = "khayr_kulli_amr",
            name = "Allahumma khir li fi kulli amrin antaziruh",
            arabic = "اللّٰهُمَّ خِرْ لِي فِي كُلِّ أَمْرٍ أَنْتَظِرُهُ",
            pronunciation = "আল্লাহুম্মা খির লি ফি কুল্লি আমরিন আনতাযিরুহু",
            translation = "হে আল্লাহ, আমি যে বিষয়ের অপেক্ষায় আছি তার প্রতিটিতে কল্যাণ দিন — O Allah, choose what is best for me in every matter I await",
            lapTarget = 33,
            note = "⚠️ এই শব্দে সহীহ হাদিসে কোনো বর্ণনা পাওয়া যায়নি; অর্থ ইসতিখারার হাদিসের কাছাকাছি (বুখারি ১১৬২)। সাধারণ দুআ হিসেবে পড়া যায়।",
            source = null,
        ),
        dhikr(
            id = "yassir_la_tuassir",
            name = "Allahumma yassir wa la tu'assir",
            arabic = "اللّٰهُمَّ يَسِّرْ وَلَا تُعَسِّرْ",
            pronunciation = "আল্লাহুম্মা ইয়াসসির ওয়ালা তুআসসির",
            translation = "হে আল্লাহ, সহজ করুন, কঠিন করবেন না — O Allah, make it easy and do not make it difficult",
            lapTarget = 33,
            note = "হাদিসের বাণী “ইয়াসসিরু ওয়ালা তুআসসিরু” (বুখারি ৬৯) থেকে গৃহীত দুআ-রূপ; হুবহু এই রূপে ছয় গ্রন্থে নেই। বৈধ সাধারণ দুআ।",
            source = "Sahih al-Bukhari 69",
        ),
        dhikr(
            id = "nuh_maghlub",
            name = "Rabbi inni maghlubun fantasir",
            arabic = "رَبِّ إِنِّي مَغْلُوبٌ فَانْتَصِرْ",
            pronunciation = "রব্বি ইন্নি মাগলুবুন ফানতাসির",
            translation = "হে আমার রব, আমি পরাভূত, তাই সাহায্য করুন — My Lord, I am overpowered, so help me",
            lapTarget = 100,
            note = "কুরআন ৫৪:১০ — নূহ (আঃ)-এর দুআ। তিলাওয়াতে “আন্নি”, দুআ হিসেবে “ইন্নি”। (আপনার তালিকায় ৩৩ ও ১০০ দুটোই ছিল।)",
            source = "Quran 54:10",
        ),
        dhikr(
            id = "short_salawat",
            name = "Sallallahu alaihi wa sallam",
            arabic = "صَلَّى اللّٰهُ عَلَيْهِ وَسَلَّمَ",
            pronunciation = "সাল্লাল্লাহু আলাইহি ওয়া সাল্লাম",
            translation = "আল্লাহ তাঁর ওপর রহমত ও শান্তি বর্ষণ করুন — May Allah send blessings and peace upon him",
            lapTarget = 33,
            note = "নবি (সাঃ)-এর নাম উল্লেখে সংক্ষিপ্ত সালাত।",
            source = null,
        ),
        dhikr(
            id = "malikul_haqq",
            name = "La ilaha illallahu malikul haqqul mubin",
            arabic = "لَا إِلَٰهَ إِلَّا اللّٰهُ الْمَلِكُ الْحَقُّ الْمُبِينُ",
            pronunciation = "লা ইলাহা ইল্লাল্লাহু মালিকুল হাক্কুল মুবীন",
            translation = "আল্লাহ ছাড়া কোনো উপাস্য নেই, সত্য অধিপতি, সুস্পষ্ট — There is no god but Allah, the Sovereign, the Truth, the Manifest",
            lapTarget = 100,
            note = "⚠️ ১০০ বার পড়লে দারিদ্র্যমুক্তি ইত্যাদির হাদিসকে দারাকুতনি ও যাহাবি দুর্বল/জাল বলেছেন। বাক্যটির অর্থ সহীহ; নির্দিষ্ট ফযীলতের বিশ্বাস ছাড়া তাসবিহ হিসেবে পড়া যায়।",
            source = null,
        ),
        dhikr(
            id = "kalimat_tammat",
            name = "A'udhu bikalimatillahit tammati min sharri ma khalaq",
            arabic = "أَعُوذُ بِكَلِمَاتِ اللّٰهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
            pronunciation = "আউযু বিকালিমাতিল্লাহিত তাম্মাতি মিন শাররি মা খালাক",
            translation = "আমি আল্লাহর পরিপূর্ণ বাণীসমূহের আশ্রয় চাই তাঁর সৃষ্টির অনিষ্ট থেকে — I seek refuge in the perfect words of Allah from the evil of what He created",
            lapTarget = 3,
            note = "সন্ধ্যায় ৩ বার পড়লে সে রাতে বিষাক্ত প্রাণী ক্ষতি করবে না — সহীহ মুসলিম ২৭০৯। সুন্নাহ সংখ্যা ৩।",
            source = "Sahih Muslim 2709",
        ),
        dhikr(
            id = "rabbighfir_tawwab",
            name = "Rabbighfir li wa tub alayya innaka antat tawwabur rahim",
            arabic = "رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ",
            pronunciation = "রব্বিগফির লি ওয়া তুব আলাইয়া ইন্নাকা আনতাত তাওয়াবুর রাহীম",
            translation = "হে আমার রব, আমাকে ক্ষমা করুন ও আমার তওবা কবুল করুন, নিশ্চয়ই আপনি তওবা কবুলকারী পরম দয়ালু — My Lord, forgive me and accept my repentance; indeed You are the Accepter of repentance, the Merciful",
            lapTarget = 100,
            note = "ইবনে উমার (রাঃ): নবি (সাঃ) এক বৈঠকে ১০০ বার এটি পড়তেন — আবু দাউদ ১৫১৬, তিরমিযি ৩৪৩৪ (সহীহ)। সুন্নাহ সংখ্যা ১০০।",
            source = "Jami at-Tirmidhi 3434",
        ),
        dhikr(
            id = "adada_khalqih",
            name = "Subhanallahi wa bihamdihi adada khalqih",
            arabic = "سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ عَدَدَ خَلْقِهِ وَرِضَا نَفْسِهِ وَزِنَةَ عَرْشِهِ وَمِدَادَ كَلِمَاتِهِ",
            pronunciation = "সুবহানাল্লাহি ওয়া বিহামদিহি আদাদা খালকিহি ওয়া রিদা নাফসিহি ওয়া যিনাতা আরশিহি ওয়া মিদাদা কালিমাতিহি",
            translation = "আল্লাহ পবিত্র ও তাঁরই প্রশংসা—তাঁর সৃষ্টির সংখ্যা, তাঁর সন্তুষ্টি, তাঁর আরশের ওজন ও তাঁর বাণীসমূহের কালি পরিমাণ — Glory and praise be to Allah, as many as His creation, as pleases Him, as the weight of His Throne and the ink of His words",
            lapTarget = 3,
            note = "জুওয়াইরিয়া (রাঃ)-কে নবি (সাঃ) শিখিয়েছেন, ৩ বার পড়লে সকাল থেকে পড়া সব যিকরের চেয়ে ভারী — সহীহ মুসলিম ২৭২৬। সুন্নাহ সংখ্যা ৩; পূর্ণ রূপটি দেওয়া হলো।",
            source = "Sahih Muslim 2726",
        ),
        dhikr(
            id = "istighfar_ghafur",
            name = "Astaghfirullah innallaha ghafurun rahim",
            arabic = "أَسْتَغْفِرُ اللّٰهَ إِنَّ اللّٰهَ غَفُورٌ رَحِيمٌ",
            pronunciation = "আস্তাগফিরুল্লাহ ইন্নাল্লাহা গাফূরুর রাহীম",
            translation = "আমি আল্লাহর কাছে ক্ষমা চাই, নিশ্চয়ই আল্লাহ ক্ষমাশীল পরম দয়ালু — I seek Allah's forgiveness; indeed Allah is Forgiving, Merciful",
            lapTarget = 33,
            note = "⚠️ একক হাদিস-বর্ণনা নয়; ইস্তিগফার + কুরআনি বাক্যাংশের (যেমন ৪:১০৬) সমন্বয়। অর্থ সহীহ।",
            source = null,
        ),
        dhikr(
            id = "kfini_halalik",
            name = "Allahumma-kfini bi halalika an haramik",
            arabic = "اللّٰهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ",
            pronunciation = "আল্লাহুম্মাকফিনি বিহালালিকা আন হারামিকা ওয়া আগনিনি বিফাদলিকা আম্মান সিওয়াক",
            translation = "হে আল্লাহ, আপনার হালাল দিয়ে আমাকে হারাম থেকে মুক্ত রাখুন এবং আপনার অনুগ্রহে অন্য সবার থেকে অমুখাপেক্ষী করুন — O Allah, suffice me with what You have made lawful against what You have forbidden, and make me independent of all besides You by Your grace",
            lapTarget = 33,
            note = "নবি (সাঃ) আলী (রাঃ)-কে ঋণমুক্তির জন্য শিখিয়েছেন — তিরমিযি ৩৫৬৩ (হাসান)।",
            source = "Jami at-Tirmidhi 3563",
        ),
        dhikr(
            id = "sharh_sadr",
            name = "Rabbi-shrah li sadri wa yassir li amri",
            arabic = "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي وَاحْلُلْ عُقْدَةً مِنْ لِسَانِي يَفْقَهُوا قَوْلِي",
            pronunciation = "রব্বিশরাহ লি সাদরি ওয়া ইয়াসসির লি আমরি ওয়াহলুল উকদাতান মিন লিসানি ইয়াফকাহু কাওলি",
            translation = "হে আমার রব, আমার বক্ষ প্রশস্ত করুন, কাজ সহজ করুন এবং জিহ্বার জড়তা দূর করুন যাতে তারা আমার কথা বোঝে — My Lord, expand my chest, ease my task, and untie the knot from my tongue so they understand my speech",
            lapTarget = 33,
            note = "কুরআন ২০:২৫-২৮ — তূর পাহাড়ে মুসা (আঃ)-এর দুআ।",
            source = "Quran 20:25-28",
        ),
        dhikr(
            id = "fath_mubin",
            name = "Inna fatahna laka fathan mubina",
            arabic = "إِنَّا فَتَحْنَا لَكَ فَتْحًا مُبِينًا",
            pronunciation = "ইন্না ফাতাহনা লাকা ফাতহাম মুবীনা",
            translation = "নিশ্চয়ই আমি আপনাকে সুস্পষ্ট বিজয় দান করেছি — Indeed, We have given you a clear conquest",
            lapTarget = 33,
            note = "কুরআন ৪৮:১ — সূরা আল-ফাতহের প্রথম আয়াত।",
            source = "Quran 48:1",
        ),
        dhikr(
            id = "ilm_nafi",
            name = "Allahumma inni as'aluka ilman nafi'an",
            arabic = "اللّٰهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلًا مُتَقَبَّلًا",
            pronunciation = "আল্লাহুম্মা ইন্নি আসআলুকা ইলমান নাফিআন ওয়া রিযকান তাইয়্যিবান ওয়া আমালান মুতাকাব্বালান",
            translation = "হে আল্লাহ, আমি আপনার কাছে চাই উপকারী জ্ঞান, পবিত্র রিযিক ও কবুলযোগ্য আমল — O Allah, I ask You for beneficial knowledge, wholesome provision and accepted deeds",
            lapTarget = 100,
            note = "নবি (সাঃ) ফজরের পর পড়তেন, উম্মে সালামা (রাঃ) বর্ণিত — ইবনে মাজাহ ৯২৫ (সহীহ)। নির্দিষ্ট সংখ্যা নেই।",
            source = "Sunan Ibn Majah 925",
        ),
        dhikr(
            id = "nafs_mutmainnah",
            name = "Allahumma inni as'aluka nafsan bika mutma'innah",
            arabic = "اللّٰهُمَّ إِنِّي أَسْأَلُكَ نَفْسًا بِكَ مُطْمَئِنَّةً تُؤْمِنُ بِلِقَائِكَ وَتَرْضَىٰ بِقَضَائِكَ وَتَقْنَعُ بِعَطَائِكَ",
            pronunciation = "আল্লাহুম্মা ইন্নি আসআলুকা নাফসান বিকা মুতমাইন্নাতান তু'মিনু বিলিকা'ইকা ওয়া তারদা বিকাদা'ইকা ওয়া তাকনাউ বিআতা'ইকা",
            translation = "হে আল্লাহ, আমি আপনার কাছে চাই এমন প্রশান্ত আত্মা যা আপনার সাক্ষাতে বিশ্বাস রাখে, আপনার ফয়সালায় সন্তুষ্ট ও আপনার দানে পরিতৃপ্ত থাকে — O Allah, I ask You for a soul at peace with You, believing in meeting You, pleased with Your decree and content with Your provision",
            lapTarget = 33,
            note = "নবি (সাঃ) এক ব্যক্তিকে শিখিয়েছেন, আবু উমামা (রাঃ) বর্ণিত — তাবারানি; ইবনে হিব্বান সহীহ বলেছেন।",
            source = "al-Mu'jam al-Kabir (Tabarani)",
        ),
        dhikr(
            id = "istighfar_atubu",
            name = "Astaghfirullaha wa atubu ilayh",
            arabic = "أَسْتَغْفِرُ اللّٰهَ وَأَتُوبُ إِلَيْهِ",
            pronunciation = "আস্তাগফিরুল্লাহা ওয়া আতুবু ইলাইহি",
            translation = "আমি আল্লাহর কাছে ক্ষমা চাই এবং তাঁর কাছে তওবা করি — I seek Allah's forgiveness and turn to Him in repentance",
            lapTarget = 100,
            note = "নবি (সাঃ) দিনে ১০০ বার (অন্য বর্ণনায় ৭০ বারের বেশি) ইস্তিগফার করতেন — সহীহ মুসলিম ২৭০২, বুখারি ৬৩০৭। সুন্নাহ সংখ্যা ১০০।",
            source = "Sahih Muslim 2702",
        ),
        dhikr(
            id = "mother_barakah",
            name = "Dua for one's mother",
            arabic = "اللّٰهُمَّ اجْعَلْ لِأُمِّي بَرَكَةً فِي عُمُرِهَا",
            pronunciation = "আল্লাহুম্মাজআল লি উম্মি বারাকাতান ফি উমুরিহা",
            translation = "হে আল্লাহ, আমার মায়ের হায়াতে বরকত দিন — O Allah, place blessing in my mother's life",
            lapTarget = 33,
            note = "⚠️ সুন্নাহ থেকে নির্দিষ্ট কোনো দুআ নয়; মায়ের জন্য ব্যক্তিগত দুআ। মূল তালিকার শব্দ (“জুখফ”) অস্পষ্ট, অর্থ অনুযায়ী শুদ্ধ করা হয়েছে।",
            source = null,
        ),
        dhikr(
            id = "maridtu_yashfin",
            name = "Wa idha maridtu fahuwa yashfin",
            arabic = "وَإِذَا مَرِضْتُ فَهُوَ يَشْفِينِ",
            pronunciation = "ওয়া ইযা মারিদতু ফাহুয়া ইয়াশফীন",
            translation = "আর যখন আমি অসুস্থ হই তখন তিনিই আমাকে সুস্থ করেন — And when I am ill, it is He who cures me",
            lapTarget = 33,
            note = "কুরআন ২৬:৮০ — ইবরাহিম (আঃ)-এর বাণী; শিফার ছয় আয়াতের একটি।",
            source = "Quran 26:80",
        ),
    )

    // Presets seed as favorites so they appear on Home out of the box; the user
    // unstars one on the Routines page to remove it from Home.
    val presetRoutines: List<RoutineEntity> = listOf(
        RoutineEntity(id = "morning", name = "Morning Dhikr", isPreset = true, isFavorite = true, createdAt = SEED_TIMESTAMP, updatedAt = SEED_TIMESTAMP),
        RoutineEntity(id = "evening", name = "Evening Dhikr", isPreset = true, isFavorite = true, createdAt = SEED_TIMESTAMP, updatedAt = SEED_TIMESTAMP),
        RoutineEntity(id = "after_salah", name = "After Salah", isPreset = true, isFavorite = true, createdAt = SEED_TIMESTAMP, updatedAt = SEED_TIMESTAMP),
        RoutineEntity(id = "before_sleep", name = "Before Sleep", isPreset = true, isFavorite = true, createdAt = SEED_TIMESTAMP, updatedAt = SEED_TIMESTAMP),
    )

    val presetRoutineSteps: List<RoutineStepEntity> = listOf(
        // Morning Dhikr: SubhanAllah x33, Alhamdulillah x33, AllahuAkbar x34 (matches
        // the prototype's ROUTINES array and design README's own example exactly —
        // design/Dhikr Android App.dc.html's `morning`/`salah` routine definitions)
        RoutineStepEntity(routineId = "morning", tasbihId = "subhan", stepOrder = 0, targetCount = 33),
        RoutineStepEntity(routineId = "morning", tasbihId = "hamd", stepOrder = 1, targetCount = 33),
        RoutineStepEntity(routineId = "morning", tasbihId = "akbar", stepOrder = 2, targetCount = 34),
        // Evening Dhikr: same three, evening framing — no separate evening-specific
        // prototype data exists, so this reuses the same structure as Morning per
        // the plan's own "Evening Dhikr" listing (plan.md §22) which gives no
        // distinct counts of its own.
        RoutineStepEntity(routineId = "evening", tasbihId = "subhan", stepOrder = 0, targetCount = 33),
        RoutineStepEntity(routineId = "evening", tasbihId = "hamd", stepOrder = 1, targetCount = 33),
        RoutineStepEntity(routineId = "evening", tasbihId = "akbar", stepOrder = 2, targetCount = 34),
        // After Salah: matches the prototype's `salah` routine exactly (same 3 steps)
        RoutineStepEntity(routineId = "after_salah", tasbihId = "subhan", stepOrder = 0, targetCount = 33),
        RoutineStepEntity(routineId = "after_salah", tasbihId = "hamd", stepOrder = 1, targetCount = 33),
        RoutineStepEntity(routineId = "after_salah", tasbihId = "akbar", stepOrder = 2, targetCount = 34),
        // Before Sleep: matches the prototype's `sleep` routine exactly —
        // Astaghfirullah x100, Subhanallahi wa bihamdihi x100
        RoutineStepEntity(routineId = "before_sleep", tasbihId = "istighfar", stepOrder = 0, targetCount = 100),
        RoutineStepEntity(routineId = "before_sleep", tasbihId = "bihamdihi", stepOrder = 1, targetCount = 100),
    )
}
